import { Language } from '../contexts/LanguageContext';

const astigmatizmTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    pageTitle: 'ასტიგმატიზმი',
    heroTitle1: 'მხედველობის აღდგენა',
    heroTitle2: 'ინოვაციური აპარატურით.',
    heroTitle3: 'სათვალე ან ლინზები საჭირო აღარ არის.',
    heroClinical: 'კლინიკურად აპრობირებულია. — რისკის და ალერგიის გარეშე. — სტაბილური შედეგი. — უმტკივნეულო და უსაფრთხო მეთოდი.',
    consultation: 'მიღებაზე ჩაწერა',
    contact: 'კონტაქტი',
    definitionText1: 'თვალის ოპტიკური სისტემის დეფექტია (რეფრაქციული მანკი), როდესაც გამოსახულების სიმკვეთრე ასიმეტრიულია თვალის ვერტიკალურ და ჰორიზონტალურ მერიდიანებში.',
    definitionText2: 'ასტიგმატიზმი არ არის დამოუკიდებელი ანომალია, ის ყოველთვის ახლო მხედველობასთან ან შორს მხედველობასთან არის შერწყმული. ასტიგმატიზმის დროს, შესაძლოა ორივე მანკის არსებობა თვალის სხვა და სხვა მერიდიანში.',
    successRateBanner: 'მაგოთერაპიით მხედველობის აღდგენა\n98% შემთხვევაში შესაძლებელია.',
    formsTitle: 'ასტიგმატიზმის ფორმები:',
    congenitalTitle: 'თანდაყოლილი:',
    congenitalText1: 'მუცლად ყოფნის დროს, სხვა და სხვა პათოლოგიური პროცესები იწვევს ასტიგმატიზმის ჩამოყალიბებას, რომელიც მემკვიდრულად გადაეცემა.',
    congenitalText2: 'ბავშვებში, სუსტად გამოხატული ორივე თვალის ასტიგმატიზმი 0,25–0,5 დიოპტრია, ნორმის ფარგლებში ითვლება. ხოლო 0,75 დიოპტრია და მეტი, იწვევს დროთა განმავლობაში ბინოკულარული მხედველობის დათრგუნვას. მხედველობის ანალიზატორის უჯრედები ვეღარ ვითარდებიან, ტვინი ვერ ამუშავებს სინათლის სიგნალს და ხშირად "ზარმაცი თვალის" სინდრომი — ამბლიოპია ან/და სიელმე ვითარდება.',
    adviceTitle: 'რჩევა!',
    adviceLine1: 'პატარა დაუყოვნებლივ გაასინჯეთ ექიმს,',
    adviceLine2: 'თუ რომელიმე მშობელს აქვს ასტიგმატიზმი.',
    adviceLine3: 'აარიდეთ მას ამბლიოპია ან სიელმე.',
    seeMoreAmblyopia: 'იხილეთ მეტი → ამბლიოპია',
    seeMoreSielme: 'იხილეთ მეტი → სიელმე',
    acquiredTitle: 'შეძენილი ფორმა:',
    acquiredText: 'ხშირად გართულების სახით ვლინდება თვალის სტრუქტურების ტრავმული ან ინფექციური დაზიანების გამო, რქოვანას კონუსის ფორმის მიღების შემთხვევაში, როდესაც კერატოკონუსი ვითარდება. შესაძლოა განვითარდეს ოპერაციული ჩარევის შედეგად.',
    symptomsBanner: 'სიმპტომები',
    childrenTitle: 'ბავშვებში',
    childrenText: 'ბავშვები ვერ ათვითცნობიერებენ, რომ გამოსახულება არა მკვეთრი და წაშლილია, რადგან არ იციან რას ნიშნავს კარგად ხედვა. დროთა განმავლობაში გაუარესებული მხედველობა იწვევს ბავშვში გაღიზიანებას, ჭირვეულობას, რასაც ხშირად ხასიათის თვისებებს მიაწერენ. ბავშვი დროულად უნდა იყოს გამოკვლეული ოფთალმოლოგის მიერ, რათა სკოლაში წასვლისას, როდესაც მხედველობითი დატვირთვა იზრდება, არ მოხდეს დაავადების პროგრესირება.',
    childrenSymptomsSubtitle: 'სპეციფიური სიმპტომები არ არსებობს. მიაქციეთ ყურადღება:',
    childSymptoms: [
      'ჭუტავს თვალებს შორს ხედვისას ან კითხვისას.',
      'თავს გვერდზე ხრის საგნებზე დაკვირვებისას.',
      'უჩივის თავბრუსხვევას, თავის ტკივილს.',
      'გაურბის მხედველობით დატვირთვას.',
      'კითხვისას შესაძლოა გადაადგილოს ასოები სიტყვაში.',
      'უჩივის თავის ტკივილს, განსაკუთრებით მხედველობის დატვირთვის შემდეგ.',
    ],
    adultsTitle: 'მოზრდილებში',
    adultSymptoms: [
      'წაშლილი, არა მკვეთრი მხედველობა.',
      'გაორება.',
      'თვალის ჩაწითლება.',
      'თვალის დაღლილობა.',
      'თავის ტკივილი.',
      '"ბუზების" არსებობა თვალების წინ.',
    ],
    correctionTitle: 'ასტიგმატიზმის კორექცია',
    correctionText1: 'ასტიგმატიზმის დროს 18 წლამდე, მკურნალობა არ არსებობს. გავრცელებულია მხედველობის კორეგირება სპეციალური ცილინდრული ან შერეული კომპონენტიანი სათვალის დანიშვნით და სხვა და სხვა ლინზების შერჩევით. სათვალეებით და ლინზებით მხედველობის კორექცია ხშირად დისკომფორტს იწვევს პაციენტებში, ასტიგმატიზმის ტიპისა და სტადიიდან გამომდინარე. ნებისმიერი სათვალე (ლინზა) მხოლოდ ეხმარება თვალს უკეთ დაინახოს და არ მკურნალობს მას, ამიტომაც დიოპტრიები იზრდება, ხოლო მხედველობა კლებულობს.',
    correctionText2: '18–20 წლის ზემოთ კი ხდება ასტიგმატიზმის მკურნალობა ოპტიკური ნაწილის სიმრუდის შეცვლით, ქირურგიული/ლაზერული ოპერაციებით, როდესაც ხელოვნურად იცვლება რქოვანას სიმრუდე.',
    ownEyesBanner: 'შეხედეთ სამყაროს საკუთარი თვალებით!',
    magotherapyTitle: 'მაგოთერაპია.',
    magotherapyText1: 'ასტიგმატიზმის და სხვა რეფრაქციული მანკების სამკურნალოდ დღევანდელ რეალობაში გავრცელებულია ქირურგიული/ლაზერული ოპერაციებით თვალის ოპტიკური ნაწილზე ზემოქმედება.',
    magotherapyText2: 'მეცნიერები მუდმივ ძიებაში არიან დახვეწონ და მოძებნონ თვალის სამკურნალოდ უსაფრთხო და ეფექტური მეთოდები. ამიტომაც მე–20 საუკუნის მიწურულს, მოსკოვის თვალის მიკროქირურგიის ინსტიტუტში, სვიატოსლავ ფეოდოროვის ხელმძღვანელობით იყო შემუშავებული, დანერგილი და დაპატენტებული თვალის მკურნალობის უსაფრთხო და ფიზიოლოგიური მეთოდი — მაგოთერაპია.',
    magotherapyText3: 'ძველი ფოტოაპარატის მსგავსად, რომელსაც აქვს ოპტიკური ნაწილი და ფირი, თვალიც შედგება ოპტიკური ნაწილისგან (რქოვანა, ბროლი, მინისებური სხეული) და ფირისგან (ბადურა გარსი).',
    magotherapyText4: 'რაც არუნდა ხარისხიანი იყოს ოპტიკური ნაწილი, თუ ფირზე (ბადურაზე) ნებისმიერი მცირე ხარვეზი მაინც აღინიშნება, გამოსახულება ფოტოზე წაშლილი და არა მკვეთრი გამოვა.',
    magotherapyText5: 'მაგოთერაპიით მკურნალობისას ჩვენ არ ვეხებით თვალის ოპტიკურ ნაწილს (რქოვანა, ბროლი). სპეციალური აპარატურა, რომელსაც მორიგეობით კანის ზემოდან ვანთავსებთ, იწვევს ბადურა გარსის და მხედველობის ტრაქტის უჯრედებში დადებით ბიოქიმიურ ცვლილებებს. შედეგად სინათლის სიგნალის ნერვულ იმპულსად გარდაქმნის პროცესი აქტიურ ფაზაში გადადის. ეს და სხვა ფაქტორები უზრუნველყოფენ მხედველობის აღდგენას წამის 0,002 ნაწილში.',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    since1996: 'ასტიგმატიზმით 1996 წლიდან 2025 წლამდე 10000ზე მეტ პაციენტს , ვუმკურნალეთ მაგოთერაპიით.',
    resultsBanner: 'მაგოთერაპიის შედეგები:',
    treatmentResults: [
      'გამოკვლევიდან მეორე დღეს პაციენტი ყველგან აღიქვამს მომატებულ მხედველობას.',
      'მკვეთრი, მომატებული მხედველობა "გაელვებების" სახით აღიქმება.',
      'ათ დღიანი პროცედურების შედეგად, მკვეთრი მხედველობის ხანგრძლივობა იზრდება.',
      'ტვინი "სწავლობს" ნერვული იმპულსის გადამუშავებას, სათვალე და ლინზები საჭირო აღარ არის.',
      'ჩერდება / ნელდება დაავადების პროგრესირება.',
      'განმეორებითი მკურნალობის კურსი იწვევს დამატებით მხედველობის მომატებას.',
    ],
    successRateResult: 'ასტიგმატიზმის მკურნალობისას 98% შემთხვევაში აღინიშნება პოზიტიური შედეგი',
    patientVideosTitle: 'პაციენტების გამოცდილება',
    contactToday: 'დაგვიკავშირდი დღესვე',
    modalTitle: 'ექიმთან მიღებაზე ჩაწერა',
    labelDate: 'სასურველი თარიღი',
    labelName: 'სახელი გვარი',
    labelEmail: 'Email',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    pageTitle: 'ASTIGMATISM',
    heroTitle1: 'Vision restoration',
    heroTitle2: 'with innovative apparatus.',
    heroTitle3: 'Glasses or lenses are no longer needed.',
    heroClinical: 'Clinically proven. — No risk and no allergy. — Stable results. — Painless and safe method.',
    consultation: 'Consultation',
    contact: 'Contact',
    definitionText1: 'A defect of the eye\'s optical system (refractive error), where image sharpness is asymmetric in the vertical and horizontal meridians of the eye.',
    definitionText2: 'Astigmatism is not an independent anomaly, it is always combined with nearsightedness or farsightedness. In astigmatism, both defects may exist in different meridians of the eye.',
    successRateBanner: 'Vision restoration with Magotherapy\nis possible in 98% of cases.',
    formsTitle: 'FORMS OF ASTIGMATISM:',
    congenitalTitle: 'Congenital:',
    congenitalText1: 'During pregnancy, various pathological processes cause the formation of astigmatism, which is passed down hereditarily.',
    congenitalText2: 'In children, mildly expressed astigmatism of both eyes at 0.25–0.5 diopters is considered within normal limits. However, 0.75 diopters and above causes suppression of binocular vision over time. Visual analyzer cells can no longer develop, the brain cannot process the light signal, and often "lazy eye" syndrome — amblyopia and/or strabismus — develops.',
    adviceTitle: 'ADVICE!',
    adviceLine1: 'Have the child examined by a doctor immediately,',
    adviceLine2: 'if either parent has astigmatism.',
    adviceLine3: 'Protect them from amblyopia or strabismus.',
    seeMoreAmblyopia: 'See more → Amblyopia',
    seeMoreSielme: 'See more → Strabismus',
    acquiredTitle: 'Acquired form:',
    acquiredText: 'Often appears as a complication due to traumatic or infectious damage to the eye structures, in cases where the cornea takes a conical shape — when keratoconus develops. May develop as a result of surgical intervention.',
    symptomsBanner: 'SYMPTOMS',
    childrenTitle: 'In children',
    childrenText: 'Children cannot realize that the image is blurry and unclear, as they do not know what it means to see well. Over time, worsened vision causes irritability and fussiness in the child, which is often attributed to personality traits. The child should be examined by an ophthalmologist in a timely manner, so that when starting school, when visual load increases, disease progression does not occur.',
    childrenSymptomsSubtitle: 'There are no specific symptoms. Pay attention to:',
    childSymptoms: [
      'Squints eyes when seeing far or reading.',
      'Tilts head to the side when observing objects.',
      'Complains of dizziness, headaches.',
      'Avoids visual load.',
      'May transpose letters in words when reading.',
      'Complains of headaches, especially after visual strain.',
    ],
    adultsTitle: 'In adults',
    adultSymptoms: [
      'Blurred, not sharp vision.',
      'Double vision.',
      'Eye redness.',
      'Eye fatigue.',
      'Headache.',
      'Presence of "floaters" before the eyes.',
    ],
    correctionTitle: 'ASTIGMATISM CORRECTION',
    correctionText1: 'In astigmatism under 18 years of age, there is no treatment. Vision correction with special cylindrical or mixed-component glasses and selection of various lenses is widespread. Vision correction with glasses and lenses often causes discomfort in patients, depending on the type and stage of astigmatism. Any glasses (lenses) only help the eye to see better and do not treat it, which is why diopters increase and vision decreases.',
    correctionText2: 'Above 18–20 years, astigmatism treatment involves changing the curvature of the optical part through surgical/laser operations, when the curvature of the cornea is artificially changed.',
    ownEyesBanner: 'SEE WITH YOUR OWN EYES!',
    magotherapyTitle: 'MAGOTHERAPY.',
    magotherapyText1: 'For treating astigmatism and other refractive errors, surgical/laser operations affecting the optical part of the eye are common in today\'s reality.',
    magotherapyText2: 'Scientists are constantly searching to refine and find safe and effective methods for eye treatment. That is why, at the end of the 20th century, at the Moscow Institute of Eye Microsurgery, under the leadership of Svyatoslav Fyodorov, a safe and physiological method for eye treatment — Magotherapy — was developed, implemented, and patented.',
    magotherapyText3: 'Like an old camera, which has an optical part and film, the eye also consists of an optical part (cornea, lens, vitreous body) and film (retina).',
    magotherapyText4: 'With quality optics present, if even any small defect is noted on the film (retina), the image in the photo will come out blurred and not sharp.',
    magotherapyText5: 'During Magotherapy treatment, we do not touch the optical part of the eye (cornea, lens). Special apparatus, which we alternately place on the skin, causes positive biochemical changes in the cells of the retinal membrane and visual tract. As a result, the process of converting light signals into nerve impulses enters an active phase. These and other factors ensure vision restoration in 0.002 seconds.',
    seeMoreMago: 'See more → Magotherapy',
    since1996: 'From 1996 to 2025, we have treated over 10,000 patients with astigmatism using Magotherapy.',
    resultsBanner: 'RESULTS OF MAGOTHERAPY:',
    treatmentResults: [
      'The day after the examination, the patient notices improved vision everywhere.',
      'Sharp, improved vision is perceived in the form of "flashes".',
      'After ten days of procedures, the duration of sharp vision increases.',
      'The brain "learns" to process nerve impulses, glasses and lenses are no longer needed.',
      'Disease progression stops / slows.',
      'A repeat course of treatment leads to additional vision improvement.',
    ],
    successRateResult: 'In astigmatism treatment, we have positive results in 98% of cases',
    patientVideosTitle: 'PATIENT EXPERIENCE',
    contactToday: 'Contact Us Today',
    modalTitle: 'Book an Appointment with the Doctor',
    labelDate: 'Preferred Date',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    pageTitle: 'АСТИГМАТИЗМ',
    heroTitle1: 'Восстановление зрения',
    heroTitle2: 'с инновационной аппаратурой.',
    heroTitle3: 'Очки или линзы больше не нужны.',
    heroClinical: 'Клинически апробировано. — Без риска и аллергии. — Стабильный результат. — Безболезненный и безопасный метод.',
    consultation: 'Консультация',
    contact: 'Контакт',
    definitionText1: 'Дефект оптической системы глаза (рефракционный изъян), при котором чёткость изображения асимметрична в вертикальном и горизонтальном меридианах глаза.',
    definitionText2: 'Астигматизм — не самостоятельная аномалия, он всегда сочетается с близорукостью или дальнозоркостью. При астигматизме возможно наличие обоих дефектов в разных меридианах глаза.',
    successRateBanner: 'Восстановление зрения Маготерапией\nвозможно в 98% случаев.',
    formsTitle: 'ФОРМЫ АСТИГМАТИЗМА:',
    congenitalTitle: 'Врождённая:',
    congenitalText1: 'Во время внутриутробного развития различные патологические процессы вызывают формирование астигматизма, который передаётся по наследству.',
    congenitalText2: 'У детей слабовыраженный астигматизм обоих глаз 0,25–0,5 диоптрии считается в пределах нормы. Но 0,75 диоптрии и выше с течением времени вызывают подавление бинокулярного зрения. Клетки зрительного анализатора перестают развиваться, мозг не может обрабатывать световой сигнал, и часто развивается синдром "ленивого глаза" — амблиопия и/или косоглазие.',
    adviceTitle: 'СОВЕТ!',
    adviceLine1: 'Немедленно покажите малыша врачу,',
    adviceLine2: 'если у кого-либо из родителей есть астигматизм.',
    adviceLine3: 'Защитите его от амблиопии или косоглазия.',
    seeMoreAmblyopia: 'Подробнее → Амблиопия',
    seeMoreSielme: 'Подробнее → Косоглазие',
    acquiredTitle: 'Приобретённая форма:',
    acquiredText: 'Часто проявляется как осложнение вследствие травматического или инфекционного повреждения структур глаза, при приобретении роговицей конической формы — когда развивается кератоконус. Может развиться в результате хирургического вмешательства.',
    symptomsBanner: 'СИМПТОМЫ',
    childrenTitle: 'У детей',
    childrenText: 'Дети не могут осознать, что изображение нечёткое и размытое, так как не знают, что значит хорошо видеть. Со временем ухудшение зрения вызывает у ребёнка раздражительность и капризность, что часто приписывают чертам характера. Ребёнок должен своевременно обследоваться у офтальмолога, чтобы при поступлении в школу, когда зрительная нагрузка возрастает, не произошло прогрессирования болезни.',
    childrenSymptomsSubtitle: 'Специфических симптомов нет. Обратите внимание:',
    childSymptoms: [
      'Щурит глаза при взгляде вдаль или при чтении.',
      'Наклоняет голову набок при рассматривании предметов.',
      'Жалуется на головокружение, головную боль.',
      'Избегает зрительной нагрузки.',
      'При чтении может переставлять буквы в словах.',
      'Жалуется на головную боль, особенно после зрительной нагрузки.',
    ],
    adultsTitle: 'У взрослых',
    adultSymptoms: [
      'Размытое, нечёткое зрение.',
      'Двоение.',
      'Покраснение глаз.',
      'Усталость глаз.',
      'Головная боль.',
      'Наличие "мушек" перед глазами.',
    ],
    correctionTitle: 'КОРРЕКЦИЯ АСТИГМАТИЗМА',
    correctionText1: 'При астигматизме до 18 лет лечения не существует. Широко распространена коррекция зрения с назначением специальных цилиндрических или смешанных очков и подбором различных линз. Коррекция зрения очками и линзами часто вызывает дискомфорт у пациентов в зависимости от типа и стадии астигматизма. Любые очки (линзы) лишь помогают глазу видеть лучше и не лечат его, поэтому диоптрии растут, а зрение снижается.',
    correctionText2: 'После 18–20 лет проводится лечение астигматизма изменением кривизны оптической части хирургическими/лазерными операциями, когда искусственно изменяется кривизна роговицы.',
    ownEyesBanner: 'СМОТРИТЕ СОБСТВЕННЫМИ ГЛАЗАМИ!',
    magotherapyTitle: 'МАГОТЕРАПИЯ.',
    magotherapyText1: 'Для лечения астигматизма и других рефракционных дефектов в современной практике широко применяется хирургическое/лазерное воздействие на оптическую часть глаза.',
    magotherapyText2: 'Учёные постоянно ищут и совершенствуют безопасные и эффективные методы лечения глаз. Поэтому в конце 20-го века в Московском институте микрохирургии глаза под руководством Святослава Фёдорова был разработан, внедрён и запатентован безопасный и физиологический метод лечения глаз — Маготерапия.',
    magotherapyText3: 'Подобно старому фотоаппарату, имеющему оптическую часть и плёнку, глаз также состоит из оптической части (роговица, хрусталик, стекловидное тело) и плёнки (сетчатка).',
    magotherapyText4: 'При наличии качественной оптики, если на плёнке (сетчатке) имеется хоть малейший дефект, изображение на фото выйдет размытым и нечётким.',
    magotherapyText5: 'При лечении Маготерапией мы не касаемся оптической части глаза (роговица, хрусталик). Специальная аппаратура, которую мы поочерёдно помещаем на кожу, вызывает положительные биохимические изменения в клетках сетчатки и зрительного тракта. В результате процесс преобразования светового сигнала в нервный импульс переходит в активную фазу. Это и другие факторы обеспечивают восстановление зрения за 0,002 секунды.',
    seeMoreMago: 'Подробнее → Маготерапия',
    since1996: 'С 1996 по 2025 год мы лечили более 10 000 пациентов с астигматизмом Маготерапией.',
    resultsBanner: 'РЕЗУЛЬТАТЫ МАГОТЕРАПИИ:',
    treatmentResults: [
      'На следующий день после обследования пациент замечает улучшение зрения повсюду.',
      'Чёткое, улучшенное зрение воспринимается в виде "вспышек".',
      'После десяти дней процедур продолжительность чёткого зрения увеличивается.',
      'Мозг "учится" обрабатывать нервные импульсы, очки и линзы больше не нужны.',
      'Прогрессирование болезни останавливается / замедляется.',
      'Повторный курс лечения приводит к дополнительному улучшению зрения.',
    ],
    successRateResult: 'При лечении астигматизма в 98% случаев у нас положительный результат',
    patientVideosTitle: 'ОПЫТ ПАЦИЕНТА',
    contactToday: 'Свяжитесь с нами сегодня',
    modalTitle: 'Записаться на приём к врачу',
    labelDate: 'Желаемая дата',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
  },
};

export function useAstigmatizmTranslations(language: Language) {
  return astigmatizmTranslations[language];
}
