import { Language } from '../contexts/LanguageContext';

const contactTranslations = {
  ge: {
    pageTitle: 'კონტაქტი',
    clinicName: 'კლინიკა "ახალი ტექნოლოგიები - MaGo"',
    magotherapy: 'მაგოთერაპია',
    workingHours: 'სამუშაო საათები:',
    workingTime: '12:00 - 18:00',
    exceptWeekends: 'შაბათ - კვირის გარდა',
    appointmentRequired: 'აუცილებელია წინასწარი ჩაწერა:',
    viberWhatsApp: 'Viber / WhatsApp',
    address: 'თბილისი, ანნა პოლიტკოვსკაის ქუჩა (ჯიქია) 4გ. ჯიქია რეზიდენსი. მეტრო სახელმწიფო უნივერსიტეტი',
    emailLabel: 'ელ.ფოსტა:',
    bookingTitle: 'მიღებაზე ჩასაწერად დააჭირეთ',
    bookingButton: 'ჩაწერა',
    bookingNote: 'ღილაკზე დაჭერის შემდეგ გახსნილ გვერდზე შეავსეთ ფორმა.',
    whatsAppTitle: 'WhatsApp-ზე დასაკავშირებლად დააჭირეთ',
    whatsAppButton: 'WhatsApp-ით დაკავშირება',
    leftP1: 'მაგო თერაპიით მკურნალობა 1996წლიდან 2025 წლამდე ჩაიტარა 10000 მეტმა პაციენტმა.',
    leftP2: 'დადგენილია, რომ ნებისმიერ ორგანიზმს გააჩნია გამოუყენებელი რესურსი სხვა და სხვა რაოდენობით.',
    leftP3: 'პირველივე ვიზიტზე მხოლოდ ჩვენთან არსებული მეთოდიკით ვიკვლევთ ორგანიზმის რესურს ანუ ვეუბნებით პაციენტს რამდენად მოემატება მას მხედველობა.',
    leftP4: 'მეორე გამოკვლევაზე, მაგოთერაპიით ტესტირების ჩატარებიდან ერთ საათში, პაციენტი ყველგან აღიქვამს დაპირებულმხედველობას.',
    bannerText1: 'მაგოთერაპიით მკურნალობისას, დაავადების ხანგრძლივობას, სირთულეს, ან პაციენტის ასაკს მნიშვნელობა არ აქვს!',
    bannerText2: 'მთავარია - რა რესურსი გააჩნია ორგანიზმს !',
    leftP5: 'ჩვენი მრავალწლიანი გამოცდილება, გვაძლევს საშუალებას ორგანიზმის რესურსზე დაყრდნობით შევადგინოთ ყველა პაციენტისათვის ინდივიდუალურად ადაპტირებული მკურნალობის გეგმა.',
    leftP6: 'ეს ერთ ერთი ფაქტორია, რომელიც გვაძლევს საშუალებას აღვადგინოთ მხედველობა სხვა და სხვა დაავადებების და განსაკუთრებით „ განუკურნებად" დაავადებების დროს.',
    leftP7: 'ჩვენი პაციენტების ასაკი არის ჩვილობიდან ღრმა მოხუცებულობამდე!',
    leftP8: 'მაგოთერაპიის პროცედურების დროს ხდება ორგანიზმის რელაქსაცია, შესაბამისად მკურნალობა არის უმტკივნეულო და უსაფრთხო.',
    clinicBannerTitle: '„თვალის კლინიკა ახალი ტექნოლოგიები - MaGo"',
    clinicBannerText: 'ბავშვებისთვის არის სათამაშოები რაც მკურნალობის ხარისხს საგრძნობლად აუმჯობესებს. პატარები სიამოვნებით მოდიან მაგოთერაპიით მკურნალობაზე და მხიარული განწყობით იტარებენ პროცედურებს.',
  },
  en: {
    pageTitle: 'CONTACT',
    clinicName: 'Clinic "New Technologies - MaGo"',
    magotherapy: 'Magotherapy',
    workingHours: 'Working Hours:',
    workingTime: '12:00 - 18:00',
    exceptWeekends: 'Except Saturday & Sunday',
    appointmentRequired: 'Prior appointment required:',
    viberWhatsApp: 'Viber / WhatsApp',
    address: 'Tbilisi, Anna Politkovskaya St. (Jikia) 4G. Jikia Residency. Metro: State University',
    emailLabel: 'Email:',
    bookingTitle: 'Click here to book an appointment',
    bookingButton: 'Book Now',
    bookingNote: 'Click the button to open the booking form and schedule your appointment.',
    whatsAppTitle: 'Click to contact us on WhatsApp',
    whatsAppButton: 'Contact on WhatsApp',
    leftP1: 'From 1996 to 2025, over 10,000 patients have received Mago Therapy treatment.',
    leftP2: 'It has been established that every organism has unused resources in varying amounts.',
    leftP3: 'On the first visit, using only our unique methodology, we measure the organism\'s resources — meaning we tell the patient how much their vision will improve.',
    leftP4: 'At the second examination, within one hour of Magotherapy testing, the patient perceives the promised vision improvement everywhere.',
    bannerText1: 'During Magotherapy treatment, the duration, severity, or age of the patient does not matter!',
    bannerText2: 'What matters — is what resources the organism has!',
    leftP5: 'Our many years of experience allow us to create an individually adapted treatment plan for every patient based on the organism\'s resources.',
    leftP6: 'This is one of the factors that allows us to restore vision in various diseases and especially in "incurable" diseases.',
    leftP7: 'Our patients range in age from infancy to advanced old age!',
    leftP8: 'During Magotherapy procedures, the body relaxes, therefore the treatment is painless and safe.',
    clinicBannerTitle: '"Eye Clinic New Technologies - MaGo"',
    clinicBannerText: 'There are toys for children which significantly improves the quality of treatment. Children come to Magotherapy treatment with pleasure and undergo procedures in a joyful mood.',
  },
  ru: {
    pageTitle: 'КОНТАКТ',
    clinicName: 'Клиника "Новые Технологии - MaGo"',
    magotherapy: 'Маготерапия',
    workingHours: 'Рабочие часы:',
    workingTime: '12:00 - 18:00',
    exceptWeekends: 'Кроме субботы и воскресенья',
    appointmentRequired: 'Обязательна предварительная запись:',
    viberWhatsApp: 'Viber / WhatsApp',
    address: 'Тбилиси, ул. Анны Политковской (Джикиа) 4Г. Джикиа Резиденси. Метро: Государственный Университет',
    emailLabel: 'Эл. почта:',
    bookingTitle: 'Нажмите здесь, чтобы записаться на приём',
    bookingButton: 'Записаться',
    bookingNote: 'Нажмите кнопку, чтобы открыть форму записи на приём.',
    whatsAppTitle: 'Нажмите, чтобы написать нам в WhatsApp',
    whatsAppButton: 'Написать в WhatsApp',
    leftP1: 'С 1996 по 2025 год лечение методом Маготерапии прошли более 10 000 пациентов.',
    leftP2: 'Установлено, что каждый организм обладает неиспользованными ресурсами в разном количестве.',
    leftP3: 'На первом визите, используя только нашу уникальную методику, мы исследуем ресурсы организма — то есть говорим пациенту, насколько улучшится его зрение.',
    leftP4: 'На втором обследовании, в течение одного часа после проведения тестирования Маготерапией, пациент повсюду воспринимает обещанное улучшение зрения.',
    bannerText1: 'При лечении Маготерапией длительность, тяжесть болезни или возраст пациента не имеют значения!',
    bannerText2: 'Главное — какими ресурсами обладает организм!',
    leftP5: 'Наш многолетний опыт позволяет нам составить индивидуально адаптированный план лечения для каждого пациента на основе ресурсов организма.',
    leftP6: 'Это один из факторов, который позволяет нам восстанавливать зрение при различных заболеваниях и особенно при "неизлечимых" заболеваниях.',
    leftP7: 'Возраст наших пациентов — от грудного возраста до глубокой старости!',
    leftP8: 'Во время процедур Маготерапии происходит релаксация организма, поэтому лечение является безболезненным и безопасным.',
    clinicBannerTitle: '«Глазная клиника Новые технологии - MaGo»',
    clinicBannerText: 'Для детей есть игрушки, что значительно улучшает качество лечения. Дети с удовольствием приходят на лечение Маготерапией и проходят процедуры в радостном настроении.',
  },
};

export function useContactTranslations(language: Language) {
  return contactTranslations[language];
}
