import { Language } from '../contexts/LanguageContext';

const bookingTranslations = {
  ge: {
    pageTitle: 'ექიმთან მიღებაზე ჩაწერა',
    whatsAppHeading: 'WhatsApp-ით სწრაფი კავშირი',
    whatsAppDesc: 'სწრაფი პასუხისთვის დაგვიკავშირდით WhatsApp-ზე',
    whatsAppButton: 'WhatsApp-ით დაკავშირება',
    orText: 'ან შეავსეთ ფორმა',
    formTitle: 'ჩაწერის ფორმა',
    labelName: 'სახელი გვარი',
    labelEmail: 'მეილი',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია, სირთულე',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
    submitting: 'იგზავნება...',
    successTitle: 'თქვენი განაცხადი მიღებულია!',
    successMessage: 'ჩვენ დაგიკავშირდებით მალე.',
    successWhatsApp: 'ასევე შეგიძლიათ WhatsApp-ით დაგვიკავშირდეთ',
    errorMessage: 'შეცდომა. გთხოვთ სცადოთ თავიდან.',
    backToContact: 'კონტაქტზე დაბრუნება',
  },
  en: {
    pageTitle: 'Book an Appointment',
    whatsAppHeading: 'Quick Contact via WhatsApp',
    whatsAppDesc: 'For a fast response, reach us directly on WhatsApp',
    whatsAppButton: 'Contact on WhatsApp',
    orText: 'or fill out the form below',
    formTitle: 'Appointment Request Form',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
    submitting: 'Sending...',
    successTitle: 'Booking Received!',
    successMessage: 'We will contact you shortly.',
    successWhatsApp: 'You can also reach us via WhatsApp',
    errorMessage: 'Something went wrong. Please try again.',
    backToContact: 'Back to Contact',
  },
  ru: {
    pageTitle: 'Записаться на приём',
    whatsAppHeading: 'Быстрая связь через WhatsApp',
    whatsAppDesc: 'Для быстрого ответа свяжитесь с нами напрямую через WhatsApp',
    whatsAppButton: 'Написать в WhatsApp',
    orText: 'или заполните форму ниже',
    formTitle: 'Форма записи на приём',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни или  диагноз',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
    submitting: 'Отправка...',
    successTitle: 'Заявка принята!',
    successMessage: 'Мы свяжемся с вами в ближайшее время.',
    successWhatsApp: 'Вы также можете написать нам в WhatsApp',
    errorMessage: 'Произошла ошибка. Пожалуйста, попробуйте снова.',
    backToContact: 'Вернуться к контактам',
  },
};

export function useBookingTranslations(language: Language) {
  return bookingTranslations[language];
}
