import { Language } from '../contexts/LanguageContext';

const sielmeTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    pageTitle: 'სიელმე',
    heroText1: 'დაუჯერებელია - მაგრამ ფაქტია!',
    heroText2: 'პროცედურიდან ერთ საათში,',
    heroText3: 'სიელმის გასწორება,',
    heroText4: 'მხედველობის,',
    heroText5: 'შერწყმის უნარის აღდგენა',
    heroText6: 'ქირურგიის და მედიკამენტების გარეშე',
    resultInOneHour: 'შედეგი ტესტირებიდან ერთ საათში ------- გართულების და რისკის გარეშე ---------- სტაბილური შედეგი',
    consultation: 'მიღებაზე ჩაწერა',
    contact: 'კონტაქტი',
    definitionTitle: 'სიელმე',
    definition: ' არის თვალის ისეთი დეფექტი, როდესაც პირდაპირ ხედვისას ერთი ან ორივე თვალი პერიოდულად იხრება ჰორიზონტალურად (შიგნით-გარეთ) ან ვერტიკალურად (ზემოთ ან ქვემოთ)',
    notCosmeticTitle: 'სიელმე არ არის მხოლოდ კოსმეტიკური დეფექტი, მას ახასიათებს:',
    symptom1: 'მხედველობის დაქვეითება',
    symptom2: 'გაორება',
    symptom3: 'გაზარმაცებული თვალი',
    symptom4: 'და სხვა.',
    symptom5: 'შერწყმის უნარის დარღვევა.',
    whenTitle: 'როდის ვლინდება სიელმე?',
    whenText1: 'ხშირად ბავშვებში 2-3 წლის ასაკში მოულოდნელად მაღალი სიცხის, ტრავმის ან სტრესის შემდეგ გამოვლინდეს.',
    whenText2: 'სიელმე შესაძლოა მოზრდილებში და მოხუცებულობაშიც განვითარდეს, რასაც მეორადი სიელმე ჰქვია.',
    whenText3: 'ბავშვობაში ჩამოყალიბებული სიელმე უარყოფით გავლენას ახდენს ბავშვის განვითარებაზე და ფსიქიკის ჩამოყალიბებაში. შესაძლოა შენელდეს ბავშვის ფიზიკური და გონებრივი განვითარება.',
    whenText4: 'სიელმის ხშირ გართულებად ამბლიოპია გვევლინება.',
    whenText5: 'სიელმის გამოვლინება ადრეულ ასაკში მშობლების მიერ არის შესაძლებელი.',
    dontDelay1: 'არ გადადოთ სიელმის მკურნალობა',
    dontDelay2: 'დაივიწყეთ - ცოტა გაიზარდოს !',
    earlyTreatment: 'დროულად დაწყებული მკურნალობა – პრობლემის სწრაფი აღმოფხვრის გარანტიაა.',
    earlyText: 'ადრეული მკურნალობა წარმატების საწინდარია. თუ სიელმეს დროულად არ უმკურნალებთ, თვალი, რომელიც კარგად ხედავს გახდება "წამყვანი", ხოლო მეორე თვალის მხედველობა დაქვეითთება იმდენად, რომ შესაძლოა სიბრმავეც გამოიწვიოს. ამას ამბლიოპია ანუ "ზარმაცი თვალი" ჰქვია.',
    whyTitle: 'რატომ იხრება თვალი?',
    whyText1: 'ადამიანის ნებისმიერი ორგანოს ფუნქციის გამართული მუშობა ( სმენა, მეტყველება, მხედველობა და სხვა) დამოკიდებულია ცენტრალურ ნერვულ სისტემაზე- კერძოდ თავის ტვინზე. ტვინი - ჩვენი ორგანიზმის ძირითადი კომპიუტერია, რომლის გამართული მუშაობა დამოკიდებულია იმაზე, თუ რამდენად სწორად ღებულობს და ამუშავებს ტვინი მიღებულ ინფორმაციას ნერვული იმპულსების სახით. როდესაც ადამიანი ცუდად ხედავს ერთი ან ორივე თვალიდან თავის ტვინამდე მიდის სუსტი ან ძალიან სუსტი იმპულსი. ტვინი ვერ აღიქვამს ამ იმპულს და ადამიანი ვერ ხედავს სრულყოფილ გამოსახულებას. ირღვევა შერწყმის უნარი და ქვეითთება მხედველობა.',
    whyText2: 'როდესაც ტრავმის ან დაავადების გამო, რომელიმე ჯანსაღ თვალში მხედველობა საგრძნობლად კლებულობს, დროთა განმავლობაში პრობლემური თვალი გადახრას იწყებს და ვითარდება მეორადი სიელმე.',
    withoutFunction: 'ფუნქციის გარეშე ნებისმიერი',
    organAtrophies: 'ორგანო ატროფიას განიცდის',
    lazyEyeText: 'თვალი, რომელიც ცუდად ხედავს ვერ მონაწილეობს მხედველობის პროცესში, იგი ,,ზარმაცდება" და იხრება. ამიტომაც შეარქვეს მას „ზარმაცი თვალი" ანუ ამბლიოპია.',
    fusionDamaged: 'ზიანდება შერწყმის უნარი',
    fusionText1: 'ბინოკულარული მხედველობა ანუ შერწყმის უნარი, ეს არის ორივე თვალით ერთდროულად საგნების მკვეთრი გამოსახულების დანახვის უნარი.',
    fusionText2: 'სიელმის დროს ტვინი ღებულობს მხოლოდ ერთ გამოსახულებას უკეთ მხედველი თვალიდან. ამიტომაც გამოსახულება ხდება ბრტყელი და არ სრულფასოვანი, რაც აფერხებს სამყაროს აღქმის უნარს.',
    commonTreatmentTitle: 'საყოველთაო მკურნალობა',
    commonText1: 'საყოველთაოდ, სიელმის მკურნალობისათვის ექიმები ურჩევენ ვარჯიშების ჩატარებას, უნიშნავენ სათვალეს, თვალის ახვევას ან სთავაზობენ ქირურგიულ ოპერაციას.',
    commonText2: 'ცნობილი ფაქტია, რომ ქირურგიული ოპერაცია მიზნად არ ისახავს მხედველობის და შერწყმის უნარის აღდგენას. ქირურგიული ოპერაციები მიმართულია მხოლოდ კოსმეტიკური დეფექტის შესასწორებლად, რას თვალის კუნთზე გარკვეული მანიპულაციებით ხდება. სამწუხაროთ, დროთა განმავლობაში თვალი, რომელიც კვლავ ვერ ხედავს , ვერ მონაწილეობს მხედველობის პროცესში და მრავალჯერადი ოპერაციების შემდეგ ოპერირებული თვალი კვლავ მეტ ნაკლებად იწყებს გადახრას!',
    commonText3: 'არსებული ვარჯიშები, სათვალეები , თვალის ახვევა და სხვა , რომელიც სიელმის სამკურნალოდ 200 წელზე მეტია გამოიყენება გარდა იმისა, რომ რთულად შესასრულებელია მცირეწლოვან ბავშვებში, სამწუხაროთ ნაკლებად ეფექტურია ან დროებითი ეფექტი აქვს.',
    medicineEvolvesTitle1: 'შეცდომაა !',
    medicineEvolvesTitle2: ' სიელმის განკურნება ზრდასრულ ასაკში შეუძლებელია.',
    medicineEvolvesText1: 'მედიცინა როგორც სხვა დარგები ვითარდება,',
    medicineEvolvesText2: 'რომ მისი განკურნება შეუძლებელია.',
    medicineEvolvesText3: 'მაგრამ ეს ასე არ არის.',
    magotherapy: 'მაგოთერაპია.',
    since1996: '1996 წლიდან   2025 წლამდე  მაგოთერაპიით მკურნალობისას   2500 მეტ პაციენტს  გაუსწორდა სიელმე და  აღუდგა მხედველობა.',
    stableResult: 'მიღებული  შედეგი სტაბილურია 20  წელზე მეტი.',
    howWeCorrectTitle: 'როგორ ვასწორებთ სიელმეს?',
    howText1: 'მაგოთერაპიის უსაფრთხო და უვნებელ პროცედურებს ჩვენი თანამშრომლები თამაშის ფორმით ატარებენ, რაც უფრო საინტერესო და სახალისოს ხდის ბავშვებისათვის მკურნალობის პროცესს.',
    howText2: 'ჩვენი მრავალწლიანი გამოცდილება გვაძლევს საშუალებას, ყველა პაციენტს საკმაოდ ზუსტად შევუდგინოთ ინდივიდუალური მკურნალობის გეგმა, რომელიც გვეხმარება მივიღოთ მაქსიმალური შედეგი, ადაპტირებული კონკრეტული ადამიანის ორგანიზმის რესურსის ასაღორძინებლად.',
    howText3: 'მაგოთერაპიისთვის სპეციალურად შექმნილი აპარატურა, რომელსაც კანის ზემოდან რიგრიგობით ვათავსებთ, იწვევს პოზიტიურ ცვლილებებს, რომლებიც გამოიხატება შემდეგში:',
    positiveChanges: [
      'უმჯობესდება უჯრედების ნივთიერებათა ცვლა.',
      'უმჯობესდება ცერებრალური სისხლისმიმოქცევა.',
      'ხდება უჯრედ შიდა სტრუქტურულ-ფუნქციონალური პარამეტრების გააქტიურება.',
      'აქტიურდება რეცეპტორების ფუნქცია და ნეირო იმპლუსის გადაცემის სიჩქარე.',
      'ბადურაზე არსებული უჯრედები გამოდიან პარბიოტული მდგომარეობიდან.',
      'თავის ტვინის მხედველობის ზონა აქტიურდება.',
      'ბადურის განგლიოზურ უჯრედებში უმჯობესდება ნეიროტრანსმისია.',
      'ტვინი უკვე აღიქვამს ნერვულ იმპულსს და სრულყოფილ გამოსახულებას უბრუნებს თვალს.',
      'იზრდება ნეირონების მემბრანის პლასტიურობა.',
    ],
    positiveChangesText: 'არსებული პოზიტიური ძვრები აუმჯობესებს ვიზომეტრიულ ეფექტს, რაც ამცირებს პაციენტის ფუნქციონალური რეაბილიტაციის პერიოდს და განსაზღვრავს მიღებული შედეგის სტაბილიზაციას რამდენიმე ათეული წლების მანძილზე.',
    resultsTitle: 'შედეგი ტესტირებიდან 1 საათში:',
    results: [
      'ნივთირებათა ცვლის აღდგენის  შემდეგ , ტვინი სწორად ამუშავებს იმპულსს და უბრუნებს  თვალს სწორ  გამოსახულებას',
      'მატულობს ცენტრალური მხედველობა.',
      'თვალი ავტომატურად ღებულობს სიმეტრიულ დგომას',
      'შედეგი სტაბილურია 20 წელზე მეტი.',
      'ხდება შერწყმის უნარის ნაწილობრივი ან მთლიანი აღდგენა.',
      'გადახრის კუთხე საგრძნობლად კლებულობს ან ქრება.',
    ],
    resultsText: 'მომატებული მხედველობა და შერწყმის უნარის აღდგენა - ეს ორი ძალიან მნიშვნელოვანი ფაქტორია, რომელიც ავტომატურად უზრუნველყოფს თვალის სიმეტრიულ დგომას და სიელმის კუთხის შემცირებას ან გაქრობას მრავალჯერადად ოპერირებულ თვალზედაც, მიუხედავად პაციენტის ასაკისა.',
    adviceTitle: 'რჩევები მშობლებს:',
    adviceText1: 'ჩვილს სამ თვემდე არ შეუძლია კოორდინებულად ორივე თვალით ყურება.',
    adviceText2: '4-5 თვიდან შეგიძლიათ მარტივი მხედველობის ტესტის ჩატარება. დაანახეთ პატარას სათამაშო, რომელზედაც იგი მზერას ორივე თვალით დააფიქსირებს. დაუფარეთ პატარას ერთი თვალი და აამოძრავეთ სათამაშო. დააკვირდით აყოლებს თუ არა პატარა ამ სათამაშოს თვალს. თუ მისი მზერა სათამაშოს მიმართულებით მოძრაობს - მაშინ ყველაფერი რიგზეა. თუ პატარა ცდილობს მოაცილოს თქვენი ხელი მის თვალს, გასაგებია, რომ იმ თვალით პატარა ცუდად ხედავს.',
    noticeText1: 'თუ ატყობთ, რომ პატარას პერიოდულად ან გამუდმებით აღენიშნება თვალის/თვალების არა სიმეტრიული დგომა, აუცილებლად მიმართეთ ექიმს.',
    noticeText2: 'სიელმე 25 ტიპის არსებობს და მისი კვალიფიციური გამოვლენა და მკურნალობა, მხოლოდ ექიმ ოფთალმოლოგს შეუძლია.',
    noticeText3: 'ყურადღებით შეარჩიეთ თვალის ექიმი, თქვენ ერთად უნდა დაეხმაროთ პატარას.',
    earlyDetection: 'სიელმის გამოვლინება ადრეულ ასაკში მშობლების მიერ არის შესაძლებელი',
    patientVideosTitle: 'პაციენტების გამოცდილება',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    pageTitle: 'Strabismus',
    heroText1: 'Unbelievable but true!',
    heroText2: 'Within one hour of the procedure,',
    heroText3: 'correction of strabismus,',
    heroText4: 'vision,',
    heroText5: 'and fusion ability restored',
    heroText6: 'Without surgery or medication',
    resultInOneHour: 'Results within 1 hour of testing — no complications, no risk — stable results',
    consultation: 'Book Appointment',
    contact: 'Contact',
    definitionTitle: 'Strabismus',
    definition: 'Strabismus is an eye defect where, during direct gaze, one or both eyes periodically deviate horizontally (inward or outward) or vertically (upward or downward)',
    notCosmeticTitle: 'Strabismus is not just a cosmetic defect, it is characterized by:',
    symptom1: 'Reduced vision',
    symptom2: 'Double vision',
    symptom3: 'Lazy eye',
    symptom4: 'and others.',
    symptom5: 'Impaired fusion ability.',
    whenTitle: 'When does strabismus appear?',
    whenText1: 'Often in children aged 2-3, it can suddenly appear after high fever, trauma or stress.',
    whenText2: 'Strabismus can also develop in adults and the elderly, which is called secondary strabismus.',
    whenText3: 'Strabismus that develops in childhood has a negative impact on the child\'s development and psyche. Physical and mental development may slow down.',
    whenText4: 'Amblyopia is a frequent complication of strabismus.',
    whenText5: 'Detection of strabismus at an early age by parents is possible.',
    dontDelay1: 'Do not postpone strabismus treatment',
    dontDelay2: 'Forget "let them grow up a little"',
    earlyTreatment: 'Early treatment is the guarantee of rapid problem resolution.',
    earlyText: 'Early treatment is the key to success. If strabismus is not treated in time, the eye that sees well will become the "leading" one, while the vision in the other eye will deteriorate to the point of possible blindness. This is called amblyopia or "lazy eye".',
    whyTitle: 'Why does the eye deviate?',
    whyText1: 'The proper functioning of any human organ (hearing, speech, vision, etc.) depends on the central nervous system — specifically the brain. The brain is the main computer of our body, whose proper functioning depends on how correctly it receives and processes incoming information in the form of nerve impulses. When a person sees poorly from one or both eyes, a weak or very weak impulse reaches the brain. The brain cannot perceive this impulse and the person cannot see a complete image. Fusion ability is disrupted and vision decreases.',
    whyText2: 'When vision in a healthy eye decreases significantly due to trauma or disease, over time the problematic eye begins to deviate and secondary strabismus develops.',
    withoutFunction: 'Without function, any',
    organAtrophies: 'organ undergoes atrophy',
    lazyEyeText: 'An eye that sees poorly cannot participate in the vision process, it "becomes lazy" and deviates. This is why it is called a "lazy eye" or amblyopia.',
    fusionDamaged: 'Fusion ability is impaired',
    fusionText1: 'Binocular vision or fusion ability is the ability to see sharp images of objects simultaneously with both eyes.',
    fusionText2: 'In strabismus, the brain receives only one image from the better-seeing eye. Therefore, the image becomes flat and incomplete, hindering the ability to perceive the world.',
    commonTreatmentTitle: 'Common Treatments',
    commonText1: 'Generally, for strabismus treatment, doctors recommend exercises, prescribe glasses, patching, or offer surgical operations.',
    commonText2: 'It is a well-known fact that surgical operations do not aim to restore vision and fusion ability. Surgical operations are aimed only at correcting the cosmetic defect through certain manipulations on the eye muscle. Unfortunately, over time, the eye that still cannot see cannot participate in the vision process, and after multiple operations, the operated eye begins to deviate again to varying degrees!',
    commonText3: 'Existing exercises, glasses, patching and others, which have been used for strabismus treatment for over 200 years, are unfortunately not very effective or have only a temporary effect, besides being difficult to perform in young children.',
    medicineEvolvesTitle1: 'Medicine, just like',
    medicineEvolvesTitle2: 'other scientific fields, is evolving.',
    medicineEvolvesText1: 'Strabismus is a serious disease and many believe',
    medicineEvolvesText2: 'that its cure is impossible.',
    medicineEvolvesText3: 'But this is not the case.',
    magotherapy: 'Magotherapy.',
    since1996: 'From 1996 to 2025, we have successfully improved vision and corrected strabismus in over 2,000 patients.',
    stableResult: 'Results are stable for over 20 years.',
    howWeCorrectTitle: 'How do we correct strabismus?',
    howText1: 'Our staff conducts Magotherapy\'s safe and harmless procedures in a playful manner, making the treatment process more interesting and fun for children.',
    howText2: 'Our many years of experience allow us to create a fairly accurate individual treatment plan for each patient, which helps us achieve maximum results, adapted to revive the resources of a specific person\'s body.',
    howText3: 'The specially designed apparatus for Magotherapy, which we place alternately on the skin, causes positive changes expressed as follows:',
    positiveChanges: [
      'Cellular metabolism improves.',
      'Cerebral blood circulation improves.',
      'Intracellular structural-functional parameters are activated.',
      'Receptor function and nerve impulse transmission speed are activated.',
      'Cells on the retina exit parabiotical state.',
      'The visual zone of the brain is activated.',
      'Neurotransmission improves in the ganglion cells of the retina.',
      'The brain now perceives the nerve impulse and returns a complete image to the eye.',
      'The plasticity of neuron membranes increases.',
    ],
    positiveChangesText: 'The existing positive shifts improve the visometric effect, which reduces the period of functional rehabilitation of the patient and determines the stabilization of the obtained result for several decades.',
    resultsTitle: 'As a result, within 1 hour of testing:',
    results: [
      'After metabolic restoration, the brain correctly processes the impulse and returns the correct image to the eye',
      'Central vision increases.',
      'The eye automatically assumes a symmetrical position',
      'Results are stable for over 20 years.',
      'Partial or complete restoration of fusion ability occurs.',
      'The deviation angle decreases significantly or disappears.',
    ],
    resultsText: 'Improved vision and restoration of fusion ability — these are two very important factors that automatically ensure the symmetrical position of the eye and the reduction or disappearance of the strabismus angle even in repeatedly operated eyes, regardless of the patient\'s age.',
    adviceTitle: 'Advice for Parents:',
    adviceText1: 'Infants under three months cannot coordinate looking with both eyes.',
    adviceText2: 'From 4-5 months, you can perform a simple vision test. Show the baby a toy which they will fix their gaze on with both eyes. Cover one of the baby\'s eyes and move the toy. Observe whether the baby follows the toy with their eye. If their gaze moves in the direction of the toy — everything is fine. If the baby tries to remove your hand from their eye, it means that the baby sees poorly with that eye.',
    noticeText1: 'If you notice that the baby periodically or constantly has asymmetrical eye position, be sure to see a doctor.',
    noticeText2: 'There are 25 types of strabismus, and only an ophthalmologist can qualify and treat it.',
    noticeText3: 'Choose your eye doctor carefully, you need to work together to help the baby.',
    earlyDetection: 'Detection of strabismus at an early age by parents is possible',
    patientVideosTitle: 'PATIENT EXPERIENCE',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    pageTitle: 'Косоглазие',
    heroText1: 'Невероятно, но факт!',
    heroText2: 'Через один час после процедуры,',
    heroText3: 'исправление косоглазия,',
    heroText4: 'восстановление зрения,',
    heroText5: 'и способности к слиянию',
    heroText6: 'Без хирургии и медикаментов',
    resultInOneHour: 'Результат через 1 час тестирования — без осложнений и риска — стабильный результат',
    consultation: 'Записаться на приём',
    contact: 'Контакт',
    definitionTitle: 'Косоглазие',
    definition: 'Косоглазие — это такой дефект глаза, когда при прямом взгляде один или оба глаза периодически отклоняются горизонтально (внутрь-наружу) или вертикально (вверх или вниз)',
    notCosmeticTitle: 'Косоглазие — не только косметический дефект, для него характерны:',
    symptom1: 'Снижение зрения',
    symptom2: 'Двоение',
    symptom3: 'Ленивый глаз',
    symptom4: 'и другие.',
    symptom5: 'Нарушение способности к слиянию.',
    whenTitle: 'Когда проявляется косоглазие?',
    whenText1: 'Часто у детей 2-3 лет может неожиданно появиться после высокой температуры, травмы или стресса.',
    whenText2: 'Косоглазие может развиться и у взрослых, и у пожилых людей, что называется вторичным косоглазием.',
    whenText3: 'Косоглазие, сформировавшееся в детстве, оказывает негативное влияние на развитие ребёнка и формирование психики. Возможно замедление физического и умственного развития ребёнка.',
    whenText4: 'Частым осложнением косоглазия является амблиопия.',
    whenText5: 'Выявление косоглазия в раннем возрасте родителями возможно.',
    dontDelay1: 'Не откладывайте лечение косоглазия',
    dontDelay2: 'Забудьте о "пусть немного подрастёт"',
    earlyTreatment: 'Своевременно начатое лечение — гарантия быстрого устранения проблемы.',
    earlyText: 'Раннее лечение — залог успеха. Если косоглазие не лечить вовремя, глаз, который видит хорошо, станет "ведущим", а зрение другого глаза ухудшится настолько, что возможна даже слепота. Это называется амблиопией или "ленивым глазом".',
    whyTitle: 'Почему глаз отклоняется?',
    whyText1: 'Нормальная работа любого органа человека (слух, речь, зрение и др.) зависит от центральной нервной системы — конкретно от головного мозга. Мозг — главный компьютер нашего организма, нормальная работа которого зависит от того, насколько правильно он принимает и обрабатывает поступающую информацию в виде нервных импульсов. Когда человек плохо видит одним или обоими глазами, до головного мозга доходит слабый или очень слабый импульс. Мозг не воспринимает этот импульс, и человек не видит полноценного изображения. Нарушается способность к слиянию и снижается зрение.',
    whyText2: 'Когда из-за травмы или болезни зрение в здоровом глазу значительно снижается, со временем проблемный глаз начинает отклоняться и развивается вторичное косоглазие.',
    withoutFunction: 'Без функции любой',
    organAtrophies: 'орган атрофируется',
    lazyEyeText: 'Глаз, который плохо видит, не может участвовать в зрительном процессе, он "ленится" и отклоняется. Поэтому его и называют "ленивым глазом" или амблиопией.',
    fusionDamaged: 'Нарушается способность к слиянию',
    fusionText1: 'Бинокулярное зрение, или способность к слиянию, — это способность одновременно видеть чёткое изображение предметов обоими глазами.',
    fusionText2: 'При косоглазии мозг получает только одно изображение от лучше видящего глаза. Поэтому изображение становится плоским и неполноценным, что препятствует восприятию мира.',
    commonTreatmentTitle: 'Общепринятое лечение',
    commonText1: 'Как правило, для лечения косоглазия врачи рекомендуют упражнения, назначают очки, окклюзию или предлагают хирургическую операцию.',
    commonText2: 'Общеизвестный факт, что хирургическая операция не ставит целью восстановление зрения и способности к слиянию. Хирургические операции направлены только на исправление косметического дефекта путём определённых манипуляций с мышцами глаза. К сожалению, со временем глаз, который по-прежнему плохо видит, не может участвовать в зрительном процессе, и после многократных операций оперированный глаз снова начинает отклоняться!',
    commonText3: 'Существующие упражнения, очки, окклюзия и прочее, применяемые для лечения косоглазия более 200 лет, кроме того что сложно выполнимы у маленьких детей, к сожалению, малоэффективны или дают лишь временный эффект.',
    medicineEvolvesTitle1: 'Медицина, как и',
    medicineEvolvesTitle2: 'другие научные дисциплины, развивается.',
    medicineEvolvesText1: 'Косоглазие — серьёзное заболевание, и многие считают,',
    medicineEvolvesText2: 'что его излечение невозможно.',
    medicineEvolvesText3: 'Но это не так.',
    magotherapy: 'Маготерапия.',
    since1996: 'С 1996 по 2025 год мы успешно улучшили зрение и исправили косоглазие более чем 2000 пациентам.',
    stableResult: 'Результат стабилен более 20 лет.',
    howWeCorrectTitle: 'Как мы исправляем косоглазие?',
    howText1: 'Наши сотрудники проводят безопасные и безвредные процедуры Маготерапии в игровой форме, что делает процесс лечения более интересным и увлекательным для детей.',
    howText2: 'Многолетний опыт позволяет нам составить достаточно точный индивидуальный план лечения для каждого пациента, что помогает нам добиться максимального результата, адаптированного к восстановлению ресурсов конкретного организма.',
    howText3: 'Специально созданная для Маготерапии аппаратура, которую мы поочерёдно помещаем на кожу, вызывает положительные изменения, выражающиеся в следующем:',
    positiveChanges: [
      'Улучшается клеточный метаболизм.',
      'Улучшается церебральное кровообращение.',
      'Активируются внутриклеточные структурно-функциональные параметры.',
      'Активируется функция рецепторов и скорость передачи нервного импульса.',
      'Клетки сетчатки выходят из парабиотического состояния.',
      'Активируется зрительная зона головного мозга.',
      'В ганглиозных клетках сетчатки улучшается нейротрансмиссия.',
      'Мозг теперь воспринимает нервный импульс и возвращает глазу полноценное изображение.',
      'Увеличивается пластичность мембран нейронов.',
    ],
    positiveChangesText: 'Существующие положительные сдвиги улучшают визометрический эффект, что сокращает период функциональной реабилитации пациента и определяет стабилизацию полученного результата на несколько десятилетий.',
    resultsTitle: 'В результате, через 1 час тестирования:',
    results: [
      'После восстановления обмена веществ мозг правильно обрабатывает импульс и возвращает глазу правильное изображение',
      'Увеличивается центральное зрение.',
      'Глаз автоматически принимает симметричное положение',
      'Результат стабилен более 20 лет.',
      'Происходит частичное или полное восстановление способности к слиянию.',
      'Угол отклонения значительно уменьшается или исчезает.',
    ],
    resultsText: 'Улучшенное зрение и восстановление способности к слиянию — два очень важных фактора, которые автоматически обеспечивают симметричное положение глаза и уменьшение или исчезновение угла косоглазия даже у многократно оперированного глаза, независимо от возраста пациента.',
    adviceTitle: 'Советы родителям:',
    adviceText1: 'Младенцы до трёх месяцев не могут координированно смотреть обоими глазами.',
    adviceText2: 'С 4-5 месяцев можно провести простой тест зрения. Покажите малышу игрушку, на которой он зафиксирует взгляд обоими глазами. Закройте один глаз малышу и подвигайте игрушку. Понаблюдайте, следит ли малыш за игрушкой глазом. Если взгляд движется в направлении игрушки — всё в порядке. Если малыш пытается убрать вашу руку с глаза — значит, этим глазом он видит плохо.',
    noticeText1: 'Если вы замечаете, что у малыша периодически или постоянно наблюдается несимметричное положение глаза/глаз, обязательно обратитесь к врачу.',
    noticeText2: 'Существует 25 типов косоглазия, и только врач-офтальмолог может квалифицированно его выявить и лечить.',
    noticeText3: 'Тщательно выбирайте глазного врача, вы должны совместно помочь малышу.',
    earlyDetection: 'Выявление косоглазия в раннем возрасте родителями возможно',
    patientVideosTitle: 'ОПЫТ ПАЦИЕНТА',
  },
};

export function useSielmeTranslations(language: Language) {
  return sielmeTranslations[language];
}
