import { Language } from '../contexts/LanguageContext';

const glaukomaTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    pageTitle: 'გლაუკომა',
    heroHeader: 'გლაუკომის პროგრესირების შეჩერება ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ჩვენთვის რეალობაა !',
    heroText1: 'აპარატურული პერსონიფიცირებული მკურნალობა',
    heroText2: 'აღადგენს პერიფერიულ და ცენტრალურ მხედველობას',
    heroText3: 'ეფექტური და უსაფრთხო მკურნალობა მაგოთერაპიით',
    heroText4: 'ჩვენთან — რეალობაა!',
    resultInOneHour: 'მკურნალობა გართულების, ტკივილის  გარეშე -------- 20  წლიანი სტაბილური შედეგები-------------დაავადების პროგრესირების შეჩერება',
    consultation: 'მიღებაზე ჩაწერა',
    contact: 'კონტაქტი',
    definitionTitle: 'გლაუკომა',
    definition1: 'თვალის ვერაგ დაავადებათა ჯგუფს მიეკუთვნება. საწყის სტადიაზე ვიწროვდება  მხოლოდ  პერიფერიული( გვერდითი) მხედველობა, მაშინ როდესაც  შორს მხედველობა  რჩება ნორმის ფარგლებში  რაც  ხშირად  შეუმჩნეველია ამ დაავადების დროს ხდება მხედველობის ნერვის პროგრესირებადი ატროფია და მხედველობის დაკარგვა. მხედველობის ნერვის მეშვეობით ხდება ვიზუალური ინფორმაციის გადაცემა თვალიდან ტვინში.დაგვიანებული მკურნალობა ხშირად სიბრმავით მთავრდება',
    definition2a: 'გავრცელებული აზრი, რომ თვალშიდა წნევის მოწესრიგება დაავადების პროგრესირებას აჩერებს — არასწორია.',
    definition2b: 'არსებული მკურნალობის მეთოდები — წვეთები, ქირურგიული ოპერაცია და ლაზერული მკურნალობა — მიმართულია მხოლოდ თვალშიდა წნევის მოსაწესრიგებლად.',
    definition3: 'მაგრამ ნორმალური და დაბალი თვალშიდა წნევის დროსაც ხდება მხედველობის ნერვის და თავის ტვინის შესაბამისი ნაწილების ატროფიის პროგრესირება, რაც ხშირად სიბრმავით მთავრდება.',
    magoBannerText: 'მაგოთერაპიით მკურნალობისას 88% შემთხვევაში ხდება მხედველობის აღდგენა გლაუკომის საწყის სტადიაზე გამოვლინება შესაძლებელია მხოლოდ პროფესიანალ ექიმის მიერ',
    whyVisionDecreaseTitle: 'რატომ კლებულობს მხედველობა გლაუკომის დროს?',
    whyText1: 'თვალი  არის  ტვინის ნაწილი, რომელიც  გამოტანილია  თავის ქალიდან  და შემოფარგლულია , თვალბუდის  ძვლოვანი კარკასით, რომელსაც ორბიტა ჰქვია, გლაუკომა ნეიროდეგენერაციული დაავადებაა.',
    whyText2: 'მხედველობის ნერვი შედგება 1,2 მილიონი ნერვული ბოჭკოსაგან, გლაუკომის დროს ხდება ამ ნერვული ბოჭკოების პროგრესირებადი ატროფია. პათოლოგიური პროცესი იწყება პერიფერიული ბოჭკოებიდან, ამიტომ პირველი სიმპტომი არის მხედველობის ველის შევიწროვება — „გვირაბული" ანუ „ტუნელური" მხედველობა.',
    whyText3: 'პროცესის პროგრესირება   იწვევს  პერიფერიული მხედველობის   შევიწროვებას, პარალელურად  კლებულობს   ცენტრალური მხედველობა , რომელიც ხშირად სიბრმავით მთავრდება.',
    whyText4: 'არსებული მკურნალობის  მეთოდები ატროფიულ პროცესებს ვერ აჩერებს-რადგან წვეთები  და სხვა და   სხვა ტიპის  ქირურგიული ჩარევები  მხოლოდ  წნევის მოწესრიგებაზე  არიან ორიენტირებული და  არ ისახავენ   მიზნად მხედველობის აღდგენას.',
    whenDevelopsTitle: 'როდის ვითარდება გლაუკომა?',
    whenText: 'გლაუკომა შეიძლება განვითარდეს ნებისმიერ ასაკში, თუმცა ყველაზე ხშირად 40 წლის შემდეგ. რისკ-ფაქტორებს მიეკუთვნება:',
    riskFactors: [
      'მომატებული თვალშიდა წნევა',
      'გლაუკომა ოჯახის სხვა წევრებში',
      'შაქრიანი დიაბეტი',
      'მომატებული არტერიული წნევა',
      'მიოპია (ახლომხედველობა)',
      'თვალის ტრავმა ან ანთება',
      'სტეროიდული მედიკამენტების გამოყენება',
    ],
    riskGroupsTitle: 'გლაუკომის რისკ ჯგუფები',
    riskGroupsText1: 'განსაკუთრებულ ყურადღებას საჭიროებენ ის ადამიანები, რომლებსაც ოჯახში ჰყავთ გლაუკომით დაავადებული ახლო ნათესავი. გენეტიკური მიდრეკილება მნიშვნელოვნად ზრდის დაავადების განვითარების ალბათობას.',
    riskGroupsText2: '40 წლის მერე სავალდებულოა  ექიმთნ   შეამოწმოთ  თვალშიდა  წნევა,  მხედველობის ველი და  თვალის ფსკერი.   ეს  სამი გამოკვლევა მოგცემთ  სრულყოფილ ინფორმაციას  გაქვთ  თუ არა  გლაუკომა.',
    riskGroupsText3: 'გახსოვდეთ: გლაუკომის ადრეულ სტადიაზე პაციენტს ხშირად საერთოდ არ აქვს სიმპტომები.  მისი  გამოვლინება მხოლოდ  პროფესიონალ  ექიმს შეუძლია !  გლაუკომას ხშირად „მხედველობის ჩუმ   მკვლელს “ ეძახიან.',
    symptomsTitle: 'გლაუკომის სიმპტომები',
    symptoms: [
      'მხედველობის ველის შევიწროვება (გვირაბული მხედველობა).',
      'ნისლი თვალის წინ.',
      'ნათურის გარშემო ცისარტყელას  მსგავსი წრეები.',
      'მხედველობის სიმახვილის დაქვეითება.',
      'ხშირი თავის ტკივილი, თვალების ტკივილი.',
      'მომატებული მგრძნობელობა შუქის მიმართ.',
    ],
    twoFormsTitle: 'გლაუკომის ორი ძირითადი ფორმა',
    openAngleTitle: '1. ღია კუთხიანი გლაუკომა',
    openAngleText: 'ყველაზე გავრცელებული ფორმა. მიმდინარეობს უსიმპტომოდ, ნელა და თანდათანობით. პაციენტი ხშირად ვერ ამჩნევს მხედველობის ველის შევიწროვებას გვიან სტადიამდე.',
    closedAngleTitle: '2. დახურულ კუთხიანი გლაუკომა',
    closedAngleText: 'ნაკლებად გავრცელებული, მაგრამ მწვავე შეტევა შესაძლებელია — მკვეთრი ტკივილი, გულისრევა, მხედველობის მოულოდნელი დაქვეითება. ესაჭიროება სასწრაფო სამედიცინო დახმარება საჭიროებს.',
    magotherapyTreatmentTitle: 'მაგოთერაპიით მკურნალობა.',
    magotherapyText: 'მაგოთერაპიით გლაუკომის მკურნალობისას, ჩვენი მიზანია გავაჩეროთ ან შევანელოთ მხედველობის ნერვის ატროფიის პროგრესირება, აღვადგინოთ მხედველობა და შევამციროთ არსებული სიმპტომები ორგანიზმის საკუთარი რესურსის გააქტიურებით.',
    treatWithUs: 'ჩვენ ვმკურნალობთ პაციენტს და არა დაავადებას!',
    treatmentPrognosis: 'მაგოთერაპიით მკურნალობისას, გამოკვლევების საფუძველზე ვიკვლევთ კონკრეტული ორგანიზმის რესურს და პირველივე ვიზიტისას 97% სიზუსტით ვაძლევთ პროგნოზს, თუ რამდენად მოემატება კონკრეტულ ადამიანს მხედველობა მკურნალობის შემდეგ.',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    successRateText: 'მაგოთერაპიით მკურნალობისას, 88% შემთხვევაში ხდება',
    successRateText2: 'მხედველობის აღდგენა და დაავადების პროგრესირების შეჩერება',
    successRateText3: 'ქირურგიისა და მედიკამენტების გარეშე.',
    resultsTitle: 'მაგოთერაპიის შედეგები:',
    results: [
      { title: '1. ფართოვდება მხედველობის ველი.', text: 'პაციენტს ეწყება პერიფერიული ხედვის გაუმჯობესებას. „გვირაბული" მხედველობა ნელ-ნელა ფართოვდება.' },
      { title: '3. ნელდება ნერვის ატროფიის პროცესი.', text: 'მხედველობის ნერვის ბოჭკოების შემდგომი დაზიანება მცირდება ან ჩერდება.' },
      { title: '5. სტაბილიზდება თვალშიდა წნევა.', text: 'ნორმალიზდება სითხის ცირკულაცია, უმჯობესდება ტროფიკა.' },
      { title: '2. მატულობს ცენტრალური მხედველობა.', text: 'მკურნალობის კურსის ჩატარებისას უფრო მეტი უჯრედი იწყებს ფუნქციონირებას და მხედველობა კვლავ მატულობს.' },
      { title: '4. ქრება ტკივილი და დისკომფორტი.', text: 'მცირდება ნისლი თვალის წინ თავის, თვალების ტკივილი და დისკომფორტი.' },
      { title: '6. უმჯობესდება ცხოვრების ხარისხი.', text: 'პაციენტი თავისუფლად გადაადგილდება, უადვილდება ყოველდღიური საქმიანობა.' },
    ],
    warningTitle: 'ყურადღება',
    warningText: 'დაბალი თვალ შიდა წნევა არ აჩერებს დაავადების პროგრესირებას და არ გიცავთ სიბრმავისგან.',
    patientVideosTitle: 'პაციენტების გამოცდილება',
    moreVideosYoutube: 'სხვა ვიდეოები YouTube-ზე →',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    pageTitle: 'Glaucoma',
    heroHeader: 'Stopping / Slowing Disease Progression',
    heroText1: 'Magotherapy will help you restore vision',
    heroText2: 'at the expense of reviving your body\'s resources.',
    heroText3: 'Effective and safe treatment with Magotherapy',
    heroText4: 'is a reality at our clinic!',
    resultInOneHour: 'Treatment without complications or pain -------- 20 years of stable results -------------stopping disease progression',
    consultation: 'Consultation',
    contact: 'Contact',
    definitionTitle: 'Glaucoma',
    definition1: 'Belongs to the group of treacherous eye diseases. This disease involves progressive atrophy of the optic nerve and loss of vision. The optic nerve transmits visual information from the eye to the brain.',
    definition2a: 'The common belief that normalizing intraocular pressure stops disease progression is incorrect.',
    definition2b: 'Existing treatment methods — drops, surgical operations, and laser treatment — are aimed only at normalizing intraocular pressure.',
    definition3: 'But even with normal and low intraocular pressure, progressive atrophy of the optic nerve and corresponding brain areas continues, often ending in blindness.',
    magoBannerText: 'With magotherapy treatment, in 88% of cases vision is restored. In the early stage of glaucoma, it can only be detected by a professional doctor',
    whyVisionDecreaseTitle: 'Why does vision decrease with glaucoma?',
    whyText1: 'The optic nerve consists of 1.2 million nerve fibers, through which visual information is transmitted from the retina to the corresponding brain areas.',
    whyText2: 'In glaucoma, progressive atrophy of these nerve fibers occurs. The pathological process starts from peripheral fibers, so the first symptom is narrowing of the visual field — "tunnel vision".',
    whyText3: 'The process progresses and central vision narrows, often ending in blindness.',
    whyText4: 'Modern medicine cannot stop this atrophic process — existing treatment methods are only focused on pressure reduction.',
    whenDevelopsTitle: 'When does glaucoma develop?',
    whenText: 'Glaucoma can develop at any age, but most often after the age of 40. Risk factors include:',
    riskFactors: [
      'Elevated intraocular pressure',
      'Glaucoma in other family members',
      'Diabetes mellitus',
      'High blood pressure',
      'Myopia (nearsightedness)',
      'Eye trauma or inflammation',
      'Use of steroid medications',
    ],
    riskGroupsTitle: 'Glaucoma risk groups',
    riskGroupsText1: 'Particular attention is needed for people who have close relatives with glaucoma. Genetic predisposition significantly increases the likelihood of developing the disease.',
    riskGroupsText2: 'After the age of 40, everyone is advised to have a preventive examination with an ophthalmologist once a year — measuring intraocular pressure alone is not sufficient, visual field testing is required.',
    riskGroupsText3: 'Remember: at an early stage of glaucoma, patients often have no symptoms at all — it is the so-called "silent thief of vision".',
    symptomsTitle: 'GLAUCOMA SYMPTOMS',
    symptoms: [
      'Narrowing of the visual field (tunnel vision).',
      'Foggy vision.',
      'Rainbow circles around lamps.',
      'Decreased visual acuity.',
      'Frequent headaches, eye pain.',
      'Increased sensitivity to light.',
    ],
    twoFormsTitle: 'Two main forms of glaucoma',
    openAngleTitle: '1. Open-angle glaucoma',
    openAngleText: 'The most common form. It progresses asymptomatically, slowly and gradually. Patients often do not notice the narrowing of the visual field until a late stage.',
    closedAngleTitle: '2. Closed-angle glaucoma',
    closedAngleText: 'Less common, but an acute attack is possible — sharp pain, nausea, sudden vision loss. Requires emergency medical care.',
    magotherapyTreatmentTitle: 'Magotherapy Treatment.',
    magotherapyText: 'During Magotherapy treatment for glaucoma, our goal is to stop or slow the progression of optic nerve atrophy, restore vision, and reduce existing symptoms by activating the body\'s own resources.',
    treatWithUs: 'We treat the patient, not just the disease!',
    treatmentPrognosis: 'During Magotherapy treatment, based on examinations, we study each organism\'s resources and at the very first visit provide a 97% accurate prognosis of how much vision improvement can be expected after treatment.',
    seeMoreMago: 'See more → Magotherapy',
    successRateText: 'With Magotherapy treatment, in 74% of cases',
    successRateText2: 'vision restoration or stopping disease progression occurs',
    successRateText3: 'without surgery and medication.',
    resultsTitle: 'Results of Magotherapy:',
    results: [
      { title: '1. Visual field expands.', text: 'The patient begins to experience improved peripheral vision. "Tunnel vision" gradually expands.' },
      { title: '3. Nerve atrophy slows.', text: 'Further damage to optic nerve fibers decreases or stops.' },
      { title: '5. Intraocular pressure stabilizes.', text: 'Fluid circulation normalizes, trophics improve.' },
      { title: '2. Central vision increases.', text: 'The patient will notice vision improvement after ten days of procedures.' },
      { title: '4. Pain and discomfort disappear.', text: 'Headaches decrease, eye pain decreases.' },
      { title: '6. Quality of life improves.', text: 'The patient moves freely, daily activities become easier.' },
    ],
    warningTitle: 'ATTENTION',
    warningText: 'Low intraocular pressure does not stop disease progression and does not protect you from blindness.',
    patientVideosTitle: 'PATIENT EXPERIENCE',
    moreVideosYoutube: 'More videos on YouTube →',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    pageTitle: 'Глаукома',
    heroHeader: 'Остановка / Замедление Прогрессирования Болезни',
    heroText1: 'Маготерапия поможет вам восстановить зрение',
    heroText2: 'за счёт возрождения ресурсов вашего организма.',
    heroText3: 'Эффективное и безопасное лечение Маготерапией',
    heroText4: 'у нас — реальность!',
    resultInOneHour: 'Лечение без осложнений и боли -------- 20 лет стабильных результатов -------------остановка прогрессирования болезни',
    consultation: 'Консультация',
    contact: 'Контакт',
    definitionTitle: 'Глаукома',
    definition1: 'Относится к группе коварных глазных заболеваний. При этом заболевании происходит прогрессирующая атрофия зрительного нерва и потеря зрения. Через зрительный нерв осуществляется передача визуальной информации от глаза к мозгу.',
    definition2a: 'Распространённое мнение о том, что нормализация внутриглазного давления останавливает прогрессирование болезни — неверно.',
    definition2b: 'Существующие методы лечения — капли, хирургическая операция и лазерное лечение — направлены только на нормализацию внутриглазного давления.',
    definition3: 'Но даже при нормальном и низком внутриглазном давлении продолжается прогрессирующая атрофия зрительного нерва и соответствующих частей головного мозга, что нередко заканчивается слепотой.',
    magoBannerText: 'При лечении маготерапией в 88% случаев происходит восстановление зрения. На начальной стадии глаукомы выявление возможно только профессиональным врачом',
    whyVisionDecreaseTitle: 'Почему снижается зрение при глаукоме?',
    whyText1: 'Зрительный нерв состоит из 1,2 миллиона нервных волокон, через которые осуществляется передача визуальной информации от сетчатки в соответствующие части мозга.',
    whyText2: 'При глаукоме происходит прогрессирующая атрофия этих нервных волокон. Патологический процесс начинается с периферических волокон, поэтому первым симптомом является сужение поля зрения — "тоннельное" зрение.',
    whyText3: 'Процесс прогрессирует, происходит сужение центрального зрения, которое нередко заканчивается слепотой.',
    whyText4: 'Современная медицина не может остановить этот атрофический процесс — существующие методы лечения ориентированы только на снижение давления.',
    whenDevelopsTitle: 'Когда развивается глаукома?',
    whenText: 'Глаукома может развиться в любом возрасте, но чаще всего после 40 лет. К факторам риска относятся:',
    riskFactors: [
      'Повышенное внутриглазное давление',
      'Глаукома у других членов семьи',
      'Сахарный диабет',
      'Повышенное артериальное давление',
      'Миопия (близорукость)',
      'Травма или воспаление глаза',
      'Применение стероидных препаратов',
    ],
    riskGroupsTitle: 'Группы риска по глаукоме',
    riskGroupsText1: 'Особого внимания требуют люди, у которых есть близкие родственники с глаукомой. Генетическая предрасположенность значительно увеличивает вероятность развития болезни.',
    riskGroupsText2: 'После 40 лет всем рекомендуется профилактическое обследование у офтальмолога раз в год — одного измерения внутриглазного давления недостаточно, необходима проверка поля зрения.',
    riskGroupsText3: 'Помните: на ранней стадии глаукомы у пациентов часто вообще нет симптомов — это так называемый "тихий похититель зрения".',
    symptomsTitle: 'СИМПТОМЫ ГЛАУКОМЫ',
    symptoms: [
      'Сужение поля зрения (тоннельное зрение).',
      'Туман перед глазами.',
      'Радужные круги вокруг ламп.',
      'Снижение остроты зрения.',
      'Частые головные боли, боль в глазах.',
      'Повышенная чувствительность к свету.',
    ],
    twoFormsTitle: 'Две основные формы глаукомы',
    openAngleTitle: '1. Открытоугольная глаукома',
    openAngleText: 'Наиболее распространённая форма. Протекает бессимптомно, медленно и постепенно. Пациенты часто не замечают сужения поля зрения до поздней стадии.',
    closedAngleTitle: '2. Закрытоугольная глаукома',
    closedAngleText: 'Менее распространена, но возможен острый приступ — резкая боль, тошнота, внезапное снижение зрения. Требует экстренной медицинской помощи.',
    magotherapyTreatmentTitle: 'Лечение Маготерапией.',
    magotherapyText: 'При лечении глаукомы Маготерапией наша цель — остановить или замедлить прогрессирование атрофии зрительного нерва, восстановить зрение и уменьшить существующие симптомы путём активации собственных ресурсов организма.',
    treatWithUs: 'Мы лечим пациента, а не болезнь!',
    treatmentPrognosis: 'При лечении Маготерапией, на основании обследований, мы изучаем ресурсы конкретного организма и при первом же визите с точностью 97% даём прогноз, насколько улучшится зрение после лечения.',
    seeMoreMago: 'Подробнее → Маготерапия',
    successRateText: 'При лечении Маготерапией в 74% случаев',
    successRateText2: 'происходит восстановление зрения или остановка прогрессирования болезни',
    successRateText3: 'без хирургии и медикаментов.',
    resultsTitle: 'Результаты Маготерапии:',
    results: [
      { title: '1. Расширяется поле зрения.', text: 'Пациент начинает замечать улучшение периферического зрения. "Тоннельное" зрение постепенно расширяется.' },
      { title: '3. Замедляется атрофия нерва.', text: 'Дальнейшее повреждение волокон зрительного нерва уменьшается или останавливается.' },
      { title: '5. Стабилизируется внутриглазное давление.', text: 'Нормализуется циркуляция жидкости, улучшается трофика.' },
      { title: '2. Увеличивается центральное зрение.', text: 'Пациент заметит улучшение зрения после десяти дней процедур.' },
      { title: '4. Исчезают боль и дискомфорт.', text: 'Уменьшаются головные боли, уменьшаются боли в глазах.' },
      { title: '6. Улучшается качество жизни.', text: 'Пациент свободно передвигается, повседневные дела становятся легче.' },
    ],
    warningTitle: 'ВНИМАНИЕ',
    warningText: 'Низкое внутриглазное давление не останавливает прогрессирование болезни и не защищает вас от слепоты.',
    patientVideosTitle: 'ОПЫТ ПАЦИЕНТА',
    moreVideosYoutube: 'Другие видео на YouTube →',
  },
};

export function useGlaukomaTranslations(language: Language) {
  return glaukomaTranslations[language];
}
