import { Language } from '../contexts/LanguageContext';

const amblyopiaTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    bookBtn: 'ექიმთან\nმიღებაზე\nჩაწერა',
    pageTitle: 'ამბლიოპია',
    heroSubtitle: 'ფიზიოლოგიური , აპარატურული მკურნალობა მაგოთერაპიით.\ მხედველობის აღდგენა  მეორე გამოკვლევის შემდეგ.',
    heroStrong: 'დაავადების ხანგრძლივობას  და პაციენტის ასაკს   მნიშვნელობა არ აქვს.',
    heroResult: 'შედეგი ტესტირებიდან ერთ საათში — გართულების და რისკის გარეშე — 20 წელზე მეტი სტაბილური შედეგი',
    consultation: 'მიღებაზე ჩაწერა',
    contact: 'კონტაქტი',
    definitionSectionTitle: 'ამბლიოპია.',
    definition: 'ამბლიოპია — ეს არის სრული ან ნაწილობრივი მხედველობის დაქვეითება ერთ ან ორივე თვალზე, რომლის კორეგირებაც სათვალეებით და ლინზებით შეუძლებელია.',
    whyNotSeeTitle: 'რატომ ვერ ხედავს თვალი ამბლიოპიის დროს.',
    whySteps: [
      'ცუდად მხედველი თვალიდან ტვინამდე მიდის სუსტი ან ძალიან სუსტი იმპულსი.',
      'ტვინი ვერ აღიქვამს ამ იმპულს, ვერ გადაამუშავებს მას და ვერ უბრუნებს თვალს სრულყოფილ გამოსახულებას. ამიტომაც გამოსახულება ხდება წაშლილი და არა მკვეთრი.',
      'თვალი, რომელიც ცუდად ხედავს, აღარ მონაწილეობს მხედველობის პროცესში და იხრება გვერდით, ამიტომაც მას "ზარმაც" თვალს უწოდებენ.',
    ],
    binocularTitle: 'ბინოკულარული მხედველობა:',
    binocularText1: 'ტვინს არ შეუძლია მხოლოდ ერთი თვალიდან მიღებული გამოსახულება გახადოს სრულყოფილი და ამიტომ, სიელმის დროს შერწყმის უნარი ანუ ბინოკოლურალური მხედველობა.',
    binocularText2: 'შერწყმის უნარი საჭიროა იმისთვის, რომ ორივე თვალით მიღებული ინფორმაცია დავინახოთ სრულყოფილად და მკვეთრად განვარჩიოთ მხედველობის ველში მდებარე საგნების დეტალები. ამბლიოპიის დროს შერწყმის უნარი დაქვეითებულია, რაც დიდ დისკომფორტს უქმნის ადამიანს.',
    causesTitle: 'როდის ვითარდება ამბლიოპია.',
    causes: [
      { num: '1', title: 'სიელმე', text: 'სიელმე არის თვალის/ბის არასიმეტრიული დგომა, როდესაც ერთი ან ორივე თვალი პერიოდულად იხრება ცხვირისაკენ, საფეთქლისკენ, ზემოთ ან ქვემოთ.' },
      { num: '2', title: 'ანიზომეტროპია', text: 'ანიზომეტროპია ჰქვია იმ მდგომარეობას, როდესაც ორივე თვალის მხედველობის სიმახვილე და რეფრაქციები მკვეთრად განსხვავდება ერთმანეთისგან.' },
      { num: '3', title: 'ობსკურაციული სინდრომი', text: 'სხვა და სხვა დაავადებების დროს (კატარაქტა, პტოზი, რქოვანას შემღვრევა და სხვა), როდესაც სინათლის სხივი ვერ აღწევს ბადურამდე. საჭიროა ამ დარღვევების მკურნალობა ადრეული ასაკიდან.' },
    ],
    parentTitle: 'გინდათ ჯანმრთელი შვილი — დააკვირდით პატარას!',
    parentText: 'ადრეულ ასაკში ბავშვმა არ იცის და ვერ ხვდება, რომ ცუდად ხედავს.\n\nდაქვეითებული მხედველობა და მასთან დაკავშირებული პრობლემები აღიზიანებს ბავშვს და იგი ხდება ჭირველი, ხშირად ტირის, დაქვეითებული აქვს სწავლის უნარი, რასაც მშობლები ხშირად ბავშვის სიზარმაცით, ცუდი განწყობით ან ხასიათის თვისებებით ხსნიან.\n\nმხოლოდ მშობლებს მარტივი დაკვირვების შედეგად, შეუძლიათ საწყის ეტაპზე გამოავლინონ ბავშვის კონკრეტული თვალის სნეულება. ექიმთან დროული მიმართვა, განსაკუთრებით მაშინ, როდესაც არსებობს მემკვიდრული ფაქტორი, მომავალში ბევრ პრობლემებს აგარიდებთ.',
    symptomsTitle: 'სიმპტომები ბავშვებში:',
    symptoms: [
      'ჭუტავს თვალებს საგნის დათვალიერებისას.',
      'მზეს ერთი და იგივე მხარეს უშვერს სახეს.',
      'გამუდმებით ერთი და იგივე მხარეს ხრის თავს საგნის დათვალიერებისას.',
      'ხშირად ისრისავს თვალებს, ეფხანება.',
      'უჩივის თავის ტკივილს განსაკუთრებით საღამოობით.',
      'ხატვის ან წერის დროს ახლოს იხრება.',
      'ახასიათებს ხშირი ცრემლდენა და თვალის სიწითლე.',
      'უჭირს სიბნელისადმი ადაპტაცია (ეცემა ცუდი განათების დროს).',
      'ერთი ან ორივე თვალი პერიოდულად ეხრება.',
      'სწავლის დროს სირთულეები.',
    ],
    seeDocTitle: 'ერთი ან რამდენიმე სიმპტომის\nაღმოჩენისას მიმართეთ ექიმს!',
    seeDocText: 'დაქვეითებული მხედველობა წაუშლელ კვალს ტოვებს ბავშვის ფსიქიკაში და აფერხებს მის განვითარებას.',
    adultsTitle: 'მოზრდილებში',
    adultsText: 'მოზრდილები როგორც წესი ამბლიოპიას შემთხვევით, პროფილაქტიკური ან სავალდებულო შემოწმებისას აღმოაჩენენ, როდესაც პერიოდულად მხოლოდ ერთი თვალიდან იყურებიან.',
    weSeeBrainTitle: 'ვიყურებით თვალით\n\nვხედავთ ტვინით!',
    functionalText: 'ამბლიოპიის დროს ხილული ორგანული პათოლოგია არ აღინიშნება. მხედველობის დაქვეითების მიზეზი არის მხედველობის ანალიზატორის ფუნქციონალური დარღვევები, რომლის აღდგენაც არსებული მეთოდებით საკმაოდ პრობლემურია.',
    normalVisionTitle: 'ნორმალური მხედველობისას:',
    normalVisionSteps: [
      'თვალი, სინათლის გამოსახულების ფოკუსირებას ახდენს ბადურაზე.',
      'ბადურაზე სინათლის იმპულსები გარდაიქმნება ნერვულ იმპულსებად.',
      'ნერვული იმპულსები ოპტიკური ნერვების მეშვეობით აღწევენ თავის ტვინის მხედველობის ცენტრში, სადაც ხდება მათი გადამუშავება, შედეგად ტვინი სრულყოფილ გამოსახულებას უბრუნებს თვალს.',
    ],
    amblyopiaTitle: 'ამბლიოპიის დროს:',
    amblyopiaSteps: [
      'ნერვული იმპულსი ვერ აღწევს მხედველობის ცენტრამდე.',
      'ტვინი ვერ აღიქვამს ნერვულ იმპულსს, შესაბამისად ვერ ამუშავებს მას და ცუდად მხედველი თვალიდან გამოსახულება ხდება წაშლილი.',
    ],
    restorationTitle: 'მაგოთერაპიით მხედველობის აღდგენა:',
    restorationText1: 'მაგოთერაპიით მკურნალობისას, კანის ზემოდან განთავსებული სპეციალური აპარატურის ზემოქმედებით, წამის 0,002 ნაწილში, ხდება ბადურის ცენტრალურ ნაწილში (მაკულიარულ ზონაში) უჯრედების პარაბიოტული მდგომარეობიდან გამოყვანა. ხდება ბადურის ელემენტების ფუნქციურ სტრუქტურული აღდგენა, რაც უზრუნველყოფს სინათლის სხივის ნერვულ იმპულსად ტრანსფორმირებას.',
    restorationText2: 'უჯრედში მიმდინარე პოზიტიური ბიოქიმიური ცვლილებები, იწვევს იმავე სიჩქარით, ნერვული უჯრედის მემბრანული პოტენციალის გაზრდას, ნერვული იმპულსის გააქტიურებას. შედეგად ნერვული იმპულსი უკვე აღწევს თავის ტვინში — მხედველობის ცენტრამდე და თვალის წინ ჩნდება მკვეთრი და მკაფიო გამოსახულება.',
    restorationText3: 'ათ დღიანი პროცედურების დროს, რომელიც საჭიროა მიღებული შედეგის გასამყარებლად, ტვინის შესაბამისი ნაწილები "სწავლობენ" ნერვულ იმპულსებზე რეაგირებას. ეს და სხვა მრავალი ფაქტორი განაპირობებენ არა მარტო მხედველობის აღდგენას, არამედ მიღებული შედეგის სტაბილურობას 20 წელზე მეტ ხანს.',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    resultsTitle: 'მაგოთერაპიის მიღებული შედეგები:',
    results: [
      'ხდება მთლიანი ან ნაწილობრივი მხედველობის აღდგენა.',
      'თვალის გადახრისას (სიელმის) დროს კლებულობს გადახრის კუთხე.',
      'რამდენჯერმე ოპერირებული თვალიც, ღებულობს სიმეტრიულ დგომას.',
      'შედეგი სტაბილურია 20 წელზე მეტი.',
      'შერწყმის უნარი ანუ ბინოკულარული მხედველობა უახლოვდება ან ხდება ნორმა.',
    ],
    patientVideosTitle: 'პაციენტების გამოცდილება',
    contactToday: 'დაგვიკავშირდი დღესვე',
    modalTitle: 'ექიმთან მიღებაზე ჩაწერა',
    labelDate: 'სასურველი თარიღი',
    labelName: 'სახელი გვარი',
    labelEmail: 'Email',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    bookBtn: 'Book\nAppointment\nwith Doctor',
    pageTitle: 'AMBLYOPIA',
    heroSubtitle: 'Effective and safe vision restoration — within one hour of Magotherapy!',
    heroStrong: 'What others call impossible — is possible for us!!!',
    heroResult: 'Results within 1 hour of testing — no complications, no risk — stable results for over 20 years',
    consultation: 'Consultation',
    contact: 'Contact',
    definitionSectionTitle: 'AMBLYOPIA.',
    definition: 'Amblyopia is a complete or partial decrease in vision in one or both eyes that cannot be corrected with glasses or contact lenses.',
    whyNotSeeTitle: 'Why does the eye not see in amblyopia.',
    whySteps: [
      'A weak or very weak impulse travels from the poorly-seeing eye to the brain.',
      'The brain cannot perceive this impulse, cannot process it, and cannot return a complete image to the eye. Therefore, the image becomes blurred and not sharp.',
      'The eye that sees poorly no longer participates in the vision process and deviates sideways, which is why it is called a "lazy" eye.',
    ],
    binocularTitle: 'BINOCULAR VISION:',
    binocularText1: 'The brain cannot make the image received from only one eye complete, therefore in strabismus, fusion ability or binocular vision is impaired.',
    binocularText2: 'Fusion ability is needed to see the information received by both eyes completely and to clearly distinguish the details of objects in the visual field. In amblyopia, fusion ability is reduced, which causes great discomfort to the person.',
    causesTitle: 'When does amblyopia develop.',
    causes: [
      { num: '1', title: 'Strabismus', text: 'Strabismus is the asymmetric position of the eye(s), when one or both eyes periodically deviate toward the nose, temple, upward or downward.' },
      { num: '2', title: 'Anisometropia', text: 'Anisometropia is a condition where the visual acuity and refractions of both eyes differ significantly from each other.' },
      { num: '3', title: 'Obscuration syndrome', text: 'In various diseases (cataract, ptosis, corneal opacity, etc.), when light rays cannot reach the retina. Treatment of these disorders from an early age is necessary.' },
    ],
    parentTitle: 'Want a healthy child — watch your little one!',
    parentText: 'At an early age, children do not know and cannot realize that they see poorly.\n\nReduced vision and related problems irritate the child and they become fussy, cry often, have reduced learning ability, which parents often attribute to the child\'s laziness, bad mood, or personality traits.\n\nOnly parents, through simple observation, can detect a specific eye disease in a child at an early stage. Timely consultation with a doctor, especially when there is a hereditary factor, will spare you many problems in the future.',
    symptomsTitle: 'SYMPTOMS IN CHILDREN:',
    symptoms: [
      'Squints eyes when examining objects.',
      'Turns their face to the same side toward the sun.',
      'Constantly tilts head to the same side when examining objects.',
      'Frequently rubs eyes, scratches them.',
      'Complains of headaches, especially in the evening.',
      'Leans close while drawing or writing.',
      'Has frequent tearing and eye redness.',
      'Has difficulty adapting to darkness (falls in poor lighting).',
      'One or both eyes periodically deviate.',
      'Difficulties during learning.',
    ],
    seeDocTitle: 'If you notice one or more symptoms,\nconsult a doctor!',
    seeDocText: 'Reduced vision leaves an indelible mark on the child\'s psyche and hinders their development.',
    adultsTitle: 'IN ADULTS',
    adultsText: 'Adults usually discover amblyopia accidentally, during a preventive or mandatory examination, when they periodically look through only one eye.',
    weSeeBrainTitle: 'WE LOOK WITH OUR EYES\n\nWE SEE WITH OUR BRAIN!',
    functionalText: 'In amblyopia, no visible organic pathology is noted. The cause of vision impairment is functional disturbances of the visual analyzer, the restoration of which is quite problematic with existing methods.',
    normalVisionTitle: 'DURING NORMAL VISION:',
    normalVisionSteps: [
      'The eye focuses the light image onto the retina.',
      'On the retina, light impulses are converted into nerve impulses.',
      'Nerve impulses travel through the optic nerves to the visual center of the brain, where they are processed, and as a result, the brain returns a complete image to the eye.',
    ],
    amblyopiaTitle: 'DURING AMBLYOPIA:',
    amblyopiaSteps: [
      'The nerve impulse cannot reach the visual center.',
      'The brain cannot perceive the nerve impulse, accordingly cannot process it, and the image from the poorly-seeing eye becomes blurred.',
    ],
    restorationTitle: 'VISION RESTORATION WITH MAGOTHERAPY:',
    restorationText1: 'During Magotherapy treatment, under the influence of special equipment placed on the skin, in 0.002 seconds, cells in the central part of the retina (macular zone) are removed from parabiotical state. Functional and structural restoration of retinal elements occurs, ensuring the transformation of light rays into nerve impulses.',
    restorationText2: 'Positive biochemical changes occurring in the cell cause, at the same speed, an increase in the membrane potential of nerve cells and activation of nerve impulses. As a result, the nerve impulse now reaches the brain — the visual center — and a sharp and clear image appears before the eye.',
    restorationText3: 'During the ten-day procedures, which are needed to consolidate the obtained result, the corresponding brain areas "learn" to respond to nerve impulses. This and many other factors determine not only vision restoration, but also the stability of the obtained result for more than 20 years.',
    seeMoreMago: 'See more → Magotherapy',
    resultsTitle: 'RESULTS OF MAGOTHERAPY TREATMENT:',
    results: [
      'Complete or partial vision restoration occurs.',
      'With eye deviation (strabismus), the deviation angle decreases.',
      'An eye operated several times also assumes a symmetrical position.',
      'Results are stable for over 20 years.',
      'Fusion ability or binocular vision approaches or becomes normal.',
    ],
    patientVideosTitle: 'PATIENT EXPERIENCE',
    contactToday: 'Contact Us Today',
    modalTitle: 'Book an Appointment with the Doctor',
    labelDate: 'Preferred Date',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    bookBtn: 'Записаться\nна приём\nк врачу',
    pageTitle: 'АМБЛИОПИЯ',
    heroSubtitle: 'Эффективное и безопасное восстановление зрения — через один час Маготерапии!',
    heroStrong: 'Для других невозможное — для нас возможно!!!',
    heroResult: 'Результат через 1 час тестирования — без осложнений и риска — стабильный результат более 20 лет',
    consultation: 'Консультация',
    contact: 'Контакт',
    definitionSectionTitle: 'АМБЛИОПИЯ.',
    definition: 'Амблиопия — это полное или частичное снижение зрения на одном или обоих глазах, которое невозможно откорректировать очками или линзами.',
    whyNotSeeTitle: 'Почему глаз не видит при амблиопии.',
    whySteps: [
      'От плохо видящего глаза до мозга доходит слабый или очень слабый импульс.',
      'Мозг не воспринимает этот импульс, не может его обработать и не возвращает глазу полноценное изображение. Поэтому изображение становится размытым и нечётким.',
      'Глаз, который плохо видит, больше не участвует в зрительном процессе и отклоняется в сторону, поэтому его называют "ленивым" глазом.',
    ],
    binocularTitle: 'БИНОКУЛЯРНОЕ ЗРЕНИЕ:',
    binocularText1: 'Мозг не может сделать полноценным изображение, полученное только от одного глаза, поэтому при косоглазии нарушается способность к слиянию, то есть бинокулярное зрение.',
    binocularText2: 'Способность к слиянию необходима для того, чтобы видеть информацию, полученную обоими глазами, полностью и чётко различать детали предметов в поле зрения. При амблиопии способность к слиянию снижена, что создаёт человеку большой дискомфорт.',
    causesTitle: 'Когда развивается амблиопия.',
    causes: [
      { num: '1', title: 'Косоглазие', text: 'Косоглазие — это несимметричное положение глаза/глаз, когда один или оба глаза периодически отклоняются к носу, виску, вверх или вниз.' },
      { num: '2', title: 'Анизометропия', text: 'Анизометропия — состояние, при котором острота зрения и рефракции обоих глаз значительно отличаются друг от друга.' },
      { num: '3', title: 'Синдром обскурации', text: 'При различных заболеваниях (катаракта, птоз, помутнение роговицы и др.), когда световые лучи не достигают сетчатки. Необходимо лечение этих нарушений с раннего возраста.' },
    ],
    parentTitle: 'Хотите здорового ребёнка — наблюдайте за малышом!',
    parentText: 'В раннем возрасте ребёнок не знает и не понимает, что плохо видит.\n\nСниженное зрение и связанные с ним проблемы раздражают ребёнка, он становится капризным, часто плачет, у него снижена способность к учёбе, что родители часто объясняют ленью ребёнка, плохим настроением или чертами характера.\n\nТолько родители путём простого наблюдения могут выявить конкретное глазное заболевание ребёнка на начальном этапе. Своевременное обращение к врачу, особенно при наличии наследственного фактора, убережёт вас от многих проблем в будущем.',
    symptomsTitle: 'СИМПТОМЫ У ДЕТЕЙ:',
    symptoms: [
      'Щурит глаза при рассматривании предметов.',
      'Поворачивает лицо в одну и ту же сторону к солнцу.',
      'Постоянно наклоняет голову в одну и ту же сторону при рассматривании предметов.',
      'Часто трёт глаза, чешет их.',
      'Жалуется на головную боль, особенно вечером.',
      'Наклоняется близко во время рисования или письма.',
      'Часто слезятся и краснеют глаза.',
      'Трудно адаптируется к темноте (падает при плохом освещении).',
      'Один или оба глаза периодически отклоняются.',
      'Трудности во время учёбы.',
    ],
    seeDocTitle: 'При обнаружении одного или\nнескольких симптомов — обратитесь к врачу!',
    seeDocText: 'Сниженное зрение оставляет неизгладимый след в психике ребёнка и тормозит его развитие.',
    adultsTitle: 'У ВЗРОСЛЫХ',
    adultsText: 'Взрослые, как правило, обнаруживают амблиопию случайно, при профилактическом или обязательном осмотре, когда периодически смотрят только одним глазом.',
    weSeeBrainTitle: 'МЫ СМОТРИМ ГЛАЗАМИ\n\nМЫ ВИДИМ МОЗГОМ!',
    functionalText: 'При амблиопии видимой органической патологии не отмечается. Причиной снижения зрения являются функциональные нарушения зрительного анализатора, восстановление которого существующими методами весьма проблематично.',
    normalVisionTitle: 'ПРИ НОРМАЛЬНОМ ЗРЕНИИ:',
    normalVisionSteps: [
      'Глаз фокусирует световое изображение на сетчатке.',
      'На сетчатке световые импульсы преобразуются в нервные импульсы.',
      'Нервные импульсы через зрительные нервы достигают зрительного центра головного мозга, где обрабатываются, и в результате мозг возвращает глазу полноценное изображение.',
    ],
    amblyopiaTitle: 'ПРИ АМБЛИОПИИ:',
    amblyopiaSteps: [
      'Нервный импульс не достигает зрительного центра.',
      'Мозг не воспринимает нервный импульс, соответственно не может его обработать, и изображение от плохо видящего глаза становится размытым.',
    ],
    restorationTitle: 'ВОССТАНОВЛЕНИЕ ЗРЕНИЯ МАГОТЕРАПИЕЙ:',
    restorationText1: 'При лечении Маготерапией, под воздействием специальной аппаратуры, размещённой на коже, за 0,002 секунды клетки центральной части сетчатки (макулярной зоны) выводятся из парабиотического состояния. Происходит функционально-структурное восстановление элементов сетчатки, что обеспечивает трансформацию светового луча в нервный импульс.',
    restorationText2: 'Положительные биохимические изменения, происходящие в клетке, вызывают с той же скоростью увеличение мембранного потенциала нервной клетки, активацию нервного импульса. В результате нервный импульс теперь достигает мозга — зрительного центра — и перед глазом появляется чёткое и ясное изображение.',
    restorationText3: 'В течение десяти дней процедур, необходимых для закрепления полученного результата, соответствующие части мозга "учатся" реагировать на нервные импульсы. Это и многие другие факторы обусловливают не только восстановление зрения, но и стабильность полученного результата более 20 лет.',
    seeMoreMago: 'Подробнее → Маготерапия',
    resultsTitle: 'РЕЗУЛЬТАТЫ ЛЕЧЕНИЯ МАГОТЕРАПИЕЙ:',
    results: [
      'Происходит полное или частичное восстановление зрения.',
      'При отклонении глаза (косоглазии) угол отклонения уменьшается.',
      'Глаз, оперированный несколько раз, также принимает симметричное положение.',
      'Результат стабилен более 20 лет.',
      'Способность к слиянию или бинокулярное зрение приближается к норме или становится нормой.',
    ],
    patientVideosTitle: 'ОПЫТ ПАЦИЕНТА',
    contactToday: 'Свяжитесь с нами сегодня',
    modalTitle: 'Записаться на приём к врачу',
    labelDate: 'Желаемая дата',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
  },
};

export function useAmblyopiaTranslations(language: Language) {
  return amblyopiaTranslations[language];
}
