export interface TextField {
  key: string;
  label: string;
  multiline?: boolean;
  rows?: number;
}

export interface PageContentDef {
  page: string;
  title: string;
  fields: TextField[];
}

export const pageContentDefs: Record<string, PageContentDef> = {
  page_home: {
    page: 'home',
    title: 'მთავარი გვერდი',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'heroTitle', label: 'ჰეროს სათაური', multiline: false },
      { key: 'heroSubtitle', label: 'ჰეროს ქვესათაური', rows: 3 },
      { key: 'naturalMethod', label: 'ბუნებრივი მეთოდი', multiline: false },
      { key: 'withApparatus', label: 'კანის ზემოდან (სტრიქონი 1)', multiline: false },
      { key: 'noSurgeryFull', label: 'ქირურგიის გარეშე (სტრიქონი 2)', multiline: false },
      { key: 'evenForIncurable', label: 'განუკურნებადი (სტრიქონი 3)', multiline: false },
      { key: 'thatCantBeCured', label: 'განუკურნებადი (სტრიქონი 4)', multiline: false },
      { key: 'patentedText', label: 'პატენტის ტექსტი', rows: 3 },
      { key: 'patientsCount', label: 'პაციენტთა რაოდენობა', rows: 3 },
      { key: 'feature1', label: 'მახასიათებელი 1', rows: 3 },
      { key: 'feature2', label: 'მახასიათებელი 2', rows: 3 },
      { key: 'feature3', label: 'მახასიათებელი 3', rows: 3 },
      { key: 'feature4', label: 'მახასიათებელი 4', rows: 3 },
      { key: 'feature5', label: 'მახასიათებელი 5', rows: 3 },
      { key: 'feature6', label: 'მახასიათებელი 6', rows: 3 },
      { key: 'feature7', label: 'მახასიათებელი 7', rows: 3 },
      { key: 'feature8', label: 'მახასიათებელი 8', rows: 3 },
      { key: 'tagline', label: 'ლოზუნგი', rows: 3 },
      { key: 'magoTherapyTitle', label: 'მაგოთერაპიის სათაური', multiline: false },
      { key: 'clinicName', label: 'კლინიკის სახელი', multiline: false },
      { key: 'intro1', label: 'შესავალი 1', rows: 4 },
      { key: 'intro2', label: 'შესავალი 2', rows: 4 },
      { key: 'intro3', label: 'შესავალი 3', rows: 4 },
      { key: 'intro4', label: 'შესავალი 4', rows: 3 },
      { key: 'doctorName', label: 'ექიმის სახელი', multiline: false },
      { key: 'doctorSubtitle', label: 'ექიმის ქვეტექსტი (ათწლეული)', rows: 2 },
      { key: 'doctorDesc1', label: 'ექიმის აღწერა 1', rows: 4 },
      { key: 'doctorDesc2', label: 'ექიმის აღწერა 2', rows: 3 },
      { key: 'magoCard1Title', label: 'ბარათი 1 — სათაური', multiline: false },
      { key: 'magoCard1', label: 'ბარათი 1 — ტექსტი', rows: 5 },
      { key: 'magoCard2Title', label: 'ბარათი 2 — სათაური', multiline: false },
      { key: 'magoCard2', label: 'ბარათი 2 — ტექსტი', rows: 5 },
      { key: 'magoCard3Title', label: 'ბარათი 3 — სათაური', multiline: false },
      { key: 'magoCard3', label: 'ბარათი 3 — ტექსტი', rows: 5 },
      { key: 'result1', label: 'შედეგი 1', rows: 4 },
      { key: 'result2', label: 'შედეგი 2', rows: 4 },
      { key: 'result3', label: 'შედეგი 3', rows: 4 },
      { key: 'contactToday', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'personalizedTreatment', label: 'პერსონიფ. მკ. (მარცხენა)', rows: 2 },
      { key: 'noSurgery', label: 'ქ-გარეშე (მარჯვენა)', multiline: false },
      { key: 'clinicAndTreatment', label: 'კლინიკა • მკ. (მობ. სათ. 1)', multiline: false },
      { key: 'visionRestoration', label: 'მხ. აღდგ. (მობ. სათ. 2)', multiline: false },
      { key: 'nonSurgicalTbilisi', label: 'არაქირ. (მობ. ქვე)', multiline: false },
      { key: 'consultation', label: 'კონსულტ. ღილაკი', multiline: false },
      { key: 'contactBtn', label: 'კონტ. ღილაკი', multiline: false },
      { key: 'mobilePoint1', label: 'მობ. პუნქტი 1', multiline: false },
      { key: 'mobilePoint2', label: 'მობ. პუნქტი 2', multiline: false },
      { key: 'mobilePoint3', label: 'მობ. პუნქტი 3', multiline: false },
      { key: 'mobilePoint4', label: 'მობ. პუნქტი 4', multiline: false },
      { key: 'seeMore', label: 'იხ. მეტი ლინკი', multiline: false },
      { key: 'check1', label: 'ჩეკ-სია 1', rows: 3 },
      { key: 'check2', label: 'ჩეკ-სია 2', rows: 3 },
      { key: 'check3', label: 'ჩეკ-სია 3', rows: 3 },
      { key: 'check4', label: 'ჩეკ-სია 4', rows: 3 },
      { key: 'check5', label: 'ჩეკ-სია 5', rows: 3 },
      { key: 'magoTitle', label: 'მაგოთ. სექ. სათ.', multiline: false },
      { key: 'magoCard1Full', label: 'ბარათი 1 — მობ. ტექსტი', rows: 3 },
      { key: 'magoCard2Full', label: 'ბარათი 2 — მობ. ტექსტი', rows: 3 },
      { key: 'magoCard3Full', label: 'ბარათი 3 — მობ. ტექსტი', rows: 3 },
      { key: 'magoFootnote', label: 'მაგოთ. სქოლიო', rows: 3 },
      { key: 'clinicCity', label: 'კლინიკის ქალაქი', multiline: false },
      { key: 'seeMoreClinic', label: 'კლინ. „იხ. მეტი" ლინკი', multiline: false },
      { key: 'resultQuestion1', label: 'შ-კ. 1 (შედ. სექ.)', rows: 2 },
      { key: 'resultQuestion2', label: 'შ-კ. 2 (შედ. სექ.)', rows: 2 },
      { key: 'feature2mobile', label: 'მახ. 2 მობ.', rows: 2 },
      { key: 'modalTitle', label: 'მოდ. სათ.', multiline: false },
      { key: 'labelDate', label: 'თარ. ლეიბ.', multiline: false },
      { key: 'labelName', label: 'სახ. ლეიბ.', multiline: false },
      { key: 'labelEmail', label: 'ემ. ლეიბ.', multiline: false },
      { key: 'labelPhone', label: 'ტელ. ლეიბ.', multiline: false },
      { key: 'labelAge', label: 'ას. ლეიბ.', multiline: false },
      { key: 'labelIAm', label: 'მე ვარ ლეიბ.', multiline: false },
      { key: 'optionChoose', label: 'არჩ. ოფ.', multiline: false },
      { key: 'optionPatient', label: 'პაც. ოფ.', multiline: false },
      { key: 'optionFamily', label: 'ოჯ. ოფ.', multiline: false },
      { key: 'optionFriend', label: 'მეგ. ოფ.', multiline: false },
      { key: 'labelHistory', label: 'ისტ. ლეიბ.', multiline: false },
      { key: 'agreePolicy', label: 'პოლ. ტექ.', multiline: false },
      { key: 'submit', label: 'გაგ. ღილ.', multiline: false },
    ],
  },
  page_navigation: {
    page: 'navigation',
    title: 'ნავიგაცია',
    fields: [
      { key: 'home', label: 'მთავარი', multiline: false },
      { key: 'magotherapy', label: 'მაგოთერაპია', multiline: false },
      { key: 'faq', label: 'კითხვა-პასუხი', multiline: false },
      { key: 'gallery', label: 'გალერეა', multiline: false },
      { key: 'photoGallery', label: 'ფოტო გალერეა', multiline: false },
      { key: 'videoGallery', label: 'ვიდეო გალერეა', multiline: false },
      { key: 'results', label: 'შედეგები', multiline: false },
      { key: 'general', label: 'ზოგადი', multiline: false },
      { key: 'sielme', label: 'სიელმე', multiline: false },
      { key: 'pigmentaryRetinitis', label: 'პიგმენტური რეტინიტი', multiline: false },
      { key: 'amblyopia', label: 'ამბლიოპია', multiline: false },
      { key: 'glaukoma', label: 'გლაუკომა', multiline: false },
      { key: 'astigmatizm', label: 'ასტიგმატიზმი', multiline: false },
      { key: 'about', label: 'ჩვენს შესახებ', multiline: false },
      { key: 'contact', label: 'კონტაქტი', multiline: false },
    ],
  },
  page_footer: {
    page: 'footer',
    title: 'ქვედა ბარი',
    fields: [
      { key: 'contact', label: 'კონტაქტი (სათაური)', multiline: false },
      { key: 'menu', label: 'მენიუ (სათაური)', multiline: false },
      { key: 'followUs', label: 'გამოგვყევი (სათაური)', multiline: false },
      { key: 'followSocial', label: 'სოციალური მედია ტექსტი', multiline: false },
      { key: 'home', label: 'მთავარი (ლინკი)', multiline: false },
      { key: 'magotherapy', label: 'მაგოთერაპია (ლინკი)', multiline: false },
      { key: 'faq', label: 'შეკითხვები (ლინკი)', multiline: false },
      { key: 'gallery', label: 'გალერეა (ლინკი)', multiline: false },
      { key: 'results', label: 'შედეგები (ლინკი)', multiline: false },
      { key: 'about', label: 'ჩვენს შესახებ (ლინკი)', multiline: false },
      { key: 'contactLink', label: 'კონტაქტი (ლინკი)', multiline: false },
      { key: 'visitorsCount', label: 'ვიზიტორთა ტექსტი', multiline: false },
      { key: 'address', label: 'მისამართი', rows: 3 },
      { key: 'facebookButton', label: 'ფეისბუქის ღილაკი', multiline: false },
      { key: 'youtubeButton', label: 'იუთუბის ღილაკი', multiline: false },
    ],
  },
  page_about: {
    page: 'about',
    title: 'ჩვენს შესახებ',
    fields: [
      { key: 'clinicTitle', label: 'კლინიკის სახელი', multiline: false },
      { key: 'magoTherapy', label: 'მაგოთერაპია (ჰეროს სათაური)', multiline: false },
      { key: 'aboutUs', label: 'ჩვენს შესახებ (ჰეროს ქვესათაური)', multiline: false },
      { key: 'heroText', label: 'ჰეროს ტექსტი', rows: 4 },
      { key: 'sinceText', label: '1996 წლიდან ტექსტი', multiline: false },
      { key: 'clinicSectionTitle', label: 'კლინიკის სექციის სათაური', multiline: false },
      { key: 'patentAlt', label: 'პატენტის სურათის Alt ტექსტი', multiline: false },
      { key: 'clinicDesc', label: 'კლინიკის აღწერა', rows: 5 },
      { key: 'aboutUsBanner', label: 'ბანერის ტექსტი', multiline: false },
      { key: 'tbilisiClinicIntro', label: 'თბილისი კლინიკის შესავალი', rows: 4 },
      { key: 'bioIntro', label: 'ბიოგრაფია შესავალი', rows: 4 },
      { key: 'bio2', label: 'ბიოგრაფია 2', rows: 4 },
      { key: 'methodText', label: 'მეთოდის ტექსტი', rows: 5 },
      { key: 'treatmentAlsoFor', label: 'მკურნალობა ასევე ტექსტი', rows: 4 },
      { key: 'advantagesTitle', label: 'უპირატესობების სათაური', multiline: false },
      { key: 'experience', label: 'გამოცდილება', rows: 3 },
      { key: 'patientsCount', label: 'პაციენტთა რაოდენობა', rows: 3 },
      { key: 'qualityImprove', label: 'ხარისხის გაუმჯობესება', multiline: false },
      { key: 'statsTitle', label: 'სტატისტიკის სათაური', multiline: false },
      { key: 'howVisionRestored', label: 'როგორ აღდგება მხედველობა', multiline: false },
      { key: 'howText', label: 'მხედველობის აღდგენის ტექსტი', rows: 6 },
      { key: 'repeatCourse1', label: 'განმეორებითი კურსი 1', multiline: false },
      { key: 'repeatCourse2', label: 'განმეორებითი კურსი 2', multiline: false },
      { key: 'repeatCourse3', label: 'განმეორებითი კურსი 3', multiline: false },
      { key: 'repeatCourse4', label: 'განმეორებითი კურსი 4', multiline: false },
      { key: 'repeatCourse5', label: 'განმეორებითი კურსი 5', multiline: false },
      { key: 'repeatCourse6', label: 'განმეორებითი კურსი 6', multiline: false },
      { key: 'researchText', label: 'კვლევის ტექსტი', rows: 4 },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთ. ლინკი', multiline: false },
      { key: 'authorTitle', label: 'ავტორის სათაური', multiline: false },
      { key: 'academicQual', label: 'აკადემ. კვალ. სათაური', multiline: false },
      { key: 'publicActivity', label: 'საზ. აქტ. სათაური', multiline: false },
      { key: 'publications', label: 'ნაბეჭდი შრომები სათაური', multiline: false },
      { key: 'awards', label: 'ჯილდოები სათაური', multiline: false },
      { key: 'academicCvText', label: 'აკადემ. CV ტექსტი (ჩამოყ.)', rows: 20 },
      { key: 'publicActivityText', label: 'საზ. აქტ. ტექსტი (ჩამოყ.)', rows: 12 },
      { key: 'publicationsText', label: 'ნაბეჭდი შრომები ტექსტი (ჩამოყ.)', rows: 20 },
      { key: 'awardsText', label: 'ჯილდოები ტექსტი (ჩამოყ.)', rows: 6 },
      { key: 'phoneNumber', label: 'ტელეფონის ნომერი (მოკლე)', multiline: false },
      { key: 'phoneNumberFull', label: 'ტელეფონის ნომერი (სრული)', multiline: false },
      { key: 'emailAddress', label: 'ელ.ფოსტა', multiline: false },
      { key: 'facebookUrl', label: 'Facebook URL', multiline: false },
      { key: 'youtubeUrl', label: 'YouTube URL', multiline: false },
      { key: 'whatsappUrl', label: 'WhatsApp URL', multiline: false },
    ],
  },
  page_contact: {
    page: 'contact',
    title: 'კონტაქტი',
    fields: [
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'clinicName', label: 'კლინიკის სახელი', multiline: false },
      { key: 'magotherapy', label: 'მაგოთერაპია (ქვეტექსტი)', multiline: false },
      { key: 'workingHours', label: 'სამუშაო საათები სათაური', multiline: false },
      { key: 'workingTime', label: 'სამუშაო საათები', multiline: false },
      { key: 'exceptWeekends', label: 'შაბათ-კვირის გარდა', multiline: false },
      { key: 'appointmentRequired', label: 'ჩაწერა სავალდებულოა', multiline: false },
      { key: 'viberWhatsApp', label: 'Viber / WhatsApp ლეიბლი', multiline: false },
      { key: 'address', label: 'მისამართი', rows: 3 },
      { key: 'emailLabel', label: 'ელ.ფოსტის ლეიბლი', multiline: false },
      { key: 'bookingTitle', label: 'ჩაწერის სათაური', multiline: false },
      { key: 'bookingButton', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'bookingNote', label: 'ჩაწერის შენიშვნა', rows: 3 },
      { key: 'whatsAppTitle', label: 'WhatsApp სათაური', multiline: false },
      { key: 'whatsAppButton', label: 'WhatsApp ღილაკი', multiline: false },
      { key: 'leftP1', label: 'მარცხენა ტექსტი 1 (გამუქებული)', rows: 3 },
      { key: 'leftP2', label: 'მარცხენა ტექსტი 2', rows: 3 },
      { key: 'leftP3', label: 'მარცხენა ტექსტი 3', rows: 4 },
      { key: 'leftP4', label: 'მარცხენა ტექსტი 4', rows: 3 },
      { key: 'bannerText1', label: 'ლურჯი ბანერი — სტრიქონი 1', rows: 3 },
      { key: 'bannerText2', label: 'ლურჯი ბანერი — სტრიქონი 2 (დიდი)', rows: 2 },
      { key: 'leftP5', label: 'მარცხენა ტექსტი 5', rows: 3 },
      { key: 'leftP6', label: 'მარცხენა ტექსტი 6', rows: 3 },
      { key: 'leftP7', label: 'მარცხენა ტექსტი 7 (ასაკი — ლურჯი)', rows: 2 },
      { key: 'leftP8', label: 'მარცხენა ტექსტი 8', rows: 3 },
      { key: 'clinicBannerTitle', label: 'კლინიკის ბანერი — სათაური', multiline: false },
      { key: 'clinicBannerText', label: 'კლინიკის ბანერი — ტექსტი (ბავშვები)', rows: 4 },
    ],
  },
  page_faq: {
    page: 'faq',
    title: 'კითხვა-პასუხი',
    fields: [
      { key: 'title', label: 'გვერდის სათაური', multiline: false },
      { key: 'youtubeNotePrefix', label: 'YouTube შენიშვნა', rows: 3 },
      { key: 'youtubeNoteLinkText', label: 'YouTube ლინკის ტექსტი', multiline: false },
      { key: 'q1', label: 'კითხვა 1', rows: 3 },
      { key: 'a1', label: 'პასუხი 1', rows: 6 },
      { key: 'q2', label: 'კითხვა 2', rows: 3 },
      { key: 'a2', label: 'პასუხი 2', rows: 8 },
      { key: 'q3', label: 'კითხვა 3', rows: 3 },
      { key: 'a3', label: 'პასუხი 3', rows: 5 },
      { key: 'q4', label: 'კითხვა 4 (სტატისტიკის სათაური)', rows: 3 },
      { key: 'q5', label: 'კითხვა 5', rows: 3 },
      { key: 'a5', label: 'პასუხი 5', rows: 5 },
      { key: 'q6', label: 'კითხვა 6', rows: 3 },
      { key: 'a6', label: 'პასუხი 6', rows: 6 },
      { key: 'q7', label: 'კითხვა 7', rows: 3 },
      { key: 'a7', label: 'პასუხი 7', rows: 6 },
      { key: 'q8', label: 'კითხვა 8', rows: 3 },
      { key: 'a8', label: 'პასუხი 8', rows: 8 },
      { key: 'q9', label: 'კითხვა 9', rows: 3 },
      { key: 'a9', label: 'პასუხი 9', rows: 5 },
      { key: 'q10', label: 'კითხვა 10', rows: 3 },
      { key: 'a10', label: 'პასუხი 10', rows: 5 },
      { key: 'q11', label: 'კითხვა 11', rows: 3 },
      { key: 'a11', label: 'პასუხი 11', rows: 8 },
      { key: 'stat_condition_1', label: 'სტატ. მდგომ. 1', multiline: false },
      { key: 'stat_pct_1', label: 'სტატ. % 1', multiline: false },
      { key: 'stat_condition_2', label: 'სტატ. მდგომ. 2', multiline: false },
      { key: 'stat_pct_2', label: 'სტატ. % 2', multiline: false },
      { key: 'stat_condition_3', label: 'სტატ. მდგომ. 3', multiline: false },
      { key: 'stat_pct_3', label: 'სტატ. % 3', multiline: false },
      { key: 'stat_condition_4', label: 'სტატ. მდგომ. 4', multiline: false },
      { key: 'stat_pct_4', label: 'სტატ. % 4', multiline: false },
      { key: 'stat_condition_5', label: 'სტატ. მდგომ. 5', multiline: false },
      { key: 'stat_pct_5', label: 'სტატ. % 5', multiline: false },
      { key: 'stat_condition_6', label: 'სტატ. მდგომ. 6', multiline: false },
      { key: 'stat_pct_6', label: 'სტატ. % 6', multiline: false },
      { key: 'stat_condition_7', label: 'სტატ. მდგომ. 7', multiline: false },
      { key: 'stat_pct_7', label: 'სტატ. % 7', multiline: false },
      { key: 'stat_condition_8', label: 'სტატ. მდგომ. 8', multiline: false },
      { key: 'stat_pct_8', label: 'სტატ. % 8', multiline: false },
      { key: 'stat_condition_9', label: 'სტატ. მდგომ. 9', multiline: false },
      { key: 'stat_pct_9', label: 'სტატ. % 9', multiline: false },
    ],
  },
  page_magotherapy: {
    page: 'magotherapy',
    title: 'მაგოთერაპია',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'subtitle', label: 'ქვესათაური', rows: 4 },
      { key: 'clinicallyTested', label: 'კლინიკურად გამოცდილი', rows: 3 },
      { key: 'mainHeading', label: 'მთავარი სათაური', multiline: false },
      { key: 'mainSubheading', label: 'მთავარი ქვესათაური', rows: 4 },
      { key: 'whatIsMagotherapy', label: 'რას ეფუძნება (სათაური)', multiline: false },
      { key: 'vedenskyText', label: 'ვედენსკის ტექსტი 1', rows: 6 },
      { key: 'vedenskyText2', label: 'ვედენსკის ტექსტი 2', rows: 6 },
      { key: 'magotherapyBoldText', label: 'გამუქებული ტექსტი', rows: 5 },
      { key: 'parabiozi', label: 'პარაბიოზი (სათაური)', multiline: false },
      { key: 'parabioziText', label: 'პარაბიოზის ტექსტი', rows: 10 },
      { key: 'whyPoorVision', label: 'რატომ ხედავთ ცუდად (სათაური)', multiline: false },
      { key: 'whyPoorVisionText', label: 'რატომ ხედავთ ცუდად (ტექსტი)', rows: 3 },
      { key: 'whyPoorVisionImportantHeading', label: 'მკაფიო ხედვისთვის (სათაური)', multiline: false },
      { key: 'important1', label: 'მნიშვნელოვანია 1', rows: 3 },
      { key: 'important2', label: 'მნიშვნელოვანია 2', rows: 3 },
      { key: 'important3', label: 'მნიშვნელოვანია 3', rows: 3 },
      { key: 'whyPoorVisionClosing', label: 'მხედველობის დახურვა', rows: 4 },
      { key: 'important', label: 'მნიშვნელოვანია (ლეიბლი)', multiline: false },
      { key: 'whatIsNerveImpulse', label: 'ნერვული იმპულსი (სათაური)', multiline: false },
      { key: 'nerveImpulseText', label: 'ნერვული იმპულსი (ტექსტი)', rows: 4 },
      { key: 'neuronComparison1', label: 'ნეირონი შედარება 1', rows: 5 },
      { key: 'neuronComparison2', label: 'ნეირონი შედარება 2', rows: 5 },
      { key: 'howNerveImpulseFormed', label: 'ნერვული იმპულსი (სათაური 2)', multiline: false },
      { key: 'nerveImpulseFormationText', label: 'ნერვული იმპულსი ჩამოყალიბება', rows: 5 },
      { key: 'synchronousActivity', label: 'სინქრონული აქტივობა', rows: 4 },
      { key: 'whyVisionRestoresInHour', label: 'მადლიერება (სათაური)', multiline: false },
      { key: 'fedorovTribute', label: 'ფედოროვისადმი მადლობა', rows: 6 },
      { key: 'mechanismOfRecovery', label: 'აღდგენის მექანიზმი (სათაური)', multiline: false },
      { key: 'mechanismText', label: 'მექანიზმის ტექსტი', rows: 5 },
      { key: 'biochemicalSubheading', label: 'ბიოქიმიური ცვლ. ქვესათაური', rows: 3 },
      { key: 'biochemicalChange1', label: 'ბიოქიმიური ცვლ. 1', rows: 3 },
      { key: 'biochemicalChange2', label: 'ბიოქიმიური ცვლ. 2', rows: 3 },
      { key: 'biochemicalChange3', label: 'ბიოქიმიური ცვლ. 3', rows: 3 },
      { key: 'biochemicalChange4', label: 'ბიოქიმიური ცვლ. 4', rows: 3 },
      { key: 'biochemicalChange5', label: 'ბიოქიმიური ცვლ. 5', rows: 3 },
      { key: 'positiveChangesResult', label: 'პოზიტიური ცვლ. შედეგი', rows: 3 },
      { key: 'step1', label: 'ნაბიჯი 1', rows: 3 },
      { key: 'step2', label: 'ნაბიჯი 2', rows: 3 },
      { key: 'step3', label: 'ნაბიჯი 3', rows: 3 },
      { key: 'step4', label: 'ნაბიჯი 4', rows: 3 },
      { key: 'step5', label: 'ნაბიჯი 5', rows: 3 },
      { key: 'step6', label: 'ნაბიჯი 6', rows: 3 },
      { key: 'wholeSecret', label: 'საიდუმლო ტექსტი', rows: 3 },
      { key: 'secretText', label: 'საიდუმლო (მოკლე)', rows: 4 },
      { key: 'treatmentAmbulatory', label: 'ამბულატორიული მკურნალობა', multiline: false },
      { key: 'patientAge', label: 'პაციენტის ასაკი', multiline: false },
      { key: 'lightningFlashes', label: 'ელვის სათაური', multiline: false },
      { key: 'lightningText', label: 'ელვის ტექსტი', rows: 5 },
      { key: 'howRealisticToTreat', label: 'რამდენად რეალურია (სათაური)', multiline: false },
      { key: 'treatPatientNotDisease', label: 'ვმკურნალობთ პაციენტს', multiline: false },
      { key: 'treatPatientText', label: 'პაციენტის ტექსტი', rows: 5 },
      { key: 'successStatistics', label: 'წარმატების სტატისტიკა', multiline: false },
      { key: 'statistics1', label: 'სტატისტიკა 1', multiline: false },
      { key: 'statistics2', label: 'სტატისტიკა 2', multiline: false },
      { key: 'statistics3', label: 'სტატისტიკა 3', multiline: false },
      { key: 'statistics4', label: 'სტატისტიკა 4', multiline: false },
      { key: 'statistics5', label: 'სტატისტიკა 5', multiline: false },
      { key: 'statistics6', label: 'სტატისტიკა 6', multiline: false },
      { key: 'statistics7', label: 'სტატისტიკა 7', multiline: false },
      { key: 'statistics8', label: 'სტატისტიკა 8', multiline: false },
      { key: 'statistics9', label: 'სტატისტიკა 9', multiline: false },
      { key: 'repeatCourses', label: 'განმეორებითი კურსები', rows: 4 },
      { key: 'contraindications', label: 'უკუჩვენებები (სათაური)', multiline: false },
      { key: 'contraindication1', label: 'უკუჩვენება 1', multiline: false },
      { key: 'contraindication2', label: 'უკუჩვენება 2', multiline: false },
      { key: 'contraindication3', label: 'უკუჩვენება 3', multiline: false },
      { key: 'contraindication4', label: 'უკუჩვენება 4', multiline: false },
      { key: 'contraindication5', label: 'უკუჩვენება 5', multiline: false },
      { key: 'sideEffects', label: 'გვერდითი მოვლენები', multiline: false },
      { key: 'risk', label: 'რისკი', multiline: false },
      { key: 'complications', label: 'გართულებები', multiline: false },
      { key: 'allergies', label: 'ალერგია', multiline: false },
      { key: 'excluded', label: 'გამორიცხულია', multiline: false },
      { key: 'advantages', label: 'უპირატესობები (სათაური)', multiline: false },
      { key: 'advantage1', label: 'უპირატესობა 1', rows: 3 },
      { key: 'advantage2', label: 'უპირატესობა 2', rows: 3 },
      { key: 'advantage3', label: 'უპირატესობა 3', rows: 3 },
      { key: 'advantage4', label: 'უპირატესობა 4', rows: 3 },
      { key: 'advantage5', label: 'უპირატესობა 5', rows: 3 },
      { key: 'advantage6', label: 'უპირატესობა 6', rows: 3 },
      { key: 'advantage7', label: 'უპირატესობა 7', rows: 3 },
      { key: 'advantage8', label: 'უპირატესობა 8', rows: 3 },
      { key: 'advantage9', label: 'უპირატესობა 9', rows: 3 },
      { key: 'advantage10', label: 'უპირატესობა 10', rows: 3 },
      { key: 'advantage11', label: 'უპირატესობა 11', rows: 3 },
      { key: 'advantage12', label: 'უპირატესობა 12', rows: 3 },
      { key: 'advantage13', label: 'უპირატესობა 13', rows: 3 },
      { key: 'advantage14', label: 'უპირატესობა 14', rows: 3 },
      { key: 'advantage15', label: 'უპირატესობა 15', rows: 3 },
      { key: 'advantage16', label: 'უპირატესობა 16', rows: 3 },
      { key: 'advantage17', label: 'უპირატესობა 17', rows: 3 },
      { key: 'advantage18', label: 'უპირატესობა 18', rows: 3 },
      { key: 'canYouHelpMe', label: 'დამეხმარებით?', multiline: false },
    ],
  },
  page_booking: {
    page: 'booking',
    title: 'ჩაწერა',
    fields: [
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'labelDate', label: 'თარიღის ლეიბლი', multiline: false },
      { key: 'labelName', label: 'სახელის ლეიბლი', multiline: false },
      { key: 'labelEmail', label: 'ელ.ფოსტის ლეიბლი', multiline: false },
      { key: 'labelPhone', label: 'ტელეფონის ლეიბლი', multiline: false },
      { key: 'labelAge', label: 'ასაკის ლეიბლი', multiline: false },
      { key: 'labelIAm', label: 'მე ვარ ლეიბლი', multiline: false },
      { key: 'optionChoose', label: 'აირჩიეთ ოფცია', multiline: false },
      { key: 'optionPatient', label: 'პაციენტი', multiline: false },
      { key: 'optionFamily', label: 'ოჯახის წევრი', multiline: false },
      { key: 'optionFriend', label: 'მეგობარი', multiline: false },
      { key: 'labelHistory', label: 'ისტორიის ლეიბლი', multiline: false },
      { key: 'agreePolicy', label: 'პოლიტიკის ტექსტი', multiline: false },
      { key: 'submit', label: 'გაგზავნის ღილაკი', multiline: false },
    ],
  },
  page_glaukoma: {
    page: 'glaukoma',
    title: 'გლაუკომა',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'heroHeader', label: 'ჰეროს სათაური', multiline: false },
      { key: 'heroText1', label: 'ჰეროს ტექსტი 1', rows: 3 },
      { key: 'heroText2', label: 'ჰეროს ტექსტი 2', rows: 3 },
      { key: 'heroText3', label: 'ჰეროს ტექსტი 3', rows: 3 },
      { key: 'heroText4', label: 'ჰეროს ტექსტი 4', rows: 3 },
      { key: 'resultInOneHour', label: 'შედეგი ბანერი', rows: 3 },
      { key: 'consultation', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'contact', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'definitionTitle', label: 'განმარტების სათაური', multiline: false },
      { key: 'definition1', label: 'განმარტება 1', rows: 5 },
      { key: 'definition2a', label: 'განმარტება 2a', rows: 4 },
      { key: 'definition2b', label: 'განმარტება 2b', rows: 4 },
      { key: 'definition3', label: 'განმარტება 3', rows: 4 },
      { key: 'magoBannerText', label: 'მაგო ბანერი', rows: 4 },
      { key: 'whyVisionDecreaseTitle', label: 'რატომ კლებულობს სათაური', multiline: false },
      { key: 'whyText1', label: 'რატომ კლებულობს 1', rows: 4 },
      { key: 'whyText2', label: 'რატომ კლებულობს 2', rows: 4 },
      { key: 'whyText3', label: 'რატომ კლებულობს 3', rows: 4 },
      { key: 'whyText4', label: 'რატომ კლებულობს 4', rows: 4 },
      { key: 'whenDevelopsTitle', label: 'როდის ვითარდება სათაური', multiline: false },
      { key: 'whenText', label: 'როდის ვითარდება ტექსტი', rows: 3 },
      { key: 'riskGroupsTitle', label: 'რისკ ჯგუფები სათაური', multiline: false },
      { key: 'riskGroupsText1', label: 'რისკ ჯგუფები 1', rows: 4 },
      { key: 'riskGroupsText2', label: 'რისკ ჯგუფები 2', rows: 4 },
      { key: 'riskGroupsText3', label: 'რისკ ჯგუფები 3', rows: 4 },
      { key: 'symptomsTitle', label: 'სიმპტომების სათაური', multiline: false },
      { key: 'twoFormsTitle', label: 'ორი ფორმა სათაური', multiline: false },
      { key: 'openAngleTitle', label: 'ღია კუთხიანი სათაური', multiline: false },
      { key: 'openAngleText', label: 'ღია კუთხიანი ტექსტი', rows: 4 },
      { key: 'closedAngleTitle', label: 'დახურული კუთხიანი სათაური', multiline: false },
      { key: 'closedAngleText', label: 'დახურული კუთხიანი ტექსტი', rows: 4 },
      { key: 'magotherapyTreatmentTitle', label: 'მაგოთერაპიით მკურნალობა სათაური', multiline: false },
      { key: 'magotherapyText', label: 'მაგოთერაპიით მკურნალობა ტექსტი', rows: 5 },
      { key: 'treatWithUs', label: 'ვმკურნალობთ პაციენტს', multiline: false },
      { key: 'treatmentPrognosis', label: 'მკურნალობის პროგნოზი', rows: 5 },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთერაპია', multiline: false },
      { key: 'successRateText', label: 'წარმატების % ტექსტი 1', rows: 3 },
      { key: 'successRateText2', label: 'წარმატების % ტექსტი 2', rows: 3 },
      { key: 'successRateText3', label: 'წარმატების % ტექსტი 3', rows: 3 },
      { key: 'resultsTitle', label: 'შედეგების სათაური', multiline: false },
      { key: 'warningTitle', label: 'ყურადღება სათაური', multiline: false },
      { key: 'warningText', label: 'ყურადღება ტექსტი', rows: 3 },
      { key: 'patientVideosTitle', label: 'პაციენტების ვიდეო სათაური', multiline: false },
      { key: 'moreVideosYoutube', label: 'YouTube ვიდეოები', multiline: false },
    ],
  },
  page_amblyopia: {
    page: 'amblyopia',
    title: 'ამბლიოპია',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'heroSubtitle', label: 'ჰეროს ქვესათაური', rows: 3 },
      { key: 'heroStrong', label: 'ჰეროს გამუქებული', multiline: false },
      { key: 'heroResult', label: 'ჰეროს შედეგი', rows: 3 },
      { key: 'consultation', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'contact', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'definitionSectionTitle', label: 'განმარტების სათაური', multiline: false },
      { key: 'definition', label: 'განმარტება', rows: 4 },
      { key: 'whyNotSeeTitle', label: 'რატომ ვერ ხედავს სათაური', multiline: false },
      { key: 'binocularTitle', label: 'ბინოკულარული სათაური', multiline: false },
      { key: 'binocularText1', label: 'ბინოკულარული 1', rows: 4 },
      { key: 'binocularText2', label: 'ბინოკულარული 2', rows: 4 },
      { key: 'causesTitle', label: 'მიზეზები სათაური', multiline: false },
      { key: 'parentTitle', label: 'მშობლებს სათაური', multiline: false },
      { key: 'parentText', label: 'მშობლებს ტექსტი', rows: 6 },
      { key: 'symptomsTitle', label: 'სიმპტომები სათაური', multiline: false },
      { key: 'seeDocTitle', label: 'ექიმს მიმართეთ სათაური', rows: 3 },
      { key: 'seeDocText', label: 'ექიმს მიმართეთ ტექსტი', rows: 3 },
      { key: 'adultsTitle', label: 'მოზრდილებში სათაური', multiline: false },
      { key: 'adultsText', label: 'მოზრდილებში ტექსტი', rows: 4 },
      { key: 'weSeeBrainTitle', label: 'ვხედავთ ტვინით სათაური', rows: 3 },
      { key: 'functionalText', label: 'ფუნქციური ტექსტი', rows: 4 },
      { key: 'normalVisionTitle', label: 'ნორმალური მხედველობა სათაური', multiline: false },
      { key: 'amblyopiaTitle', label: 'ამბლიოპიის სათაური', multiline: false },
      { key: 'restorationTitle', label: 'აღდგენის სათაური', multiline: false },
      { key: 'restorationText1', label: 'აღდგენა ტექსტი 1', rows: 5 },
      { key: 'restorationText2', label: 'აღდგენა ტექსტი 2', rows: 5 },
      { key: 'restorationText3', label: 'აღდგენა ტექსტი 3', rows: 5 },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთერაპია', multiline: false },
      { key: 'resultsTitle', label: 'შედეგების სათაური', multiline: false },
      { key: 'patientVideosTitle', label: 'პაციენტების ვიდეო სათაური', multiline: false },
      { key: 'contactToday', label: 'დაგვიკავშირდი', multiline: false },
      { key: 'modalTitle', label: 'მოდალის სათაური', multiline: false },
      { key: 'labelDate', label: 'თარიღის ლეიბლი', multiline: false },
      { key: 'labelName', label: 'სახელის ლეიბლი', multiline: false },
      { key: 'labelEmail', label: 'ელ.ფოსტის ლეიბლი', multiline: false },
      { key: 'labelPhone', label: 'ტელეფონის ლეიბლი', multiline: false },
      { key: 'labelAge', label: 'ასაკის ლეიბლი', multiline: false },
      { key: 'labelIAm', label: 'მე ვარ ლეიბლი', multiline: false },
      { key: 'optionChoose', label: 'აირჩიეთ ოფცია', multiline: false },
      { key: 'optionPatient', label: 'პაციენტი', multiline: false },
      { key: 'optionFamily', label: 'ოჯახის წევრი', multiline: false },
      { key: 'optionFriend', label: 'მეგობარი', multiline: false },
      { key: 'labelHistory', label: 'ისტორიის ლეიბლი', multiline: false },
      { key: 'agreePolicy', label: 'პოლიტიკის ტექსტი', multiline: false },
      { key: 'submit', label: 'გაგზავნა', multiline: false },
    ],
  },
  page_astigmatizm: {
    page: 'astigmatizm',
    title: 'ასტიგმატიზმი',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'heroTitle1', label: 'ჰეროს სათაური 1', multiline: false },
      { key: 'heroTitle2', label: 'ჰეროს სათაური 2', multiline: false },
      { key: 'heroTitle3', label: 'ჰეროს სათაური 3', multiline: false },
      { key: 'heroClinical', label: 'ჰეროს კლინიკური', rows: 3 },
      { key: 'consultation', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'contact', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'definitionText1', label: 'განმარტება 1', rows: 4 },
      { key: 'definitionText2', label: 'განმარტება 2', rows: 4 },
      { key: 'successRateBanner', label: 'წარმატების % ბანერი', rows: 3 },
      { key: 'formsTitle', label: 'ფორმები სათაური', multiline: false },
      { key: 'congenitalTitle', label: 'თანდაყოლილი სათაური', multiline: false },
      { key: 'congenitalText1', label: 'თანდაყოლილი ტექსტი 1', rows: 4 },
      { key: 'congenitalText2', label: 'თანდაყოლილი ტექსტი 2', rows: 4 },
      { key: 'adviceTitle', label: 'რჩევა სათაური', multiline: false },
      { key: 'adviceLine1', label: 'რჩევა 1', multiline: false },
      { key: 'adviceLine2', label: 'რჩევა 2', multiline: false },
      { key: 'adviceLine3', label: 'რჩევა 3', multiline: false },
      { key: 'seeMoreAmblyopia', label: 'ამბლიოპია ლინკი', multiline: false },
      { key: 'seeMoreSielme', label: 'სიელმე ლინკი', multiline: false },
      { key: 'acquiredTitle', label: 'შეძენილი სათაური', multiline: false },
      { key: 'acquiredText', label: 'შეძენილი ტექსტი', rows: 4 },
      { key: 'symptomsBanner', label: 'სიმპტომები ბანერი', multiline: false },
      { key: 'childrenTitle', label: 'ბავშვებში სათაური', multiline: false },
      { key: 'childrenText', label: 'ბავშვებში ტექსტი', rows: 5 },
      { key: 'childrenSymptomsSubtitle', label: 'ბავშვის სიმპტ. ქვესათ.', rows: 3 },
      { key: 'adultsTitle', label: 'მოზრდილებში სათაური', multiline: false },
      { key: 'correctionTitle', label: 'კორექცია სათაური', multiline: false },
      { key: 'correctionText1', label: 'კორექცია ტექსტი 1', rows: 5 },
      { key: 'correctionText2', label: 'კორექცია ტექსტი 2', rows: 4 },
      { key: 'ownEyesBanner', label: 'საკუთარი თვალები ბანერი', multiline: false },
      { key: 'magotherapyTitle', label: 'მაგოთერაპია სათაური', multiline: false },
      { key: 'magotherapyText1', label: 'მაგოთერაპია 1', rows: 4 },
      { key: 'magotherapyText2', label: 'მაგოთერაპია 2', rows: 4 },
      { key: 'magotherapyText3', label: 'მაგოთერაპია 3', rows: 4 },
      { key: 'magotherapyText4', label: 'მაგოთერაპია 4', rows: 4 },
      { key: 'magotherapyText5', label: 'მაგოთერაპია 5', rows: 5 },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთერაპია', multiline: false },
      { key: 'since1996', label: '1996 წლიდან', rows: 3 },
      { key: 'resultsBanner', label: 'შედეგები ბანერი', multiline: false },
      { key: 'successRateResult', label: 'წარმატების % შედეგი', rows: 3 },
      { key: 'patientVideosTitle', label: 'პაციენტების ვიდეო სათაური', multiline: false },
      { key: 'contactToday', label: 'დაგვიკავშირდი', multiline: false },
      { key: 'modalTitle', label: 'მოდალის სათაური', multiline: false },
      { key: 'labelDate', label: 'თარიღის ლეიბლი', multiline: false },
      { key: 'labelName', label: 'სახელის ლეიბლი', multiline: false },
      { key: 'labelEmail', label: 'ელ.ფოსტის ლეიბლი', multiline: false },
      { key: 'labelPhone', label: 'ტელეფონის ლეიბლი', multiline: false },
      { key: 'labelAge', label: 'ასაკის ლეიბლი', multiline: false },
      { key: 'labelIAm', label: 'მე ვარ ლეიბლი', multiline: false },
      { key: 'optionChoose', label: 'აირჩიეთ ოფცია', multiline: false },
      { key: 'optionPatient', label: 'პაციენტი', multiline: false },
      { key: 'optionFamily', label: 'ოჯახის წევრი', multiline: false },
      { key: 'optionFriend', label: 'მეგობარი', multiline: false },
      { key: 'labelHistory', label: 'ისტორიის ლეიბლი', multiline: false },
      { key: 'agreePolicy', label: 'პოლიტიკის ტექსტი', multiline: false },
      { key: 'submit', label: 'გაგზავნა', multiline: false },
    ],
  },
  page_sielme: {
    page: 'sielme',
    title: 'სიელმე',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'heroText1', label: 'ჰეროს ტექსტი 1', multiline: false },
      { key: 'heroText2', label: 'ჰეროს ტექსტი 2', multiline: false },
      { key: 'heroText3', label: 'ჰეროს ტექსტი 3', multiline: false },
      { key: 'heroText4', label: 'ჰეროს ტექსტი 4', multiline: false },
      { key: 'heroText5', label: 'ჰეროს ტექსტი 5', multiline: false },
      { key: 'heroText6', label: 'ჰეროს ტექსტი 6', multiline: false },
      { key: 'resultInOneHour', label: 'შედეგი ბანერი', rows: 3 },
      { key: 'consultation', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'contact', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'definitionTitle', label: 'განმარტების სათაური', multiline: false },
      { key: 'definition', label: 'განმარტება', rows: 4 },
      { key: 'notCosmeticTitle', label: 'არა კოსმეტიკური სათაური', rows: 3 },
      { key: 'symptom1', label: 'სიმპტომი 1', multiline: false },
      { key: 'symptom2', label: 'სიმპტომი 2', multiline: false },
      { key: 'symptom3', label: 'სიმპტომი 3', multiline: false },
      { key: 'symptom4', label: 'სიმპტომი 4', multiline: false },
      { key: 'symptom5', label: 'სიმპტომი 5', multiline: false },
      { key: 'whenTitle', label: 'როდის ვლინდება სათაური', multiline: false },
      { key: 'whenText1', label: 'როდის ვლინდება 1', rows: 3 },
      { key: 'whenText2', label: 'როდის ვლინდება 2', rows: 3 },
      { key: 'whenText3', label: 'როდის ვლინდება 3', rows: 3 },
      { key: 'whenText4', label: 'როდის ვლინდება 4', rows: 3 },
      { key: 'whenText5', label: 'როდის ვლინდება 5', rows: 3 },
      { key: 'dontDelay1', label: 'ნუ გადადებთ 1', multiline: false },
      { key: 'dontDelay2', label: 'ნუ გადადებთ 2', multiline: false },
      { key: 'earlyTreatment', label: 'ადრეული მკურნალობა', multiline: false },
      { key: 'earlyText', label: 'ადრეული ტექსტი', rows: 4 },
      { key: 'whyTitle', label: 'რატომ იხრება სათაური', multiline: false },
      { key: 'whyText1', label: 'რატომ იხრება 1', rows: 5 },
      { key: 'whyText2', label: 'რატომ იხრება 2', rows: 4 },
      { key: 'withoutFunction', label: 'ფუნქციის გარეშე', multiline: false },
      { key: 'organAtrophies', label: 'ორგანო ატროფიას', multiline: false },
      { key: 'lazyEyeText', label: 'ზარმაცი თვალი ტექსტი', rows: 3 },
      { key: 'fusionDamaged', label: 'შერწყმა ზიანდება', multiline: false },
      { key: 'fusionText1', label: 'შერწყმა 1', rows: 4 },
      { key: 'fusionText2', label: 'შერწყმა 2', rows: 4 },
      { key: 'commonTreatmentTitle', label: 'საყოველთაო მკურნალობა სათ.', multiline: false },
      { key: 'commonText1', label: 'საყოველთაო 1', rows: 4 },
      { key: 'commonText2', label: 'საყოველთაო 2', rows: 5 },
      { key: 'commonText3', label: 'საყოველთაო 3', rows: 4 },
      { key: 'medicineEvolvesTitle1', label: 'მედიცინა ვითარდება 1', multiline: false },
      { key: 'medicineEvolvesTitle2', label: 'მედიცინა ვითარდება 2', multiline: false },
      { key: 'medicineEvolvesText1', label: 'მედიცინა ვითარდება ტ.1', rows: 3 },
      { key: 'medicineEvolvesText2', label: 'მედიცინა ვითარდება ტ.2', rows: 3 },
      { key: 'medicineEvolvesText3', label: 'მედიცინა ვითარდება ტ.3', rows: 3 },
      { key: 'magotherapy', label: 'მაგოთერაპია', multiline: false },
      { key: 'since1996', label: '1996 წლიდან', rows: 3 },
      { key: 'stableResult', label: 'სტაბილური შედეგი', multiline: false },
      { key: 'howWeCorrectTitle', label: 'როგორ ვასწორებთ სათ.', multiline: false },
      { key: 'howText1', label: 'როგორ ვასწ. 1', rows: 4 },
      { key: 'howText2', label: 'როგორ ვასწ. 2', rows: 4 },
      { key: 'howText3', label: 'როგორ ვასწ. 3', rows: 4 },
      { key: 'positiveChangesText', label: 'პოზიტიური ცვლ. ტექსტი', rows: 4 },
      { key: 'resultsTitle', label: 'შედეგების სათაური', multiline: false },
      { key: 'resultsText', label: 'შედეგების ტექსტი', rows: 5 },
      { key: 'adviceTitle', label: 'რჩევები მშობლებს სათ.', multiline: false },
      { key: 'adviceText1', label: 'რჩევა 1', rows: 3 },
      { key: 'adviceText2', label: 'რჩევა 2', rows: 5 },
      { key: 'noticeText1', label: 'შენიშვნა 1', rows: 3 },
      { key: 'noticeText2', label: 'შენიშვნა 2', rows: 3 },
      { key: 'noticeText3', label: 'შენიშვნა 3', rows: 3 },
      { key: 'earlyDetection', label: 'ადრეული გამოვლენა', rows: 3 },
      { key: 'patientVideosTitle', label: 'პაციენტების ვიდეო სათ.', multiline: false },
    ],
  },
  page_pigmenturetinite: {
    page: 'pigmenturetinite',
    title: 'პიგმენტური რეტინიტი',
    fields: [
      { key: 'appointmentOnly', label: 'მიღების შეტყობინება', multiline: false },
      { key: 'pageTitle1', label: 'გვერდის სათაური 1', multiline: false },
      { key: 'pageTitle2', label: 'გვერდის სათაური 2', multiline: false },
      { key: 'heroText1', label: 'ჰეროს ტექსტი 1', rows: 3 },
      { key: 'heroText2', label: 'ჰეროს ტექსტი 2', rows: 3 },
      { key: 'heroText3', label: 'ჰეროს ტექსტი 3', rows: 3 },
      { key: 'heroText4', label: 'ჰეროს ტექსტი 4', rows: 3 },
      { key: 'resultInOneHour', label: 'შედეგი ბანერი', rows: 3 },
      { key: 'consultation', label: 'ჩაწერის ღილაკი', multiline: false },
      { key: 'contact', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'definitionTitle', label: 'განმარტების სათაური', multiline: false },
      { key: 'definition1', label: 'განმარტება 1', rows: 3 },
      { key: 'definition2', label: 'განმარტება 2', rows: 3 },
      { key: 'definition3', label: 'განმარტება 3', rows: 4 },
      { key: 'definition4', label: 'განმარტება 4', rows: 3 },
      { key: 'definition5', label: 'განმარტება 5', rows: 3 },
      { key: 'definition6', label: 'განმარტება 6', rows: 3 },
      { key: 'distrophiesTitle1', label: 'დისტროფიები სათ. 1', multiline: false },
      { key: 'distrophiesTitle2', label: 'დისტროფიები სათ. 2', multiline: false },
      { key: 'initialSymptomsTitle', label: 'საწყისი სიმპტ. სათ.', multiline: false },
      { key: 'initialSymptomsText', label: 'საწყისი სიმპტ. ტექსტი', rows: 5 },
      { key: 'childrenWarning', label: 'ბავშვები გაფრთხ.', multiline: false },
      { key: 'childrenText1', label: 'ბავშვები 1', rows: 4 },
      { key: 'childrenText2', label: 'ბავშვები 2', rows: 3 },
      { key: 'primarySymptomsTitle', label: 'პირველადი სიმპტ. სათ.', multiline: false },
      { key: 'noteTitle', label: 'შენიშვნა სათაური', multiline: false },
      { key: 'noteText', label: 'შენიშვნა ტექსტი', rows: 4 },
      { key: 'mainSymptomsTitle', label: 'ძირითადი სიმპტ. სათ.', multiline: false },
      { key: 'whyDecreaseTitle', label: 'რატომ კლებულობს სათ.', multiline: false },
      { key: 'whyText1', label: 'რატომ კლებულობს 1', rows: 4 },
      { key: 'whyText2', label: 'რატომ კლებულობს 2', rows: 4 },
      { key: 'whyText3', label: 'რატომ კლებულობს 3', rows: 5 },
      { key: 'magotherapyTreatTitle', label: 'მაგოთ. მკ. სათ.', multiline: false },
      { key: 'magotherapyTreatText', label: 'მაგოთ. მკ. ტექსტი', rows: 4 },
      { key: 'treatWithUs', label: 'ვმკურნალობთ პაციენტს', multiline: false },
      { key: 'treatmentPrognosis', label: 'მკ. პროგნოზი', rows: 6 },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთ.', multiline: false },
      { key: 'howVisionRestoredTitle', label: 'როგორ აღდგება სათ.', multiline: false },
      { key: 'howText1', label: 'როგორ აღდგება 1', rows: 5 },
      { key: 'howText2', label: 'როგორ აღდგება 2', rows: 5 },
      { key: 'howText3', label: 'როგორ აღდგება 3', rows: 5 },
      { key: 'successRateText', label: 'წარმ. % ტ. 1', rows: 3 },
      { key: 'successRateText2', label: 'წარმ. % ტ. 2', rows: 3 },
      { key: 'successRateText3', label: 'წარმ. % ტ. 3', rows: 3 },
      { key: 'resultsTitle', label: 'შედეგების სათ.', multiline: false },
      { key: 'patientVideosTitle', label: 'პაც. ვიდეო სათ.', multiline: false },
      { key: 'moreVideosYoutube', label: 'YouTube ვიდეოები', multiline: false },
    ],
  },
  page_zogadi: {
    page: 'zogadi',
    title: 'ზოგადი შედეგები',
    fields: [
      { key: 'pageTitle', label: 'გვერდის სათაური', multiline: false },
      { key: 'magoActivates', label: 'მაგო ააქტიურებს', rows: 3 },
      { key: 'restoresResources', label: 'რესურსი აღდგება', rows: 3 },
      { key: 'restoresCells', label: 'უჯრედები ფუნქციონირებს', rows: 3 },
      { key: 'visionRestores', label: 'მხედველობა აღდგება', rows: 3 },
      { key: 'clinicallyProven', label: 'კლინიკურად დამტკ.', rows: 3 },
      { key: 'contactUs', label: 'კონტაქტის ღილაკი', multiline: false },
      { key: 'seeMoreMago', label: 'იხ. მეტი მაგოთ.', multiline: false },
      { key: 'visionPossible', label: 'მხ. შესაძლებელია', multiline: false },
      { key: 'clinicDescription', label: 'კლინიკის აღწერა', rows: 5 },
      { key: 'impossiblePossible', label: 'შეუძლებელი შეიძლება', multiline: false },
      { key: 'seeMore', label: 'იხ. მეტი', multiline: false },
      { key: 'disease_0_title', label: 'დავ. 1 სათ. (ამბლ.)', multiline: false },
      { key: 'disease_0_description', label: 'დავ. 1 აღწ. (ამბლ.)', rows: 6 },
      { key: 'disease_0_successRate', label: 'დავ. 1 წარმ. % (ამბლ.)', rows: 3 },
      { key: 'disease_1_title', label: 'დავ. 2 სათ. (პიგმ.)', multiline: false },
      { key: 'disease_1_description', label: 'დავ. 2 აღწ. (პიგმ.)', rows: 6 },
      { key: 'disease_1_successRate', label: 'დავ. 2 წარმ. % (პიგმ.)', rows: 3 },
      { key: 'disease_2_title', label: 'დავ. 3 სათ. (სიელ.)', multiline: false },
      { key: 'disease_2_description', label: 'დავ. 3 აღწ. (სიელ.)', rows: 6 },
      { key: 'disease_2_successRate', label: 'დავ. 3 წარმ. % (სიელ.)', rows: 3 },
      { key: 'disease_3_title', label: 'დავ. 4 სათ. (ასტ.)', multiline: false },
      { key: 'disease_3_description', label: 'დავ. 4 აღწ. (ასტ.)', rows: 6 },
      { key: 'disease_3_successRate', label: 'დავ. 4 წარმ. % (ასტ.)', rows: 3 },
      { key: 'disease_4_title', label: 'დავ. 5 სათ. (გლაუ.)', multiline: false },
      { key: 'disease_4_description', label: 'დავ. 5 აღწ. (გლაუ.)', rows: 6 },
      { key: 'disease_4_successRate', label: 'დავ. 5 წარმ. % (გლაუ.)', rows: 3 },
      { key: 'disease_5_title', label: 'დავ. 6 სათ. (შორსმ.)', multiline: false },
      { key: 'disease_5_description', label: 'დავ. 6 აღწ. (შორსმ.)', rows: 6 },
      { key: 'disease_5_successRate', label: 'დავ. 6 წარმ. % (შორსმ.)', rows: 3 },
      { key: 'disease_6_title', label: 'დავ. 7 სათ. (მიოპ.)', multiline: false },
      { key: 'disease_6_description', label: 'დავ. 7 აღწ. (მიოპ.)', rows: 6 },
      { key: 'disease_6_successRate', label: 'დავ. 7 წარმ. % (მიოპ.)', rows: 3 },
      { key: 'disease_7_title', label: 'დავ. 8 სათ. (ნისტ.)', multiline: false },
      { key: 'disease_7_description', label: 'დავ. 8 აღწ. (ნისტ.)', rows: 6 },
      { key: 'disease_7_successRate', label: 'დავ. 8 წარმ. % (ნისტ.)', rows: 3 },
    ],
  },
  page_gallery: {
    page: 'gallery',
    title: 'გალერეა',
    fields: [
      { key: 'photoGalleryTitle', label: 'ფოტო გალერეის სათაური', multiline: false },
      { key: 'videoGalleryTitle', label: 'ვიდეო გალერეის სათაური', multiline: false },
    ],
  },
};
