import { Language } from '../contexts/LanguageContext';

const navTranslations = {
  ge: {
    home: 'მთავარი',
    magotherapy: 'მაგოთერაპია',
    treatment: 'მკურნალობა',
    magotherapyFull: 'მაგოთერაპია',
    faq: 'შეკითხვები',
    gallery: 'გალერეა',
    photoGallery: 'ფოტო გალერეა',
    videoGallery: 'ვიდეო გალერეა',
    results: 'შედეგები',
    general: 'ზოგადი',
    sielme: 'სიელმე',
    pigmentaryRetinitis: 'პიგმენტური რეტინიტი',
    amblyopia: 'ამბლიოპია',
    glaukoma: 'გლაუკომა',
    astigmatizm: 'ასტიგმატიზმი',
    about: 'ჩვენს შესახებ',
    contact: 'კონტაქტი',
    resultsGeneral: 'შედეგები — ზოგადი',
    resultsSielme: 'შედეგები — სიელმე',
    resultsPigmentary: 'შედეგები — პიგმენტური რეტინიტი',
    resultsAmblyopia: 'შედეგები — ამბლიოპია',
    resultsGlaukoma: 'შედეგები — გლაუკომა',
    resultsAstigmatizm: 'შედეგები — ასტიგმატიზმი',
  },
  en: {
    home: 'Home',
    magotherapy: 'Magotherapy',
    treatment: 'Treatment',
    magotherapyFull: 'Magotherapy',
    faq: 'FAQ',
    gallery: 'Gallery',
    photoGallery: 'Photo Gallery',
    videoGallery: 'Video Gallery',
    results: 'Results',
    general: 'General',
    sielme: 'Strabismus',
    pigmentaryRetinitis: 'Pigmentary Retinitis',
    amblyopia: 'Amblyopia',
    glaukoma: 'Glaucoma',
    astigmatizm: 'Astigmatism',
    about: 'About Us',
    contact: 'Contact',
    resultsGeneral: 'Results — General',
    resultsSielme: 'Results — Strabismus',
    resultsPigmentary: 'Results — Pigmentary Retinitis',
    resultsAmblyopia: 'Results — Amblyopia',
    resultsGlaukoma: 'Results — Glaucoma',
    resultsAstigmatizm: 'Results — Astigmatism',
  },
  ru: {
    home: 'Главная',
    magotherapy: 'Маготерапия',
    treatment: 'Лечение',
    magotherapyFull: 'Маготерапия',
    faq: 'Вопросы',
    gallery: 'Галерея',
    photoGallery: 'Фото галерея',
    videoGallery: 'Видео галерея',
    results: 'Результаты',
    general: 'Общие',
    sielme: 'Косоглазие',
    pigmentaryRetinitis: 'Пигментный ретинит',
    amblyopia: 'Амблиопия',
    glaukoma: 'Глаукома',
    astigmatizm: 'Астигматизм',
    about: 'О нас',
    contact: 'Контакт',
    resultsGeneral: 'Результаты — Общие',
    resultsSielme: 'Результаты — Косоглазие',
    resultsPigmentary: 'Результаты — Пигментный ретинит',
    resultsAmblyopia: 'Результаты — Амблиопия',
    resultsGlaukoma: 'Результаты — Глаукома',
    resultsAstigmatizm: 'Результаты — Астигматизм',
  },
};

export function useNavTranslations(language: Language) {
  return navTranslations[language];
}
