import { Language } from '../contexts/LanguageContext';

const zogadiTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    pageTitle: 'შედეგები',
    magoActivates: 'კანის ზემოდან განთავსებული აპარატურა აუმჯობესებს ნივთერებათა ცვლას,',
    restoresResources: 'აღადგენს ორგანიზმის გამოუყენებელ რესურსს',
    restoresCells: 'ბადურის უჯრედები და მხედველობის ანალიზატორი იწყებენ ფუნქციონირებას.',
    visionRestores: '"განუკურნებადი" დაავადების დროს აღდგება მხედველობა.',
    clinicallyProven: 'კლინიკურად დამტკიცებულია — სტაბილური შედეგი — ქირურგიის და მედიკამენტების გარეშე.',
    contactUs: 'დაგვეკონტაქტე',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    visionPossible: 'მხედველობის აღდგენა მაგოთერაპიით შესაძლებელია!',
    clinicDescription: 'თვალის კლინიკა "ახალი ტექნოლოგიები-MaGo", ექსკლუზიური მეთოდით მაგოთერაპია - აპარატურული პერსონიფიცირებული მკურნალობა, აღადგენს მხედველობას როგორც წარუმატებელი ოპერაციების შემდეგ, აგრეთვე თვალის სხვა და სხვა სნეულებების დროს, ისეთი დაავადების დროსაც, რომელიც გჯერათ რომ არ ინკურნება.',
    impossiblePossible: 'სხვისთვის შეუძლებელი - ჩვენთვის შესაძლებელია!',
    seeMore: 'იხილეთ მეტი →',
    disease_0_title: 'ამბლიოპია (ზარმაცი თვალი)',
    disease_0_description: 'ვითარდება მხედველობის სიმახვილის დაქვეითების შემთხვევაში ერთ ან ორივე თვალზე. დაავადების დროს, ბადურაზე, მხედველობის ნერვის და თავის ტვინის შესაბამის ნაწილებში, აღინიშნება ფუნქციონალური დარღვევები, ხილული ცვლილებების გარეშე. სუსტი მხედველობის გამო, თვალი ვერ მონაწილეობს მხედველობის პროცესში. მხედველობის ანალიზატორი „გადაჩვეული" ინფორმაციის გადამუშვას, რადგან ბადურაზე მოხვედრილი შუქის სხივი ვერ აღწევს ტვინამდე. ამბლიოპია ხშირად ბავშვობაში ვითარდება, თუმცა შესაძლოა მოზრდილებშიც გამოვლინდეს.',
    disease_0_successRate: 'ამბლიოპიის მკურნალობა მაგოთერაპიით 97% შემთხვეხაში აღადგენს მხედველობას პაციენტის ასაკის მიუხედავად.',
    disease_1_title: 'პიგმენტური რეტინიტი',
    disease_1_description: 'მიეკუთვნება ბადურის დისტროფიების ჯგუფს. ახასიათებს ბადურა გარსზე ფოტორეცეპტორების ფუნქციის დაქვეითება (აპოპტოზი), ბადურის უჯრედები, რომელიც განაპირობებენ მხედველობას შებინდებისას (ჩხირები), თანდათანობით კარგავენ ფუნქციურ თვისებებს, ხდება მათი გადაგვარება, რის გამოც მხედველობა შებინდებისას უარესდება. ბადურა გარსის და მხედველობის ანალიზატორის უჯრედების დისფუნქცია, არის სიბრმავის გამომწვევი ძირითადი მიზეზი.',
    disease_1_successRate: 'მაგოთერაპიით მკურნალობისას მხედველობის აღდგენა ხდება 90% შემთხვეხაში, კონკრეტული ორგანიზმის რესურსზე დაყრდნობით.',
    disease_2_title: 'სიელმე',
    disease_2_description: 'ისეთი დაავადებაა, როდესაც თვალები არა სიმეტრიულად, სხვა და სხვა მიმართულებით იყურებიან, რაც ართულებს მზერის ფოკუსირებას საგანზე. თუ რომელიმე თვალი ცუდად ხედავს, თავის ტვინი ვერ ღებულობს ინფორმაციას და ვითარდება „ზარმაცი თვალი" (ამბლიოპია). სიელმის დროს ქირურგიული ოპერაცია მხოლოდ კოსმეტიკური დეფექტის აღმოსაფხვრელად არის საჭირო და მიზნად არ ისახავს მხედველობის აღდგენას. შედეგად, დროთა განმავლობაში თვალი კვლავ იწყებს გადახრას. სიელმე 25 ტიპისაა და ყველა მათგანს აქვს საკუთარი კლინიკური მახასიათებლები და წარმოშობის ასაკი.',
    disease_2_successRate: 'მაგოთერაპიით მკურნალობისას 98% შემთხვეხაში ხდება ბინოკულარული და ცენტრალური მხედველობის აღდგენა, რაც ავტომატურად იწვევს თვალის სიმეტრიულ დგომას.',
    disease_3_title: 'ასტიგმატიზმი',
    disease_3_description: 'გავრცელებული დაავადებაა, როდესაც ახლოს და შორს მანძილზე ხედვისას, საგნები ერთნაირად წაშლილი და არა მკვეთრია. ბავშვებში ამ დაავადების საწყის ეტაპზე გამოვლინება ხშირად მშობლებს შეუძლიათ. ასტიგმატიზმს არ გააჩნია სპეციფიური სიმპტომები, ბავშვები კი ვერ ხვდებიან, რომ ცუდად ხედავენ და შესაბამისად ჩივილებიც არ აქვთ. ასტიგმატიზმის ადრეულ ეტაპზე გამოვლენა, მხოლოდ ბავშვზე დაკვირვებით არის შესაძლებელი, რაც მომავალში ბევრ პრობლემას აარიდებს თქვენს პატარას.',
    disease_3_successRate: 'ასტიგმატიზმის მკურნალობა ქირურგიისა და მედიკამენტების გარეშე, ფიზიოლოგიური მეთოდით მაგოთერაპია 98% შემთხვეხაში აღადგენს მხედველობას.',
    disease_4_title: 'გლაუკომა',
    disease_4_description: 'თვალის ვერაგ დაავადებათა ჯგუფს მიეკუთვნება. ამ დაავადების დროს ხდება მხედველობის ნერვის პროგრესირებადი ატროფია და მხედველობის დაკარგვა. მხედველობის ნერვის მეშვეობით ხდება ვიზუალური ინფორმაციის გადაცემა თვალიდან ტვინში. გავრცელებული აზრი, რომ თვალშიდა წნევის მოწესრიგება დაავადების პროგრესირებას აჩერებს — არასწორია. არსებული მკურნალობის მეთოდები — წვეთები, ქირურგიული ოპერაცია და ლაზერული მკურნალობა — მიმართულია მხოლოდ თვალშიდა წნევის მოსაწესრიგებლად. მაგრამ ნორმალური და დაბალი თვალშიდა წნევის დროსაც ხდება მხედველობის ნერვის და თავის ტვინის შესაბამისი ნაწილების ატროფიის პროგრესირება, რაც ხშირად სიბრმავით მთავრდება.',
    disease_4_successRate: 'მაგოთერაპია აღადგენს მხედველობას, აჩერებს ან ანელებს დაავადების პროგრესირებას 88% შემთხვეხაში, კონკრეტული ორგანიზმის რესურსიდან გამომდინარე, ქირურგიისა და მედიკამენტების გარეშე.',
    disease_5_title: 'შორსმხედველობა (ჰიპერმეტროპია)',
    disease_5_description: 'თვალის რეფრაქციულ მანკს მიეკუთვნება. მხედველობის დაქვეითებაა, როდესაც საგნების გარჩევა ახლო მანძილზე (20–30 სმ) თვალიდან გართულებულია. თუ შორსმხედველობა მაღალი ხარისხისაა, მხედველობა ისევე როგორც ახლო მანძილზე, შორსაც გართულებულია. ამ დაავადების დროს, აკომოდაციის კუნთი გამუდმებით დაძაბულია, რაც იწვევს თავის ტკივილს და მხედველობით გადაღლას. მცირე ასაკის ბავშვებისათვის სუსტი ხარისხის შორსმხედველობა ნორმაა, მაგრამ თუ შორსმხედველობის ხარისხი მაღალია და არ იქნა ნამკურნალები, ვითარდება ისეთი გართულებები, როგორიც არის „ზარმაცი თვალი" (ამბლიოპია) და სიელმე.',
    disease_5_successRate: 'მაგოთერაპიით მკურნალობისას, მიუხედავად პაციენტის ასაკისა და დაავადების ხანგრძლივობისა, 98% შემთხვეხაში ხდება მხედველობის აღდგენა რისკის და გართულებების გარეშე.',
    disease_6_title: 'ახლომხედველობა (მიოპია)',
    disease_6_description: 'თვალის რეფრაქციულ მანკებს მიეკუთვნება. მიოპიის დროს, ადამიანი კარგად ხედავს ახლოს და უჭირს შორს ხედვა. მიოპია შესაძლოა იყოს, როგორც თანდაყოლილი, ისე შეძენილი ნებისმიერ ასაკში. ახლომხედველ ადამიანებს ახასიათებს შორს ხედვისას თვალის მოჭუტვა, რაც მშობლებისთვის ბავშვის ექიმთან წაყვანის მიზეზი უნდა გახდეს. დააკვირდით პატარას, რადგან ბავშვა არ იცის, როგორ უნდა ხედავდეს ნორმის ფარგლებში.',
    disease_6_successRate: 'მაგოთერაპიით, ქირურგიის გარეშე, ბუნებრივად აღვადგენთ მხედველობას კანის ზემოდან განთავსებული აპარატურით 98% შემთხვეხაში. პროცედურები უვნებელი და უმტკივნეულოა.',
    disease_7_title: 'ნისტაგმი',
    disease_7_description: 'თვალების უნებლიე რხევითი მოძრაობაა, როდესაც თვალი ხშირად ჰორიზონტალური და იშვიათად ვერტიკალური ან რატატორული (წრიული) მიმართულებით მოძრაობს. მოძრაობის ციკლი შედგება უნებლიე თვალის გადახრისგან შემდგომი ნახტომისებური რე-ფიქსაციული მოძრაობამდე. ნისტაგმის დროს შეუძლებელია ერთ საგანზე მზერის ფიქსაცია, რაც აიძულებს ადამიანს უჩვეულოდ დახაროს თავი საგნის გასარჩევად. ნისტაგმს ხშირად თან სდევს დაქვეითებული მხედველობა — ბადურის დისტროფია, სიელმე, ასტიგმატიზმი, შორსმხედველობა, მხედველობის ნერვის ატროფია და სხვა.',
    disease_7_successRate: 'მცნება „ნისტაგმი არ ინკურნება" — წარსულს ჩაბარდა! ნისტაგმის არაქირურგიული, უმტკივნეულო მკურნალობა ჩვენთან რეალობაა! ფიზიოლოგიური მეთოდი მაგოთერაპია 87% შემთხვეხაში აღადგენს მხედველობას და ამცირებს ან აჩერებს ნისტაგმს.',
    diseases: [
      {
        title: 'ამბლიოპია (ზარმაცი თვალი)',
        description: 'ვითარდება მხედველობის სიმახვილის დაქვეითების შემთხვევაში ერთ ან ორივე თვალზე. დაავადების დროს, ბადურაზე, მხედველობის ნერვის და თავის ტვინის შესაბამის ნაწილებში, აღინიშნება ფუნქციონალური დარღვევები, ხილული ცვლილებების გარეშე. სუსტი მხედველობის გამო, თვალი ვერ მონაწილეობს მხედველობის პროცესში. მხედველობის ანალიზატორი „გადაჩვეული" ინფორმაციის გადამუშვას, რადგან ბადურაზე მოხვედრილი შუქის სხივი ვერ აღწევს ტვინამდე. ამბლიოპია ხშირად ბავშვობაში ვითარდება, თუმცა შესაძლოა მოზრდილებშიც გამოვლინდეს.',
        successRate: 'ამბლიოპიის მკურნალობა მაგოთერაპიით 97% შემთხვეხაში აღადგენს მხედველობას პაციენტის ასაკის მიუხედავად.',
      },
      {
        title: 'პიგმენტური რეტინიტი',
        description: 'მიეკუთვნება ბადურის დისტროფიების ჯგუფს. ახასიათებს ბადურა გარსზე ფოტორეცეპტორების ფუნქციის დაქვეითება (აპოპტოზი), ბადურის უჯრედები, რომელიც განაპირობებენ მხედველობას შებინდებისას (ჩხირები), თანდათანობით კარგავენ ფუნქციურ თვისებებს, ხდება მათი გადაგვარება, რის გამოც მხედველობა შებინდებისას უარესდება. ბადურა გარსის და მხედველობის ანალიზატორის უჯრედების დისფუნქცია, არის სიბრმავის გამომწვევი ძირითადი მიზეზი.',
        successRate: 'მაგოთერაპიით მკურნალობისას მხედველობის აღდგენა ხდება 90% შემთხვეხაში, კონკრეტული ორგანიზმის რესურსზე დაყრდნობით.',
      },
      {
        title: 'სიელმე',
        description: 'ისეთი დაავადებაა, როდესაც თვალები არა სიმეტრიულად, სხვა და სხვა მიმართულებით იყურებიან, რაც ართულებს მზერის ფოკუსირებას საგანზე. თუ რომელიმე თვალი ცუდად ხედავს, თავის ტვინი ვერ ღებულობს ინფორმაციას და ვითარდება „ზარმაცი თვალი" (ამბლიოპია). სიელმის დროს ქირურგიული ოპერაცია მხოლოდ კოსმეტიკური დეფექტის აღმოსაფხვრელად არის საჭირო და მიზნად არ ისახავს მხედველობის აღდგენას. შედეგად, დროთა განმავლობაში თვალი კვლავ იწყებს გადახრას. სიელმე 25 ტიპისაა და ყველა მათგანს აქვს საკუთარი კლინიკური მახასიათებლები და წარმოშობის ასაკი.',
        successRate: 'მაგოთერაპიით მკურნალობისას 98% შემთხვეხაში ხდება ბინოკულარული და ცენტრალური მხედველობის აღდგენა, რაც ავტომატურად იწვევს თვალის სიმეტრიულ დგომას.',
      },
      {
        title: 'ასტიგმატიზმი',
        description: 'გავრცელებული დაავადებაა, როდესაც ახლოს და შორს მანძილზე ხედვისას, საგნები ერთნაირად წაშლილი და არა მკვეთრია. ბავშვებში ამ დაავადების საწყის ეტაპზე გამოვლინება ხშირად მშობლებს შეუძლიათ. ასტიგმატიზმს არ გააჩნია სპეციფიური სიმპტომები, ბავშვები კი ვერ ხვდებიან, რომ ცუდად ხედავენ და შესაბამისად ჩივილებიც არ აქვთ. ასტიგმატიზმის ადრეულ ეტაპზე გამოვლენა, მხოლოდ ბავშვზე დაკვირვებით არის შესაძლებელი, რაც მომავალში ბევრ პრობლემას აარიდებს თქვენს პატარას.',
        successRate: 'ასტიგმატიზმის მკურნალობა ქირურგიისა და მედიკამენტების გარეშე, ფიზიოლოგიური მეთოდით მაგოთერაპია 98% შემთხვეხაში აღადგენს მხედველობას.',
      },
      {
        title: 'გლაუკომა',
        description: 'თვალის ვერაგ დაავადებათა ჯგუფს მიეკუთვნება. ამ დაავადების დროს ხდება მხედველობის ნერვის პროგრესირებადი ატროფია და მხედველობის დაკარგვა. მხედველობის ნერვის მეშვეობით ხდება ვიზუალური ინფორმაციის გადაცემა თვალიდან ტვინში. გავრცელებული აზრი, რომ თვალშიდა წნევის მოწესრიგება დაავადების პროგრესირებას აჩერებს — არასწორია. არსებული მკურნალობის მეთოდები — წვეთები, ქირურგიული ოპერაცია და ლაზერული მკურნალობა — მიმართულია მხოლოდ თვალშიდა წნევის მოსაწესრიგებლად. მაგრამ ნორმალური და დაბალი თვალშიდა წნევის დროსაც ხდება მხედველობის ნერვის და თავის ტვინის შესაბამისი ნაწილების ატროფიის პროგრესირება, რაც ხშირად სიბრმავით მთავრდება.',
        successRate: 'მაგოთერაპია აღადგენს მხედველობას, აჩერებს ან ანელებს დაავადების პროგრესირებას 88% შემთხვეხაში, კონკრეტული ორგანიზმის რესურსიდან გამომდინარე, ქირურგიისა და მედიკამენტების გარეშე.',
      },
      {
        title: 'შორსმხედველობა (ჰიპერმეტროპია)',
        description: 'თვალის რეფრაქციულ მანკს მიეკუთვნება. მხედველობის დაქვეითებაა, როდესაც საგნების გარჩევა ახლო მანძილზე (20–30 სმ) თვალიდან გართულებულია. თუ შორსმხედველობა მაღალი ხარისხისაა, მხედველობა ისევე როგორც ახლო მანძილზე, შორსაც გართულებულია. ამ დაავადების დროს, აკომოდაციის კუნთი გამუდმებით დაძაბულია, რაც იწვევს თავის ტკივილს და მხედველობით გადაღლას. მცირე ასაკის ბავშვებისათვის სუსტი ხარისხის შორსმხედველობა ნორმაა, მაგრამ თუ შორსმხედველობის ხარისხი მაღალია და არ იქნა ნამკურნალები, ვითარდება ისეთი გართულებები, როგორიც არის „ზარმაცი თვალი" (ამბლიოპია) და სიელმე.',
        successRate: 'მაგოთერაპიით მკურნალობისას, მიუხედავად პაციენტის ასაკისა და დაავადების ხანგრძლივობისა, 98% შემთხვეხაში ხდება მხედველობის აღდგენა რისკის და გართულებების გარეშე.',
      },
      {
        title: 'ახლომხედველობა (მიოპია)',
        description: 'თვალის რეფრაქციულ მანკებს მიეკუთვნება. მიოპიის დროს, ადამიანი კარგად ხედავს ახლოს და უჭირს შორს ხედვა. მიოპია შესაძლოა იყოს, როგორც თანდაყოლილი, ისე შეძენილი ნებისმიერ ასაკში. ახლომხედველ ადამიანებს ახასიათებს შორს ხედვისას თვალის მოჭუტვა, რაც მშობლებისთვის ბავშვის ექიმთან წაყვანის მიზეზი უნდა გახდეს. დააკვირდით პატარას, რადგან ბავშვა არ იცის, როგორ უნდა ხედავდეს ნორმის ფარგლებში.',
        successRate: 'მაგოთერაპიით, ქირურგიის გარეშე, ბუნებრივად აღვადგენთ მხედველობას კანის ზემოდან განთავსებული აპარატურით 98% შემთხვეხაში. პროცედურები უვნებელი და უმტკივნეულოა.',
      },
      {
        title: 'ნისტაგმი',
        description: 'თვალების უნებლიე რხევითი მოძრაობაა, როდესაც თვალი ხშირად ჰორიზონტალური და იშვიათად ვერტიკალური ან რატატორული (წრიული) მიმართულებით მოძრაობს. მოძრაობის ციკლი შედგება უნებლიე თვალის გადახრისგან შემდგომი ნახტომისებური რე-ფიქსაციული მოძრაობამდე. ნისტაგმის დროს შეუძლებელია ერთ საგანზე მზერის ფიქსაცია, რაც აიძულებს ადამიანს უჩვეულოდ დახაროს თავი საგნის გასარჩევად. ნისტაგმს ხშირად თან სდევს დაქვეითებული მხედველობა — ბადურის დისტროფია, სიელმე, ასტიგმატიზმი, შორსმხედველობა, მხედველობის ნერვის ატროფია და სხვა.',
        successRate: 'მცნება „ნისტაგმი არ ინკურნება" — წარსულს ჩაბარდა! ნისტაგმის არაქირურგიული, უმტკივნეულო მკურნალობა ჩვენთან რეალობაა! ფიზიოლოგიური მეთოდი მაგოთერაპია 87% შემთხვეხაში აღადგენს მხედველობას და ამცირებს ან აჩერებს ნისტაგმს.',
      },
    ],
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    pageTitle: 'Results — General',
    magoActivates: 'Magotherapy, with innovative apparatus, activates cellular metabolism,',
    restoresResources: 'restores the body\'s resources and function',
    restoresCells: 'and rejuvenates cells on the retina.',
    visionRestores: 'As a result, vision is restored.',
    clinicallyProven: 'Clinically proven — stable results — without surgery or medication.',
    contactUs: 'Contact Us',
    seeMoreMago: 'See more → Magotherapy',
    visionPossible: 'Vision restoration with Magotherapy is possible!',
    clinicDescription: 'Eye Clinic "New Technologies-MaGo", with the exclusive Magotherapy method, restores vision both after unsuccessful operations and in various eye conditions, even in diseases you believe are incurable.',
    impossiblePossible: 'Even the impossible is possible for us!',
    seeMore: 'See more →',
    disease_0_title: 'Amblyopia (Lazy Eye)',
    disease_0_description: 'Develops in case of reduced visual acuity in one or both eyes. The condition involves functional disturbances in the retina, optic nerve, and corresponding brain areas without visible changes. Due to poor vision, the eye cannot participate in the vision process. The visual analyzer becomes "accustomed" to not processing information because the light ray reaching the retina cannot reach the brain. Amblyopia often develops in childhood but may also appear in adults.',
    disease_0_successRate: 'Amblyopia treatment with Magotherapy restores vision in 97% of cases, regardless of the patient\'s age.',
    disease_1_title: 'Pigmentary Retinitis',
    disease_1_description: 'Belongs to the group of retinal dystrophies. Characterized by decreased photoreceptor function (apoptosis) on the retinal membrane. Retinal cells that ensure twilight vision (rods) gradually lose their functional properties and degenerate, causing vision to worsen at dusk. Dysfunction of the retinal membrane and visual analyzer cells is the primary cause of blindness.',
    disease_1_successRate: 'With Magotherapy treatment, vision restoration occurs in 90% of cases, based on the specific organism\'s resources.',
    disease_2_title: 'Strabismus',
    disease_2_description: 'A condition where the eyes look in different directions rather than symmetrically, making it difficult to focus on objects. If one eye sees poorly, the brain cannot receive information and a "lazy eye" (amblyopia) develops. Surgery for strabismus is only needed to eliminate the cosmetic defect and does not aim to restore vision. As a result, the eye eventually begins to deviate again. There are 25 types of strabismus, each with its own clinical characteristics and age of onset.',
    disease_2_successRate: 'With Magotherapy treatment, in 98% of cases, binocular and central vision is restored, which automatically results in the eye resuming symmetrical position.',
    disease_3_title: 'Astigmatism',
    disease_3_description: 'A common condition where objects appear equally blurred both near and far. Parents can often detect the initial stage of this condition in children. Astigmatism has no specific symptoms, and children don\'t realize they see poorly and therefore have no complaints. Early detection of astigmatism is only possible through observation of the child, which will save your child from many problems in the future.',
    disease_3_successRate: 'Astigmatism treatment without surgery and medication, with the physiological Magotherapy method, restores vision in 98% of cases.',
    disease_4_title: 'Glaucoma',
    disease_4_description: 'Belongs to the group of treacherous eye diseases. This disease involves progressive atrophy of the optic nerve and loss of vision. The optic nerve transmits visual information from the eye to the brain. The common belief that normalizing intraocular pressure stops disease progression is incorrect. Existing treatment methods — drops, surgery, and laser treatment — are aimed only at normalizing intraocular pressure. But even with normal and low intraocular pressure, progressive atrophy of the optic nerve and corresponding brain areas continues, often ending in blindness.',
    disease_4_successRate: 'Magotherapy restores vision, stops or slows disease progression in 88% of cases, based on the specific organism\'s resources, without surgery or medication.',
    disease_5_title: 'Farsightedness (Hypermetropia)',
    disease_5_description: 'A refractive defect of the eye. A vision impairment where distinguishing objects close to the eye (20–30 cm) is difficult. If farsightedness is of high degree, vision is also difficult at a distance. The accommodation muscle is constantly tense, causing headaches and visual fatigue. Mild farsightedness is normal for young children, but if the degree is high and untreated, complications such as "lazy eye" (amblyopia) and strabismus develop.',
    disease_5_successRate: 'With Magotherapy treatment, regardless of the patient\'s age and disease duration, vision is restored in 98% of cases without risk and complications.',
    disease_6_title: 'Nearsightedness (Myopia)',
    disease_6_description: 'A refractive defect of the eye. In myopia, a person sees well up close but has difficulty seeing far away. Myopia can be congenital or acquired at any age. Nearsighted people characteristically squint when looking at distant objects, which should prompt parents to take the child to a doctor. Watch your child closely, as the child does not know how they should see within the normal range.',
    disease_6_successRate: 'With Magotherapy, without surgery, we naturally restore vision using apparatus placed on the skin in 98% of cases. The procedures are safe and painless.',
    disease_7_title: 'Nystagmus',
    disease_7_description: 'Involuntary oscillatory movement of the eyes, where the eyes frequently move in a horizontal and rarely in a vertical or rotatory (circular) direction. The movement cycle consists of involuntary eye deviation followed by a rapid re-fixation movement. In nystagmus, it is impossible to fix gaze on a single object, forcing the person to tilt their head unusually to see. Nystagmus is often accompanied by reduced vision — retinal dystrophy, strabismus, astigmatism, farsightedness, optic nerve atrophy, and others.',
    disease_7_successRate: 'The notion that "nystagmus is incurable" is a thing of the past! Non-surgical, painless treatment of nystagmus is a reality here! The physiological Magotherapy method restores vision and reduces or stops nystagmus in 87% of cases.',
    diseases: [
      {
        title: 'Amblyopia (Lazy Eye)',
        description: 'Develops in case of reduced visual acuity in one or both eyes. The condition involves functional disturbances in the retina, optic nerve, and corresponding brain areas without visible changes. Due to poor vision, the eye cannot participate in the vision process. The visual analyzer becomes "accustomed" to not processing information because the light ray reaching the retina cannot reach the brain. Amblyopia often develops in childhood but may also appear in adults.',
        successRate: 'Amblyopia treatment with Magotherapy restores vision in 97% of cases, regardless of the patient\'s age.',
      },
      {
        title: 'Pigmentary Retinitis',
        description: 'Belongs to the group of retinal dystrophies. Characterized by decreased photoreceptor function (apoptosis) on the retinal membrane. Retinal cells that ensure twilight vision (rods) gradually lose their functional properties and degenerate, causing vision to worsen at dusk. Dysfunction of the retinal membrane and visual analyzer cells is the primary cause of blindness.',
        successRate: 'With Magotherapy treatment, vision restoration occurs in 90% of cases, based on the specific organism\'s resources.',
      },
      {
        title: 'Strabismus',
        description: 'A condition where the eyes look in different directions rather than symmetrically, making it difficult to focus on objects. If one eye sees poorly, the brain cannot receive information and a "lazy eye" (amblyopia) develops. Surgery for strabismus is only needed to eliminate the cosmetic defect and does not aim to restore vision. As a result, the eye eventually begins to deviate again. There are 25 types of strabismus, each with its own clinical characteristics and age of onset.',
        successRate: 'With Magotherapy treatment, in 98% of cases, binocular and central vision is restored, which automatically results in the eye resuming symmetrical position.',
      },
      {
        title: 'Astigmatism',
        description: 'A common condition where objects appear equally blurred both near and far. Parents can often detect the initial stage of this condition in children. Astigmatism has no specific symptoms, and children don\'t realize they see poorly and therefore have no complaints. Early detection of astigmatism is only possible through observation of the child, which will save your child from many problems in the future.',
        successRate: 'Astigmatism treatment without surgery and medication, with the physiological Magotherapy method, restores vision in 98% of cases.',
      },
      {
        title: 'Glaucoma',
        description: 'Belongs to the group of treacherous eye diseases. This disease involves progressive atrophy of the optic nerve and loss of vision. The optic nerve transmits visual information from the eye to the brain. The common belief that normalizing intraocular pressure stops disease progression is incorrect. Existing treatment methods — drops, surgery, and laser treatment — are aimed only at normalizing intraocular pressure. But even with normal and low intraocular pressure, progressive atrophy of the optic nerve and corresponding brain areas continues, often ending in blindness.',
        successRate: 'Magotherapy restores vision, stops or slows disease progression in 88% of cases, based on the specific organism\'s resources, without surgery or medication.',
      },
      {
        title: 'Farsightedness (Hypermetropia)',
        description: 'A refractive defect of the eye. A vision impairment where distinguishing objects close to the eye (20–30 cm) is difficult. If farsightedness is of high degree, vision is also difficult at a distance. The accommodation muscle is constantly tense, causing headaches and visual fatigue. Mild farsightedness is normal for young children, but if the degree is high and untreated, complications such as "lazy eye" (amblyopia) and strabismus develop.',
        successRate: 'With Magotherapy treatment, regardless of the patient\'s age and disease duration, vision is restored in 98% of cases without risk and complications.',
      },
      {
        title: 'Nearsightedness (Myopia)',
        description: 'A refractive defect of the eye. In myopia, a person sees well up close but has difficulty seeing far away. Myopia can be congenital or acquired at any age. Nearsighted people characteristically squint when looking at distant objects, which should prompt parents to take the child to a doctor. Watch your child closely, as the child does not know how they should see within the normal range.',
        successRate: 'With Magotherapy, without surgery, we naturally restore vision using apparatus placed on the skin in 98% of cases. The procedures are safe and painless.',
      },
      {
        title: 'Nystagmus',
        description: 'Involuntary oscillatory movement of the eyes, where the eyes frequently move in a horizontal and rarely in a vertical or rotatory (circular) direction. The movement cycle consists of involuntary eye deviation followed by a rapid re-fixation movement. In nystagmus, it is impossible to fix gaze on a single object, forcing the person to tilt their head unusually to see. Nystagmus is often accompanied by reduced vision — retinal dystrophy, strabismus, astigmatism, farsightedness, optic nerve atrophy, and others.',
        successRate: 'The notion that "nystagmus is incurable" is a thing of the past! Non-surgical, painless treatment of nystagmus is a reality here! The physiological Magotherapy method restores vision and reduces or stops nystagmus in 87% of cases.',
      },
    ],
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    pageTitle: 'Результаты — Общие',
    magoActivates: 'Маготерапия с помощью инновационной аппаратуры активирует клеточный метаболизм,',
    restoresResources: 'восстанавливает ресурсы и функцию организма',
    restoresCells: 'и возвращает клетки на сетчатке.',
    visionRestores: 'В результате восстанавливается зрение.',
    clinicallyProven: 'Клинически подтверждено — стабильный результат — без хирургии и медикаментов.',
    contactUs: 'Свяжитесь с нами',
    seeMoreMago: 'Подробнее → Маготерапия',
    visionPossible: 'Восстановление зрения Маготерапией возможно!',
    clinicDescription: 'Глазная клиника "Новые Технологии-MaGo", с эксклюзивным методом Маготерапия восстанавливает зрение как после безуспешных операций, так и при различных глазных заболеваниях, даже при болезнях, которые, по вашему мнению, неизлечимы.',
    impossiblePossible: 'Для нас невозможное — возможно!',
    seeMore: 'Подробнее →',
    disease_0_title: 'Амблиопия (Ленивый глаз)',
    disease_0_description: 'Развивается при снижении остроты зрения одного или обоих глаз. При заболевании на сетчатке, в зрительном нерве и соответствующих частях головного мозга наблюдаются функциональные нарушения без видимых изменений. Из-за слабого зрения глаз не может участвовать в зрительном процессе. Зрительный анализатор "отвыкает" от обработки информации, так как световой луч, попавший на сетчатку, не достигает мозга. Амблиопия часто развивается в детстве, но может проявиться и у взрослых.',
    disease_0_successRate: 'Лечение амблиопии Маготерапией восстанавливает зрение в 88% случаев, независимо от возраста пациента.',
    disease_1_title: 'Пигментный ретинит',
    disease_1_description: 'Относится к группе дистрофий сетчатки. Характеризуется снижением функции фоторецепторов (апоптозом) на мембране сетчатки. Клетки сетчатки, обеспечивающие сумеречное зрение (палочки), постепенно теряют функциональные свойства и дегенерируют, из-за чего зрение в сумерках ухудшается. Дисфункция мембраны сетчатки и клеток зрительного анализатора является основной причиной слепоты.',
    disease_1_successRate: 'При лечении Маготерапией восстановление зрения происходит в 79% случаев, на основе ресурсов конкретного организма.',
    disease_2_title: 'Косоглазие',
    disease_2_description: 'Заболевание, при котором глаза смотрят не симметрично, а в разные стороны, что затрудняет фокусировку взгляда на предмете. Если один глаз видит плохо, мозг не получает информацию и развивается "ленивый глаз" (амблиопия). Хирургическая операция при косоглазии нужна только для устранения косметического дефекта и не направлена на восстановление зрения. В результате со временем глаз снова начинает отклоняться. Существует 25 типов косоглазия, каждый с собственными клиническими характеристиками и возрастом появления.',
    disease_2_successRate: 'При лечении Маготерапией в 93% случаев восстанавливается бинокулярное и центральное зрение, что автоматически приводит к симметричному положению глаза.',
    disease_3_title: 'Астигматизм',
    disease_3_description: 'Распространённое заболевание, при котором предметы одинаково размыты как вблизи, так и вдали. Родители часто могут выявить начальную стадию этого заболевания у детей. Астигматизм не имеет специфических симптомов, а дети не замечают, что плохо видят, и, соответственно, жалоб нет. Раннее выявление астигматизма возможно только путём наблюдения за ребёнком, что избавит вашего малыша от многих проблем в будущем.',
    disease_3_successRate: 'Лечение астигматизма без хирургии и медикаментов физиологическим методом Маготерапия восстанавливает зрение в 93% случаев.',
    disease_4_title: 'Глаукома',
    disease_4_description: 'Относится к группе коварных глазных заболеваний. При этом заболевании происходит прогрессирующая атрофия зрительного нерва и потеря зрения. Через зрительный нерв осуществляется передача визуальной информации от глаза к мозгу. Распространённое мнение о том, что нормализация внутриглазного давления останавливает прогрессирование болезни — неверно. Существующие методы лечения — капли, хирургическая операция и лазерное лечение — направлены только на нормализацию внутриглазного давления. Но даже при нормальном и низком внутриглазном давлении продолжается прогрессирующая атрофия зрительного нерва и соответствующих частей головного мозга, что нередко заканчивается слепотой.',
    disease_4_successRate: 'Маготерапия восстанавливает зрение, останавливает или замедляет прогрессирование болезни в 74% случаев, исходя из ресурсов конкретного организма, без хирургии и медикаментов.',
    disease_5_title: 'Дальнозоркость (Гиперметропия)',
    disease_5_description: 'Относится к рефракционным дефектам глаза. Снижение зрения, при котором различение предметов вблизи (20–30 см) затруднено. Если дальнозоркость высокой степени, зрение затруднено и вдаль. Мышца аккомодации постоянно напряжена, что вызывает головные боли и зрительную усталость. Для детей раннего возраста слабая дальнозоркость является нормой, но если степень высока и не лечится, развиваются такие осложнения, как "ленивый глаз" (амблиопия) и косоглазие.',
    disease_5_successRate: 'При лечении Маготерапией, независимо от возраста пациента и длительности болезни, в 92% случаев происходит восстановление зрения без риска и осложнений.',
    disease_6_title: 'Близорукость (Миопия)',
    disease_6_description: 'Относится к рефракционным дефектам глаза. При миопии человек хорошо видит вблизи, но затрудняется смотреть вдаль. Миопия может быть как врождённой, так и приобретённой в любом возрасте. Близоруким людям свойственно прищуривать глаза при взгляде вдаль, что должно стать поводом для родителей отвести ребёнка к врачу. Следите за малышом, так как ребёнок не знает, как должен видеть в пределах нормы.',
    disease_6_successRate: 'Маготерапией, без хирургии, мы естественным образом восстанавливаем зрение с помощью аппаратуры, размещённой на коже, в 93% случаев. Процедуры безвредны и безболезненны.',
    disease_7_title: 'Нистагм',
    disease_7_description: 'Непроизвольное колебательное движение глаз, при котором глаза часто движутся горизонтально и редко — вертикально или ротаторно (кругово). Цикл движения состоит из непроизвольного отклонения глаза с последующим быстрым движением рефиксации. При нистагме невозможно зафиксировать взгляд на одном предмете, что вынуждает человека необычно наклонять голову для различения предмета. Нистагм часто сопровождается снижением зрения — дистрофией сетчатки, косоглазием, астигматизмом, дальнозоркостью, атрофией зрительного нерва и другими.',
    disease_7_successRate: 'Понятие "нистагм не лечится" — ушло в прошлое! Нехирургическое, безболезненное лечение нистагма у нас — реальность! Физиологический метод Маготерапия восстанавливает зрение и уменьшает или останавливает нистагм в 67% случаев.',
    diseases: [
      {
        title: 'Амблиопия (Ленивый глаз)',
        description: 'Развивается при снижении остроты зрения одного или обоих глаз. При заболевании на сетчатке, в зрительном нерве и соответствующих частях головного мозга наблюдаются функциональные нарушения без видимых изменений. Из-за слабого зрения глаз не может участвовать в зрительном процессе. Зрительный анализатор "отвыкает" от обработки информации, так как световой луч, попавший на сетчатку, не достигает мозга. Амблиопия часто развивается в детстве, но может проявиться и у взрослых.',
        successRate: 'Лечение амблиопии Маготерапией восстанавливает зрение в 88% случаев, независимо от возраста пациента.',
      },
      {
        title: 'Пигментный ретинит',
        description: 'Относится к группе дистрофий сетчатки. Характеризуется снижением функции фоторецепторов (апоптозом) на мембране сетчатки. Клетки сетчатки, обеспечивающие сумеречное зрение (палочки), постепенно теряют функциональные свойства и дегенерируют, из-за чего зрение в сумерках ухудшается. Дисфункция мембраны сетчатки и клеток зрительного анализатора является основной причиной слепоты.',
        successRate: 'При лечении Маготерапией восстановление зрения происходит в 79% случаев, на основе ресурсов конкретного организма.',
      },
      {
        title: 'Косоглазие',
        description: 'Заболевание, при котором глаза смотрят не симметрично, а в разные стороны, что затрудняет фокусировку взгляда на предмете. Если один глаз видит плохо, мозг не получает информацию и развивается "ленивый глаз" (амблиопия). Хирургическая операция при косоглазии нужна только для устранения косметического дефекта и не направлена на восстановление зрения. В результате со временем глаз снова начинает отклоняться. Существует 25 типов косоглазия, каждый с собственными клиническими характеристиками и возрастом появления.',
        successRate: 'При лечении Маготерапией в 93% случаев восстанавливается бинокулярное и центральное зрение, что автоматически приводит к симметричному положению глаза.',
      },
      {
        title: 'Астигматизм',
        description: 'Распространённое заболевание, при котором предметы одинаково размыты как вблизи, так и вдали. Родители часто могут выявить начальную стадию этого заболевания у детей. Астигматизм не имеет специфических симптомов, а дети не замечают, что плохо видят, и, соответственно, жалоб нет. Раннее выявление астигматизма возможно только путём наблюдения за ребёнком, что избавит вашего малыша от многих проблем в будущем.',
        successRate: 'Лечение астигматизма без хирургии и медикаментов физиологическим методом Маготерапия восстанавливает зрение в 93% случаев.',
      },
      {
        title: 'Глаукома',
        description: 'Относится к группе коварных глазных заболеваний. При этом заболевании происходит прогрессирующая атрофия зрительного нерва и потеря зрения. Через зрительный нерв осуществляется передача визуальной информации от глаза к мозгу. Распространённое мнение о том, что нормализация внутриглазного давления останавливает прогрессирование болезни — неверно. Существующие методы лечения — капли, хирургическая операция и лазерное лечение — направлены только на нормализацию внутриглазного давления. Но даже при нормальном и низком внутриглазном давлении продолжается прогрессирующая атрофия зрительного нерва и соответствующих частей головного мозга, что нередко заканчивается слепотой.',
        successRate: 'Маготерапия восстанавливает зрение, останавливает или замедляет прогрессирование болезни в 74% случаев, исходя из ресурсов конкретного организма, без хирургии и медикаментов.',
      },
      {
        title: 'Дальнозоркость (Гиперметропия)',
        description: 'Относится к рефракционным дефектам глаза. Снижение зрения, при котором различение предметов вблизи (20–30 см) затруднено. Если дальнозоркость высокой степени, зрение затруднено и вдаль. Мышца аккомодации постоянно напряжена, что вызывает головные боли и зрительную усталость. Для детей раннего возраста слабая дальнозоркость является нормой, но если степень высока и не лечится, развиваются такие осложнения, как "ленивый глаз" (амблиопия) и косоглазие.',
        successRate: 'При лечении Маготерапией, независимо от возраста пациента и длительности болезни, в 92% случаев происходит восстановление зрения без риска и осложнений.',
      },
      {
        title: 'Близорукость (Миопия)',
        description: 'Относится к рефракционным дефектам глаза. При миопии человек хорошо видит вблизи, но затрудняется смотреть вдаль. Миопия может быть как врождённой, так и приобретённой в любом возрасте. Близоруким людям свойственно прищуривать глаза при взгляде вдаль, что должно стать поводом для родителей отвести ребёнка к врачу. Следите за малышом, так как ребёнок не знает, как должен видеть в пределах нормы.',
        successRate: 'Маготерапией, без хирургии, мы естественным образом восстанавливаем зрение с помощью аппаратуры, размещённой на коже, в 93% случаев. Процедуры безвредны и безболезненны.',
      },
      {
        title: 'Нистагм',
        description: 'Непроизвольное колебательное движение глаз, при котором глаза часто движутся горизонтально и редко — вертикально или ротаторно (кругово). Цикл движения состоит из непроизвольного отклонения глаза с последующим быстрым движением рефиксации. При нистагме невозможно зафиксировать взгляд на одном предмете, что вынуждает человека необычно наклонять голову для различения предмета. Нистагм часто сопровождается снижением зрения — дистрофией сетчатки, косоглазием, астигматизмом, дальнозоркостью, атрофией зрительного нерва и другими.',
        successRate: 'Понятие "нистагм не лечится" — ушло в прошлое! Нехирургическое, безболезненное лечение нистагма у нас — реальность! Физиологический метод Маготерапия восстанавливает зрение и уменьшает или останавливает нистагм в 67% случаев.',
      },
    ],
  },
};

export function useZogadiTranslations(language: Language) {
  return zogadiTranslations[language];
}
