import { Language } from '../contexts/LanguageContext';

const pigmenturetiniteTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    pageTitle1: 'ბადურის დისტროფიები.',
    pageTitle2: 'პიგმენტური რეტინიტი.',
    heroText1: 'მაგოთერაპია დაგეხმარებათ მხედველობის აღდგენაში',
    heroText2: 'თქვენი ორგანიზმის რესურსის აღორძინების ხარჯზე.',
    heroText3: 'ეფექტური და უსაფრთხო მკურნალობა მაგოთერაპიით',
    heroText4: 'ჩვენთან რეალობაა!',
    resultInOneHour: 'შედეგი ტესტირებიდან ერთ საათში ------- გართულების და რისკის გარეშე ---------- სტაბილური შედეგი',
    consultation: 'მიღებაზე ჩაწერა',
    contact: 'კონტაქტი',
    definitionTitle: 'პიგმენტური რეტინიტი',
    definition1: 'მიეკუთვნება ბადურის მემკვიდრული დისტროფიების',
    definition2: 'დაავადებათა ჯგუფს. დაავადების დროს ზიანდება თვალის პიგმენტური ეპითელიუმის ფუნქცია,',
    definition3: 'რაც ავტომატურად იწვევს ფოტორეცეპტორული უჯრედების- ჩხირები და კოლბების დისფუნქციას, რომელნიც უზრუნველყოფენ დღის, ღამის და პერიფერიულ მხედველობას. პიგმენტური რეტინიტი პროგრესირებადი დაავადებაა და ყველა კონკრეტულ შემთხვევაში სხვადასხვა',
    definition4: 'სისწრაფით ხდება მხედველობის დაკარგვა, რომელიც ხშირად სიბრმავით მთავრდება.',
    definition5: 'პიგმენტური რეტინიტის ფორმიდან გამომდინარე, დაავადების გამოვლინება და პირველი',
    definition6: 'სიმტომები შესაძლოა 3-5 წლის ასაკში ან 30-50-60 წლის ასაკშიც დაიწყოს.',
    distrophiesTitle1: 'ბადურის მემკვიდრულ დისტროფიებს',
    distrophiesTitle2: 'რომელსაც წარმატებით ვმკურნალობთ მიეკუთვნება:',
    distrophies: [
      'ტაბორეტინალური აბიოტროფია.',
      'ბესტის დაავადება.',
      'შტარდგარტის დაავადება',
      'კოლბურ-ჩხიროვანი ბადურის დისტროფია.',
      'ბადურის თანდაყოლილი აბიოტროფია',
      'და სხვა, ორგანიზმის რესურსიდან გამომდინარე',
    ],
    initialSymptomsTitle: 'საწყისი სიმპტომები',
    initialSymptomsText: 'ბადურის დისტროფიების დროს, პიგმენტური რეტინიტის საწყის სტადიაზე, შესაძლოა მხედველობის სიმახვილე რამდენიმე საათით (დღით) დაქვეითთდეს და მერე ისევ ნორმაში ჩადგეს. საწყისი სიმპტომები შეიძლება ნებისმიერ ასაკში გამოვლინდეს. როგორც წესი, დაავადება ბავშობაში იწყება და 30 წლამდე ხდება მისი დიაგნოსტირება.',
    childrenWarning: 'განსაკუთრებით ყურადსაღებია ბავშვები!',
    childrenText1: 'მნიშვნელოვანია დააკვირდეთ და მიაქციოთ ყურადღება უჭირს თუ არა პატარას გადაადგილება სიბნელეში. შესაძლოა ხშირად ეცემა, ეჯახება საგნებს, არ თამაშობს ეზოში შებინდებისას და სხვა.',
    childrenText2: 'თუ რომელიმე სიმპტომს შეამჩნევთ, აუცილებლად ჩაუტარეთ პატარას გამოკვლევები, რათა დროულად იქნას პრობლემა გამოვლენილი და ნამკურნალები.',
    primarySymptomsTitle: 'მნიშვნელოვანი პირველადი სიმპტომები:',
    primarySymptoms: [
      { num: '1', lines: ['დიზორიენტაცია შებინდებისას,', 'დღის მხედველობის შენარჩუნების ფონზე.'] },
      { num: '2', lines: ['ხანგრძლივი ადაპტაცია მკვეთრი', 'სინათლიდან სიბნელეში გადასვლისას.'] },
    ],
    noteTitle: 'გაითვალისწინეთ!',
    noteText: 'პიგმენტური რეტინიტის საწყისი სიმპტომები, შესაძლოა თვალის სხვადასხვა დაავადებებსაც ახასიათებდეს. მხოლოდ ექიმ-ოფთალმოლოგს შეუძლია მათი დიფერენციაცია და სწორი დიაგნოზის დასმა.',
    mainSymptomsTitle: 'ძირითადი სიმპტომები',
    mainSymptoms: [
      'ნისლი თვალის წილ.',
      'წაშლილი, არა მკვეთრი გამოსახულება.',
      'პერიოდულად დღის მხედველობის დაქვეითება.',
      'მხედველობის ველის შევიწროვება.',
      'მომატებული მგრძნობელობა შუქის მიმართ.',
      'ფერების აღქმის დაქვეითება.',
      'მილისებური (ტუნელური) მხედველობა.',
    ],
    whyDecreaseTitle: 'რატომ კლებულობს მხედველობა?',
    whyText1: 'ბადურა გარსი ტვინის ნაწილია, ანუ იგივე ნერვული ქსოვილი. ბადურის უჯრედები (ფოტორეცეპტორები) აღიქვამენ შუქის იმპულსებს და ახდენენ მათ ტრანსფორმირებას ნერვულ იმპულსებად.',
    whyText2: 'ფოტორეცეპტორები ის უჯრედებია, რომლებიც გარდაქმნიან შუქის იმპულსებს ნერვულ იმპულსებად. მათ მიეკუთვნება კოლბები და ჩხირები რომლებიც განაპირობებენ დღის, ღამის და სხვა ტიპის მხედველობას. მათი გამართული ფუნქციონირება დამოკიდებულია უჯრედ შიდა გამუდმებით მიმდინარე ნივთიერებათა ცვლის გამართულ მუშაობაზე.',
    whyText3: 'პიგმენტური რეტინიტის და ბადურის სხვა დისტროფიების დროს, პიგმენტურ ეპითელიუმის უჯრედებში ირღვევა ნივთიერებათა ცვლა. ფოტორეცეპტორები ვერ გარდაქნიან შუქის იმპულსებს ნერვულ იმპულსებათ და ტვინი ვერ ღებულობს ინფორმაციას, შესაბამისად ვერ ამუშავებს მას. უჯრედების უმრავლესობა "მძინარე" - პარაბიოტულ მდგომარეობაში გადადის, რაც დამატებით აფერხებს ნერვული იმპულსის წარმოქმნას. შედეგად - ირღვევა დღის და ღამის მხედველობა, ფერების აღქმა.',
    magotherapyTreatTitle: 'მაგოთერაპიით მკურნალობა.',
    magotherapyTreatText: 'მაგოთერაპიით ბადურის დისტროფიების მკურნალობისას, ჩვენი მიზანია მოვუმატოთ პაციენტს მხედველობა, შევამციროთ არსებული სიმპტომები რაც დაავადების პროგრესირების შენელებით ან შეჩერებით ვლინდება.',
    treatWithUs: 'ჩვენ ვმკურნალობთ პაციენტს და არა დაავადებას!',
    treatmentPrognosis: 'მაგოთერაპიით მკურნალობისას, გამოკვლევების საფუძველზე ვიკვლევთ კონკრეტული ორგანიზმის რესურს და პირველივე ვიზიტისას 90% სიზუსტით ვაძლევთ პროგნოზს, თუ რამდენად მოემატება კონკრეტულ ადამიანს მხედველობა მკურნალობის შემდეგ. გამოკვლევების საფუძველზე, ყველა პაციენტს ვუდგენთ მკურნალობის ინდივიდუალურ სქემას, რაც განაპირობებს პოზიტურ მკურნალობის შედეგს.',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    howVisionRestoredTitle: 'როგორ აღდგება მხედველობა მაგოთერაპიით?',
    howText1: 'სპეციალურად მაგოთერაპიისათვის შექმნილი აპარატურა, რომელსაც კანის ზემოდან ვანთავსებთ მხედველობის ანალიზატორის მიმართულებით, წამის 0,002 ნაწილში ააქტიურებს უჯრედ შიდა ნივთიერებათა ცვლას. შედეგად ცოცხალი, მაგრამ პარაბიოტულ "მიძინებულ" მდგომარეობაში მყოფი ფოტორეცეპტორები იწყებენ ფუნქციონირებს — მათ უკვე შეუძლიათ შუქის იმპულსის ნეირონებათ გარდაქმნა. მხედველობის ანალიზატორი იმავე სისწრაფით ახდენს ადექვატურ რეაგირებას ამ იმპულსებზე და მატულობს მხედველობა.',
    howText2: 'მრავალწლიანმა სამეცნიერო კვლევებით დადგინდა, რომ უჯრედშიდა ნივთიერებათა ცვლის აღდგენა განაპირობებს მრავალ დადებით ბიოქიმიურ ცვლილებებს მთელ ორგანიზმში. ხდება ციტოკინების და ზრდის ენდოგენური ფაქტორების გამოთვისუფლება. ზრდის ფაქტორები არეგულირებენ უჯრედების ზრდას და მათ გამრავლებას, ახდენენ უჯრედების დიფერენციაციას, ანუ არა სპეციალიზირებულ უჯრედებს გარდაქმნიან სპეციალიზირებულ უჯრედებად და განაპირობებენ ორგანიზმის გამართულ ფუნქციონირებას.',
    howText3: 'ციტოკინები — განსაკუთრებული ნივთიერებაა, რომელსაც სხვადასხვა უჯრედები გამოყოფენ. ციტოკინები თავიანთი ზემოქმედებით ახდენენ სხვა უჯრედების ფუნქციის სტიმულაციას, რომლებიც იცავენ ფოტორეცეპტორებს დაზიანებისაგან, ხოლო ბადურა გარსს — ახალი დეგენერაციული კერების გაჩენისაგან. ეს და სხვა პოზიტიური ბიოქიმიური პროცესები უზრუნველყოფენ მაგოთერაპიით არა მარტო მხედველობის აღდგენას, არამედ დაავადების პროგრესირების შეჩერებას ან შენელებას, რაც ყველა კონკრეტულ შემთხვევაში ინდივიდუალურია.',
    successRateText: 'მაგოთერაპიით მკურნალობისას 90% შემთხვევაში მხედველობის',
    successRateText2: 'აღდგენა ხდება დისტროფიების ჯგუფში შესულ "განუკურნებადი"',
    successRateText3: 'დაავადებების დროს მხოლოდ აპარატურის გამოყენებით. გამორიცხულია გართულებები, რისკი, გვერდითი მოვლენები და სხვა',
    resultsTitle: 'მაგოთერაპიის შედეგები:',
    results: [
      { title: '1. მატულობს ცენტრალური მხედველობა.', text: 'რასაც პაციენტი 1 საათში გაელვებების სახით აღიქვამს. ათ დღიანი პროცედურების შედეგად "გაელვებების" ხანგრძლივობა და ნათელი ხედვის პერიოდები იზრდება.' },
      { title: '3. უმჯობესდება მხედველობა შებინდებისას.', text: 'პაციენტი თავისუფლად გადაადგილდება, აღარ ეჯახება საგნებს.' },
      { title: '5. საგნები უფრო მკვეთრ ფორმას იძენენ.', text: 'უმჯობესდება ცხოვრების ხარისხი.' },
      { title: '2. მცირდება ან ქრება შუქის "ბლიკები" თვალის წინ.', text: 'შუქისადმი ადაპტაციის უნარი მცირდება.' },
      { title: '4. შესაძლებელი ხდება ფერების მკვეთრი აღქმა.', text: 'პაციენტის ფსიქოლოგიური მდგომარეობა უმჯობესდება.' },
      { title: '6. ფართოვდება მხედველობის ველი.', text: 'პაციენტს უადვილდება უცხო გარემოში გადაადგილება.' },
    ],
    patientVideosTitle: 'პაციენტების გამოცდილება',
    moreVideosYoutube: 'სხვა ვიდეოები YouTube-ზე →',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    pageTitle1: 'Retinal Dystrophies.',
    pageTitle2: 'Pigmentary Retinitis.',
    heroText1: 'Magotherapy will help you restore vision',
    heroText2: 'at the expense of reviving your body\'s resources.',
    heroText3: 'Effective and safe treatment with Magotherapy',
    heroText4: 'is a reality at our clinic!',
    resultInOneHour: 'Results within 1 hour of testing — no complications, no risk — stable results',
    consultation: 'Consultation',
    contact: 'Contact',
    definitionTitle: 'Pigmentary Retinitis',
    definition1: 'Belongs to the group of hereditary retinal dystrophies',
    definition2: 'diseases. During the disease, the function of the eye\'s pigment epithelium is damaged,',
    definition3: 'which automatically leads to dysfunction of photoreceptor cells — rods and cones, which ensure daytime, nighttime, and peripheral vision. Pigmentary retinitis is a progressive disease and in each specific case, at different',
    definition4: 'rates, vision loss occurs, which often ends in blindness.',
    definition5: 'Depending on the form of pigmentary retinitis, the manifestation of the disease and the first',
    definition6: 'symptoms may begin at age 3-5 or even at 30-50-60 years of age.',
    distrophiesTitle1: 'Hereditary retinal dystrophies',
    distrophiesTitle2: 'which we successfully treat include:',
    distrophies: [
      'Taboreretinal abiotrophy.',
      'Best\'s disease.',
      'Stargardt disease',
      'Cone-rod retinal dystrophy.',
      'Congenital retinal abiotrophy',
      'and others, depending on the organism\'s resources',
    ],
    initialSymptomsTitle: 'Initial symptoms',
    initialSymptomsText: 'In retinal dystrophies, at the initial stage of pigmentary retinitis, visual acuity may decrease for several hours (days) and then normalize again. Initial symptoms can appear at any age. As a rule, the disease begins in childhood and is diagnosed before the age of 30.',
    childrenWarning: 'Children require special attention!',
    childrenText1: 'It is important to observe and pay attention to whether the child has difficulty moving in the dark. They may frequently fall, bump into objects, not play outside at dusk, etc.',
    childrenText2: 'If you notice any symptom, be sure to have the child examined so that the problem can be detected and treated in a timely manner.',
    primarySymptomsTitle: 'Important primary symptoms:',
    primarySymptoms: [
      { num: '1', lines: ['Disorientation at dusk,', 'with preserved daytime vision.'] },
      { num: '2', lines: ['Prolonged adaptation when', 'transitioning from bright light to darkness.'] },
    ],
    noteTitle: 'Please note!',
    noteText: 'The initial symptoms of pigmentary retinitis may also be characteristic of various other eye diseases. Only an ophthalmologist can differentiate them and make the correct diagnosis.',
    mainSymptomsTitle: 'MAIN SYMPTOMS',
    mainSymptoms: [
      'Foggy vision.',
      'Blurred, not sharp image.',
      'Periodic decrease in daytime vision.',
      'Narrowing of the visual field.',
      'Increased sensitivity to light.',
      'Decreased color perception.',
      'Tubular (tunnel) vision.',
    ],
    whyDecreaseTitle: 'Why does vision decrease?',
    whyText1: 'The retinal membrane is part of the brain — the same nervous tissue. Retinal cells (photoreceptors) perceive light impulses and transform them into nerve impulses.',
    whyText2: 'Photoreceptors are the cells that transform light impulses into nerve impulses. They include cones and rods, which determine daytime, nighttime, and other types of vision. Their proper functioning depends on the proper operation of intracellular metabolism.',
    whyText3: 'In pigmentary retinitis and other retinal dystrophies, metabolism is disrupted in pigment epithelial cells. Photoreceptors cannot transform light impulses into nerve impulses and the brain cannot receive information, accordingly cannot process it. The majority of cells enter a "sleeping" — parabiotical state, which additionally hinders nerve impulse generation. As a result — daytime and nighttime vision is disturbed, and color perception is impaired.',
    magotherapyTreatTitle: 'Magotherapy Treatment.',
    magotherapyTreatText: 'During Magotherapy treatment for retinal dystrophies, our goal is to improve the patient\'s vision and reduce existing symptoms, which is achieved by slowing or stopping disease progression.',
    treatWithUs: 'We treat the patient, not just the disease!',
    treatmentPrognosis: 'During Magotherapy treatment, based on examinations, we study each organism\'s resources and at the very first visit provide a 97% accurate prognosis of how much vision improvement can be expected after treatment. Based on the examinations, we create an individual treatment plan for each patient, which determines the positive treatment outcome.',
    seeMoreMago: 'See more → Magotherapy',
    howVisionRestoredTitle: 'How is vision restored with Magotherapy?',
    howText1: 'The apparatus specially created for Magotherapy, which we place on the skin in the direction of the visual analyzer, in 0.002 seconds activates intracellular metabolism. As a result, photoreceptors that are alive but in a parabiotical "sleeping" state begin to function — they can now transform light impulses into neurons. The visual analyzer responds adequately to these impulses at the same speed and vision increases.',
    howText2: 'Many years of scientific research have established that restoring intracellular metabolism determines many positive biochemical changes throughout the body. Cytokines and endogenous growth factors are released. Growth factors regulate cell growth and proliferation, differentiate cells — transform non-specialized cells into specialized cells and determine the proper functioning of the organism.',
    howText3: 'Cytokines are a special substance secreted by various cells. Cytokines stimulate the function of other cells that protect photoreceptors from damage and the retinal membrane from the appearance of new degenerative foci. These and other positive biochemical processes ensure not only vision restoration but also stopping or slowing disease progression with Magotherapy, which is individual in each specific case.',
    successRateText: 'With Magotherapy treatment, 79% of cases experience painless and safe',
    successRateText2: 'vision restoration in "incurable" diseases included',
    successRateText3: 'in the retinal dystrophy group.',
    resultsTitle: 'Results of Magotherapy:',
    results: [
      { title: '1. Central vision increases.', text: 'The patient perceives this within 1 hour in the form of "flashes". After ten days of procedures, the duration of "flashes" and periods of clear vision increase.' },
      { title: '3. Vision at dusk improves.', text: 'The patient moves freely, no longer bumps into objects.' },
      { title: '5. Objects become sharper.', text: 'Quality of life improves.' },
      { title: '2. Light "glares" before the eyes decrease or disappear.', text: 'Ability to adapt to light decreases.' },
      { title: '4. Sharp color perception becomes possible.', text: 'Patient\'s psychological state improves.' },
      { title: '6. Visual field expands.', text: 'Moving in unfamiliar surroundings becomes easier for the patient.' },
    ],
    patientVideosTitle: 'PATIENT EXPERIENCE',
    moreVideosYoutube: 'More videos on YouTube →',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    pageTitle1: 'Дистрофии сетчатки.',
    pageTitle2: 'Пигментный ретинит.',
    heroText1: 'Маготерапия поможет вам восстановить зрение',
    heroText2: 'за счёт возрождения ресурсов вашего организма.',
    heroText3: 'Эффективное и безопасное лечение Маготерапией',
    heroText4: 'у нас — реальность!',
    resultInOneHour: 'Результат через 1 час тестирования — без осложнений и риска — стабильный результат',
    consultation: 'Консультация',
    contact: 'Контакт',
    definitionTitle: 'Пигментный ретинит',
    definition1: 'Относится к группе наследственных дистрофий сетчатки',
    definition2: 'заболеваний. При болезни нарушается функция пигментного эпителия глаза,',
    definition3: 'что автоматически приводит к дисфункции фоторецепторных клеток — палочек и колбочек, обеспечивающих дневное, ночное и периферическое зрение. Пигментный ретинит — прогрессирующее заболевание, и в каждом конкретном случае с разной',
    definition4: 'скоростью происходит потеря зрения, которая нередко заканчивается слепотой.',
    definition5: 'В зависимости от формы пигментного ретинита проявление болезни и первые',
    definition6: 'симптомы могут начаться в возрасте 3-5 лет или даже в 30-50-60 лет.',
    distrophiesTitle1: 'Наследственные дистрофии сетчатки,',
    distrophiesTitle2: 'которые мы успешно лечим, включают:',
    distrophies: [
      'Таборетинальная абиотрофия.',
      'Болезнь Беста.',
      'Болезнь Штаргардта',
      'Колбочко-палочковая дистрофия сетчатки.',
      'Врождённая абиотрофия сетчатки',
      'и другие, исходя из ресурсов организма',
    ],
    initialSymptomsTitle: 'Начальные симптомы',
    initialSymptomsText: 'При дистрофиях сетчатки, на начальной стадии пигментного ретинита, острота зрения может снизиться на несколько часов (дней), а затем вернуться к норме. Начальные симптомы могут проявиться в любом возрасте. Как правило, болезнь начинается в детстве и диагностируется до 30 лет.',
    childrenWarning: 'Особого внимания требуют дети!',
    childrenText1: 'Важно наблюдать и обращать внимание, есть ли у малыша трудности с передвижением в темноте. Возможно, он часто падает, натыкается на предметы, не играет на улице в сумерках и т.д.',
    childrenText2: 'Если вы заметите какой-либо симптом, обязательно проведите обследование малыша, чтобы проблема была выявлена и пролечена своевременно.',
    primarySymptomsTitle: 'Важные первичные симптомы:',
    primarySymptoms: [
      { num: '1', lines: ['Дезориентация в сумерках,', 'при сохранении дневного зрения.'] },
      { num: '2', lines: ['Длительная адаптация при', 'переходе от яркого света к темноте.'] },
    ],
    noteTitle: 'Имейте в виду!',
    noteText: 'Начальные симптомы пигментного ретинита могут быть характерны и для различных других глазных заболеваний. Только врач-офтальмолог может их дифференцировать и поставить правильный диагноз.',
    mainSymptomsTitle: 'ОСНОВНЫЕ СИМПТОМЫ',
    mainSymptoms: [
      'Туман перед глазами.',
      'Размытое, нечёткое изображение.',
      'Периодическое снижение дневного зрения.',
      'Сужение поля зрения.',
      'Повышенная чувствительность к свету.',
      'Снижение цветового восприятия.',
      'Трубчатое (тоннельное) зрение.',
    ],
    whyDecreaseTitle: 'Почему снижается зрение?',
    whyText1: 'Сетчатка является частью мозга — той же нервной тканью. Клетки сетчатки (фоторецепторы) воспринимают световые импульсы и преобразуют их в нервные импульсы.',
    whyText2: 'Фоторецепторы — это клетки, преобразующие световые импульсы в нервные импульсы. К ним относятся колбочки и палочки, обеспечивающие дневное, ночное и другие виды зрения. Их нормальное функционирование зависит от правильной работы внутриклеточного метаболизма.',
    whyText3: 'При пигментном ретините и других дистрофиях сетчатки в клетках пигментного эпителия нарушается метаболизм. Фоторецепторы не могут преобразовать световые импульсы в нервные импульсы, мозг не получает информацию и, соответственно, не может её обработать. Большинство клеток переходит в "спящее" — парабиотическое состояние, что дополнительно препятствует генерации нервного импульса. В результате нарушается дневное и ночное зрение, цветовое восприятие.',
    magotherapyTreatTitle: 'Лечение Маготерапией.',
    magotherapyTreatText: 'При лечении дистрофий сетчатки Маготерапией наша цель — улучшить зрение пациента и уменьшить существующие симптомы, что достигается замедлением или остановкой прогрессирования болезни.',
    treatWithUs: 'Мы лечим пациента, а не болезнь!',
    treatmentPrognosis: 'При лечении Маготерапией, на основании обследований, мы изучаем ресурсы конкретного организма и при первом же визите с точностью 97% даём прогноз, насколько улучшится зрение после лечения. На основании обследований каждому пациенту мы составляем индивидуальную схему лечения, что обусловливает положительный результат лечения.',
    seeMoreMago: 'Подробнее → Маготерапия',
    howVisionRestoredTitle: 'Как восстанавливается зрение Маготерапией?',
    howText1: 'Специально созданная для Маготерапии аппаратура, которую мы помещаем на кожу в направлении зрительного анализатора, за 0,002 секунды активирует внутриклеточный метаболизм. В результате живые, но находящиеся в парабиотическом "спящем" состоянии фоторецепторы начинают функционировать — они теперь могут преобразовывать световые импульсы в нейроны. Зрительный анализатор с той же скоростью адекватно реагирует на эти импульсы, и зрение улучшается.',
    howText2: 'Многолетние научные исследования установили, что восстановление внутриклеточного метаболизма обусловливает множество положительных биохимических изменений во всём организме. Происходит высвобождение цитокинов и эндогенных факторов роста. Факторы роста регулируют рост и размножение клеток, дифференцируют клетки — превращают неспециализированные клетки в специализированные и обеспечивают нормальное функционирование организма.',
    howText3: 'Цитокины — особое вещество, выделяемое различными клетками. Цитокины стимулируют функцию других клеток, защищающих фоторецепторы от повреждения, а сетчатку — от появления новых дегенеративных очагов. Эти и другие положительные биохимические процессы обеспечивают Маготерапией не только восстановление зрения, но и остановку или замедление прогрессирования болезни, что в каждом конкретном случае индивидуально.',
    successRateText: 'При лечении Маготерапией в 79% случаев происходит безболезненное и безопасное',
    successRateText2: 'восстановление зрения при "неизлечимых" заболеваниях,',
    successRateText3: 'входящих в группу дистрофий сетчатки.',
    resultsTitle: 'Результаты Маготерапии:',
    results: [
      { title: '1. Увеличивается центральное зрение.', text: 'Пациент воспринимает это в течение 1 часа в виде "вспышек". После десяти дней процедур продолжительность "вспышек" и периодов чёткого зрения увеличивается.' },
      { title: '3. Улучшается зрение в сумерках.', text: 'Пациент свободно передвигается, больше не натыкается на предметы.' },
      { title: '5. Предметы приобретают более чёткие очертания.', text: 'Улучшается качество жизни.' },
      { title: '2. Световые "блики" перед глазами уменьшаются или исчезают.', text: 'Способность адаптироваться к свету снижается.' },
      { title: '4. Становится возможным чёткое цветовосприятие.', text: 'Психологическое состояние пациента улучшается.' },
      { title: '6. Расширяется поле зрения.', text: 'Пациенту становится легче ориентироваться в незнакомой обстановке.' },
    ],
    patientVideosTitle: 'ОПЫТ ПАЦИЕНТА',
    moreVideosYoutube: 'Другие видео на YouTube →',
  },
};

export function usePigmenturetiniteTranslations(language: Language) {
  return pigmenturetiniteTranslations[language];
}
