import { Language } from '../contexts/LanguageContext';

export const sharedTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    bookBtn1: 'ექიმთან',
    bookBtn2: 'მიღებაზე',
    bookBtn3: 'ჩაწერა',
    whatsAppBtn: 'დააკლიკეთ ვათსაფზე დასაკავშირებლად',
    consultation: 'კონსულტაცია',
    contact: 'კონტაქტი',
    resultInOneHour: 'შედეგი ტესტირებიდან ერთ საათში ------- გართულების და რისკის გარეშე ---------- სტაბილური შედეგი',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    patientVideos: 'რას ჰყვებიან ჩვენი პაციენტები?',
    moreVideosYoutube: 'სხვა ვიდეოები YouTube-ზე →',
    treatWithUs: 'ჩვენ ვმკურნალობთ პაციენტს და არა დაავადებას!',
    treatmentPrognosis: 'მაგოთერაპიით მკურნალობისას, გამოკვლევების საფუძველზე ვიკვლევთ კონკრეტული ორგანიზმის რესურს და პირველივე ვიზიტისას 97% სიზუსტით ვაძლევთ პროგნოზს, თუ რამდენად მოემატება კონკრეტულ ადამიანს მხედველობა მკურნალობის შემდეგ. გამოკვლევების საფუძველზე, ყველა პაციენტს ვუდგენთ მკურნალობის ინდივიდუალურ სქემას, რაც განაპირობებს პოზიტიურ მკურნალობის შედეგს.',
    treatmentResults: 'მაგოთერაპიის შედეგები:',
    contactToday: 'დაგვიკავშირდი დღესვე',
    whatPatientsSay: 'რაზე &nbsp; საუბრობენ &nbsp; ჩვენი &nbsp; პაციენტები:',
    modalTitle: 'ექიმთან მიღებაზე ჩაწერა',
    labelDate: 'სასურველი თარიღი',
    labelName: 'სახელი გვარი',
    labelEmail: 'Email',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
    submitting: 'იგზავნება...',
    successTitle: 'თქვენი განაცხადი მიღებულია!',
    successMessage: 'ჩვენ დაგიკავშირდებით მალე.',
    errorMessage: 'შეცდომა. გთხოვთ სცადოთ თავიდან.',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    bookBtn1: 'Book',
    bookBtn2: 'Appointment',
    bookBtn3: 'with Doctor',
    whatsAppBtn: 'Click to contact on WhatsApp',
    consultation: 'Consultation',
    contact: 'Contact',
    resultInOneHour: 'Results within 1 hour of testing — no complications, no risk — stable results',
    seeMoreMago: 'See more → Magotherapy',
    patientVideos: 'What our patients say?',
    moreVideosYoutube: 'More videos on YouTube →',
    treatWithUs: 'We treat the patient, not just the disease!',
    treatmentPrognosis: 'During Magotherapy treatment, based on examinations, we study each organism\'s resources and at the very first visit we provide a 97% accurate prognosis of how much vision improvement a specific person can expect after treatment. Based on the examinations, we create an individual treatment plan for each patient, which determines the positive treatment outcome.',
    treatmentResults: 'Results of Magotherapy:',
    contactToday: 'Contact Us Today',
    whatPatientsSay: 'W H A T &nbsp; O U R &nbsp; P A T I E N T S &nbsp; S A Y:',
    modalTitle: 'Book an Appointment with the Doctor',
    labelDate: 'Preferred Date',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
    submitting: 'Sending...',
    successTitle: 'Booking received!',
    successMessage: 'We will contact you shortly.',
    errorMessage: 'Something went wrong. Please try again.',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    bookBtn1: 'Записаться',
    bookBtn2: 'на приём',
    bookBtn3: 'к врачу',
    whatsAppBtn: 'Написать в WhatsApp',
    consultation: 'Консультация',
    contact: 'Контакт',
    resultInOneHour: 'Результат через 1 час тестирования — без осложнений и риска — стабильный результат',
    seeMoreMago: 'Подробнее → Маготерапия',
    patientVideos: 'Что говорят наши пациенты?',
    moreVideosYoutube: 'Другие видео на YouTube →',
    treatWithUs: 'Мы лечим пациента, а не болезнь!',
    treatmentPrognosis: 'При лечении Маготерапией, на основании обследований, мы изучаем ресурсы конкретного организма и при первом же визите с точностью 97% даём прогноз, насколько улучшится зрение у конкретного человека после лечения. На основании обследований каждому пациенту мы составляем индивидуальную схему лечения, что обусловливает положительный результат лечения.',
    treatmentResults: 'Результаты Маготерапии:',
    contactToday: 'Свяжитесь с нами сегодня',
    whatPatientsSay: 'Ч Т О &nbsp; Г О В О Р Я Т &nbsp; Н А Ш И &nbsp; П А Ц И Е Н Т Ы:',
    modalTitle: 'Записаться на приём к врачу',
    labelDate: 'Желаемая дата',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
    submitting: 'Отправка...',
    successTitle: 'Заявка принята!',
    successMessage: 'Мы свяжемся с вами в ближайшее время.',
    errorMessage: 'Произошла ошибка. Пожалуйста, попробуйте снова.',
    youtubeBannerText: 'С результатами и опытом пациентов, проходивших лечение Маготерапией, вы можете ознакомиться на нашем YouTube-канале.',
    youtubeBannerLink: 'Нажмите здесь, чтобы посмотреть',
  },
};

export const youtubeBannerTranslations = {
  ge: {
    text: 'მაგოთერაპიით მკურნალობის პაციენტების შედეგებს და გამოცდილებას შეგიძლიათ გაეცნოთ ჩვენს იუთუბის არხზე.',
    linkLabel: 'სანახავად დააჭირეთ აქ',
  },
  en: {
    text: 'You can view patient results and experiences from Magotherapy treatment on our YouTube channel.',
    linkLabel: 'Click here to watch',
  },
  ru: {
    text: 'С результатами и опытом пациентов, проходивших лечение Маготерапией, вы можете ознакомиться на нашем YouTube-канале.',
    linkLabel: 'Нажмите здесь, чтобы посмотреть',
  },
};

export function useSharedTranslations(language: Language) {
  return sharedTranslations[language];
}
