import { Language } from '../contexts/LanguageContext';

const aboutTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    bookBtn1: 'ექიმთან',
    bookBtn2: 'მიღებაზე',
    bookBtn3: 'ჩაწერა',
    clinicTitle: 'თვალის კლინიკა "ახალი ტექნოლოგიები — MaGo"',
    magoTherapy: 'მაგოთერაპია',
    aboutUs: 'ჩვენს &nbsp; შესახებ',
    heroText: 'მხოლოდ ჩვენთან პირველივე ვიზიტზე ვაძლევთ პროგნოზს რამდენად მოემატება მხედველობა, რომელსაც პაციენტი მეორე დღეს ყველგან აღიქვამს. დაავადების ხანგრძლივობას, სირთულეს და პაციენტის ასაკს მნიშვნელობა არ აქვს.',
    sinceText: 'ჩვენ წარმატებით ვმკურნალობთ მაგოთერაპიით 1996 წლიდან.',
    clinicSectionTitle: 'კლინიკა "ახალი ტექნოლოგიები — MaGo"',
    patentAlt: 'პატენტი',
    clinicDesc: 'მაკა გოგიაშვილის თერაპია, მაგოთერაპია — აპარატურული პერსონიფიცირებული მკურნალობა. დაფუძნებულია 12 გამოგონებაზე.‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ მხედველობის აღდგენა ქირურგიისა და მედიკამენტების გარეშე.‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎‎‎ ‎ სტაბილური შედეგები. გამორიცხულია ნებისმიერი გართულება, რისკი, ალერგია. ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎გამოგონებები და მაგოთერაპია დაცულია საერთაშორისო პატენტებით.',
    aboutUsBanner: 'ჩვენს &nbsp; შესახებ',
    tbilisiClinicIntro: 'თბილისში, კლინიკა "ახალი ტექნოლოგიები -MaGo" შექმნის მიზანი იყო აღგვედგინა მხედველობა ადამიანებისათვის, რომლებმაც იმედი დაკარგეს სრულფასოვანი ცხოვრების.',
    bioIntro: 'მაკა გოგიაშვილი 1979 წელს დაამთავრა თბილისის სახელმწიფო სამედიცინო ინსტიტუტი. 1983 წლიდან სწავლობდა და მუშაობდა მოსკოვში, თვალის მიკროქირურგიის ინსტიტუტში.',
    bio2: 'მნიშვნელოვანი როლი მაგოთერაპიის მეთოდის ინოვაციების შემუშავებაში შეასრულა ტვინის ინსტიტუტში აკადემიკოს ნატალია ბეხტერევას ხელმძღვანელობით ჩატარებულმა კვლევებმა - ხედვის ანალიზატორსა და მთელ ორგანიზმზე.‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ სწავლისა და მუშაობის წლებში 1500-ზე მეტ პაციენტს აღუდგინა მხედველობა.',
    methodText: 'ორგანიზმის შიდა რესურსის განსაზღვრის უნიკალური, ავტორიზებული მეთოდი გვაძლევს საშუალებას, მივცეთ პაციენტს პროგნოზი მკურნალობის სავარაუდო შედეგზე ყველა კონკრეტულ შემთხვევაში. კლინიკური გამოცდილება და სრულყოფისაკენ სწრაფვა საშუალებას გვაძლევს შევქმნათ ინდივიდუალური სამკურნალო გეგმა რომელიც ადაპტირებულია კონკრეტული ორგანიზმისთვის. ეს ერთ-ერთი ფაქტორია რომელიც გვეხმარება აღვუდგინოთ მხედველობა იმედ დაკარგულ პაციენტებს',
    treatmentAlsoFor: 'მხედველობის აღდგენა მაგოთერაპიით ხდება როგორც ბანალური დაავადებების დროს,უშედეგოდ ჩატარებული ოპერაციების შემდეგ, აგრეთვე იმ დაავადებების დროს როდესაც არსებული მკურნალობის მეთოდებით უშედეგოა.',
    diseaseList: [
      { label: 'პიგმენტური რეტინიტი', to: '/results/pigmentary-retinitis' },
      { label: 'ბადურის დისტროფიები', to: '/results/pigmentary-retinitis' },
      { label: 'მაკულოდისტროფია', to: '/results/pigmentary-retinitis' },
      { label: 'ქორეორეტინიტი', to: '/results/pigmentary-retinitis' },
      { label: 'თანდაყოლილი აბიოტროფია', to: '/results/pigmentary-retinitis' },
      { label: 'ნისტაგმი', to: '/results/general' },
      { label: 'გლაუკომა', to: '/results/glaukoma' },
      { label: 'სიელმე', to: '/results/sielme' },
      { label: 'ამბლიოპია', to: '/results/amblyopia' },
      { label: 'ასტიგმატიზმი', to: '/results/astigmatizm' },
      { label: 'და სხვა (ორგანიზმის რესურსიდან გამომდინარე)', to: '/results/general' },
    ],
    advantagesTitle: 'ჩვენი &nbsp; კლინიკის &nbsp; უპირატესობები',
    experience: '30+ წლიანი გამოცდილება მაგოთერაპიით.',
    patientsCount: '1996 წლიდან 2025 წლამდე 10000 ზე მეტმა ადამიანმა გაიარა მაგოთერაპიის კურსი.',
    qualityImprove: 'მაგოთერაპია აუმჯობესებს პაციენტების ცხოვრების ხარისხს!',
    statsTitle: 'წარმატების &nbsp; სტატისტიკა &nbsp; — &nbsp; დაავადებების &nbsp; დროს',
    repeatCourse1: 'მეთოდის სრული ფიზიოლოგიურობიდან გამომდინარე, მაგოთერაპიის კურსი',
    repeatCourse2: 'შეიძლება განმეორდეს',
    repeatCourse3: 'სასურველი მხედველობის აღდგენამდე,',
    repeatCourse4: 'ყოველ 6 – 9 – 12 თვეში ერთხელ.',
    repeatCourse5: 'განმეორებითი მაგოთერაპიის კურსები დამატებით',
    repeatCourse6: 'აუმჯობესებს მხედველობას.',
    researchText: 'გამოცდილება და შედეგების ანალიზი უზრუნველყოფს ინდივიდუალური მიდგომის მაქსიმალურ ეფექტს.',
    howVisionRestored: 'როგორ აღდგება მხედველობა მაგოთერაპიით',
    howText: 'მხედველობის აღდგენა მაგოთერაპიით ხდება სპეციალური კანის ზემოდან განთავსებული აპარატურით, რომელიც ზემოქმედებს როგორც ბადურაზე, ისე ტვინის იმ ნაწილებზე, რომლებიც პასუხისმგებელია სინათლის სიგნალების აღქმაზე. ინოვაციური აპარატურის ზემოქმედებით უჯრედები მდიდრდება ჟანგბადით, უმჯობესდება და რეგულირდება უჯრედშიდა ცვლა. ცვლის პროცესის გაუმჯობესება ხელს უწყობს სინათლის სიგნალის ნერვულ იმპულსად გადაქცევას, რომელიც ტვინის შესაბამის ნაწილებში გადამუშავდება ნათელ და მკვეთრ გამოსახულებად. უჯრედშიდა ცვლის პროცესის აღდგენა ხდება 0.002 წამის მეასედის განმავლობაში, რაც უზრუნველყოფს მხედველობის აღდგენას ამდენად წარმოუდგენლად მოკლე დროში.',
    seeMoreMago: 'იხილეთ მეტი → მაგოთერაპია',
    authorTitle: 'მაგოთერაპიის &nbsp; ავტორი &nbsp; და &nbsp;კლინიკის &nbsp; ხელმძღვანელი',
    academicQual: 'აკადემიური კვალიფიკაცია',
    publicActivity: 'საზოგადოებრივი აქტიურობა',
    publications: 'ნაბეჭდი შრომები',
    awards: 'ჯილდოები',
    academicCvText: '1978: ექიმის დიპლომი. თბილისის სახელმწიფო სამედიცინო ინსტიტუტი.\n1979: ქირურგ-ექიმის დიპლომი. თბილისის სახელმწიფო სამედიცინო ინსტიტუტი.\n1985: მოსკოვის თვალის მიკროქირურგიის კომპლექსი (ასპირანტურა).\n1989: სამეცნიერო კვლევებმა, ჩატარებულმა ტვინის ინსტიტუტში, მნიშვნელოვანი როლი შეასრულა მაგოთერაპიის მეთოდის შემუშავებაში. სამედიცინო მეცნიერებათა კანდიდატის დიპლომი. ᲛᲜᲢᲙ მიკროქირურგია თვალის. მოსკოვი.\n1990: სერთიფიკატი მხედველობის ნერვის ატროფიის მკურნალობის შესახებ. როსტოვის ნეიროკიბერნეტიკის სახელმწიფო ინსტიტუტი. რუსეთი.\n1991: სერთიფიკატი უკონტაქტო ნეიროსტიმულაციის გამოყენებაში. საბჭოთა კავშირის სოციალური ინვესტორების ორგანიზაცია. მოსკოვი.\n1993: სერთიფიკატი დაბალი ინტენსივობის ლაზეროთერაპიის გამოყენებაში. რუსეთის სამედიცინო აკადემია — პოსტდიპლომური სწავლება. მოსკოვი.\n1995: მოსკოვის თვალის მიკროქირურგიის კომპლექსი (დოქტორანტურა).\n1997-1999: სერთიფიკატი ტვინის ფუნქციური ბიოქიმიის შემსწავლელი კურსი, ადამიანის ტვინის ინსტიტუტი, რუსეთის მეცნიერებათა აკადემია.\n1999: Course on "Prevention of Blindness". Bethesda, Maryland, Washington D.C., U.S.A.\n1999: Course on "OPHTHALMOMETRY". Bethesda, Maryland, Washington D.C., U.S.A.\n2000: სამედიცინო მეცნიერებათა დოქტორის დიპლომი. მოსკოვის თვალის მიკროქირურგიის ინსტიტუტი',
    publicActivityText: '1996: ნიუ-იორკის სამეცნიერო აკადემიის ქმედითი წევრი.\n1996: ევროპელ ოფთალმოლოგთა საბჭოს წევრი.\n1997: საქველმოქმედო საზოგადოება "ქალები მშვიდობისა და სიცოცხლისათვის".\n2000: საერთაშორისო საქველმოქმედო კლუბი "Rotary International Club".\n2004: საქართველოს მეცნიერთა და სპეციალისტთა ასოციაცია.\n2005: საქართველოს მეცნიერთა და სპეციალისტთა ასოციაცია. ლექცია — "რატომ არის სათვალე თვალის ყავარჯენი".\n2012: MEDICAL WOMEN\'S INTERNATIONAL ASSOCIATION CENTRAL EUROPEAN REGIONAL CONGRESS. "რა იცით ნისტაგმისა და მხედველობის ნერვის ატროფიის მკურნალობის ახალი მეთოდის შესახებ".\n2012: ექიმთა პოსტდიპლომური განათლების ასოციაცია. "მაგოთერაპიით ნამკურნალები პაციენტების შორეული შედეგები".',
    publicationsText: '1975: ი. ჯავახიშვილის სახ. თბილისის სამედიცინო ინსტიტუტის სტუდენტური სამეცნიერო საბჭოს 38-ე კონფერენცია — "ჰიპერთერმიული სინდრომი ბავშვთა ქირურგიის პრაქტიკაში", გვ. 181.\n1975: ერევანი — 17-ე სრულიად საკავშირო კონფერენცია ბავშვთა ქირურგიის სტუდენტური სამეცნიერო საზოგადოების — "ბარძაყის ძვლის მოტეხილობის მკურნალობისათვის", გვ. 346.\n1976: ყაზანი — 18-ე სრულიად საკავშირო კონფერენცია — "ჩირქოვანი ჭრილობების კომპლექსური ენზიმოთერაპია", გვ. 203.\n1977: უფა — 19-ე სრულიად საკავშირო კონფერენცია — "აპენდიკულარული პერიტონიტის მკურნალობისათვის", გვ. 179.\n1978: BIALYMSTOK — 18 UCZELNIANA KONFERENCJA — "ნაწლავის პეტლის სასიცოცხლო უნარიანობის განსაზღვრა", გვ. 36.\n1986: სიმპოზიუმი მოსკოვი–თელავი — მ. გოგიაშვილი "კოლაგენის მოლეკულური რეგენერაცია ოფთალმოლოგიაში", გვ. 11.\n1988: სამედიცინო სარეფერატო ჟურნალი №1 — ა. ივაშინა, მ. გოგიაშვილი — "რადიალური კერატოტომიის რეფრაქციული ეფექტიანობის კვლევა", გვ. 11.\n1988: რაციონალიზატორული წინადადება "რადიალური კერატოტომიის დასერვის მინიმალური რაოდენობის განსაზღვრის მეთოდი". მოწმობა №753.\n1997: Gogiashvili M. — "Application of red and infrared laser in a complex treatment of NYSTAGMUS and OPTICAL NERVE ATROPHIES." The First International Congress. Laser Health \'97. Page 38. Limassol, Cyprus.\n1998: გოგიაშვილი მ.ა. — მხედველობის ნერვის ნაწილობრივი ატროფიის მკურნალობის მეთოდი. მოსკოვი. გამოგონების პატენტი №2146909.\n1998: გოგიაშვილი მ.ა. — რეფრაქციული ანომალიის მკურნალობის მეთოდი ამბლიოპიასთან ერთობლიობაში. მოსკოვი. გამოგონების პატენტი №2146910.\n1998: გოგიაშვილი მ.ა. — მხედველობის სიმახვილის შესწავლის მოწყობილობა. მოსკოვი. სასარგებლო მოდელის მოწმობა №14127.\n1998: გოგიაშვილი მ.ა. — აკომოდაციის მკურნალობის მოწყობილობა. მოსკოვი. სასარგებლო მოდელის მოწმობა №13149.\n2000: გოგიაშვილი მ.ა. — ბადურის თანდაყოლილი დეგენერაციის სამკურნალო მოწყობილობა. №14126.\n2000: გოგიაშვილი მ.ა. — ამბლიოპიის სამკურნალო მოწყობილობა. №12918.\n2000: გოგიაშვილი მ.ა. — მხედველობის ვარჯიშის მოწყობილობა. №14114; №14127.\n2000: გოგიაშვილი მ.ა. — თვალის სამკურნალო მოწყობილობა. №15455.\n2000: გოგიაშვილი მ.ა. — მხედველობის სიმახვილის შემოწმების მოწყობილობა. №14010.',
    awardsText: '1975: I პრემია ერევნის სამედიცინო ინსტიტუტისგან — საუკეთესო მოხსენება ბავშვთა ქირურგიის სრულიად საკავშირო კონფერენციაზე.\n1978: საპატიო სიგელი — თბილისის სახელმწიფო სამედიცინო ინსტიტუტი, სტუდენტური სამეცნიერო საზოგადოების საბჭოში აქტიური მონაწილეობისთვის.\n2026: მედიცინის განვითარებაში განსაკუთრებული წვლილის შეტანასითვის მიენიჭა წოდება \'ათწლეულის პერსონა\' თბილისი, საქართველო.',
    modalTitle: 'ექიმთან მიღებაზე ჩაწერა',
    labelDate: 'სასურველი თარიღი',
    labelName: 'სახელი გვარი',
    labelEmail: 'Email',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
    advantages: [
      { num: '1', title: 'სათვალე — "ყავარჯენია"', text: '1985 წლიდან ს.ნ. ფეოდოროვის ხელმძღვანელობით ჩატარებული მრავალწლიანი სამეცნიერო კვლევების ანალიზი გვაძლევს უფლებას განვაცხადოთ: სათვალე — ეს თვალის ყავარჯენია, რომელიც მხოლოდ ეხმარება უკეთ დაინახოს, მაგრამ არ მკურნალობს თვალს. ხშირად სათვალის ნომერი იზრდება, ხოლო მხედველობა კლებულობს. მაგოთერაპიით მკურნალობის შემდეგ სათვალე და ლინზები არ გამოიყენება.' },
      { num: '2', title: 'ორგანიზმის რესურსის აღდგენა', text: 'მეცნიერთა კვლევებით დამტკიცებულია, რომ ადამიანის ორგანიზმს გააჩნია შინაგანი, გამოუყენებელი რესურსი. მხოლოდ ჩვენს კლინიკაში შეიძლება ორგანიზმის ამ რესურსის გამოვლენა და აღდგენა ყველა კონკრეტულ შემთხვევაში, პაციენტის ასაკისა და დაავადების სიმძიმისაგან დამოუკიდებლად.' },
      { num: '3', title: 'ბუნებრივი მეთოდი', text: 'მაგოთერაპიით მკურნალობა სრულად გამორიცხავს ნებისმიერ გართულებას, რისკს, ალერგიას. ჩვენ არ ვიყენებთ მედიკამენტებს და ქირურგიას, რაც გამორიცხავს ნებისმიერ გვერდით მოვლენას.' },
      { num: '4', title: 'შედეგი — წარმოუდგენლად მოკლე დროში', text: 'მკურნალობის შედეგს პაციენტი გრძნობს მეორე  გამოკვლევის შემდეგ. შედეგის განმტკიცებისთვის საჭიროა 5 ან 10დღე , რაც ყველა კონკრეტულ შემთხვევაში ინდივიდუალურია.' },
      { num: '5', title: 'დაავადების პროგრესირება ნელდება (ჩერდება)', text: 'მაგოთერაპიის ინოვაციური ტექნოლოგიით ხდება თვალის მრავალი ქრონიკული დაავადების პროგრესირების შენელება (შეჩერება). მხედველობის გაუმჯობესება მიიღწევა შემთხვევათა 89%-ში, ხოლო სრული აღდგენა — 56%-ში.' },
      { num: '6', title: '30 წლიანი გამოცდილება', text: 'ჩვენი კლინიკური გამოცდილება საშუალებას გვაძლევს შევქმნათ ინდივიდუალური სამკურნალო გეგმა კონკრეტული პაციენტისთვის, კონკრეტული ადამიანის რესურსზე დაყრდნობით. შედეგად, აღდგება მხედველობა პაციენტებში, რომელთა თვალის დაავადებები სხვა მეთოდებით განუკურნავად მიაჩნდათ.' },
    ],
    stats: [
      { label: 'სიელმე, ასტიგმატიზმი, მიოპია', value: 98 },
      { label: 'შორსმხედველობა (ჰიპერმეტროპია)', value: 98 },
      { label: 'ამბლიოპია (გაზარმაცებული თვალი)', value: 97 },
      { label: 'ბადურის ატროფიულ-დისტროფიული პროცესები', value: 90 },
      { label: 'უშედეგო ოპერაციების შემდეგ', value: 89 },
      { label: 'გლაუკომა (მინიმალური მხედველობის არსებობისას)', value: 88 },
      { label: 'ნისტაგმი', value: 87 },
      { label: 'მხედველობის ნერვის ატროფია', value: 80 },
      { label: 'კერატოკონუსი ( საწყისი სტადიები და ოპერირებული )', value: 70 },
    ],
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    bookBtn1: 'Book',
    bookBtn2: 'Appointment',
    bookBtn3: 'with Doctor',
    clinicTitle: 'Eye Clinic "New Technologies — MaGo"',
    magoTherapy: 'MAGOTHERAPY',
    aboutUs: 'ABOUT &nbsp; US',
    heroText: 'Only with us can you find out what your body\'s resources are, which will help us naturally restore your vision. Neither the patient\'s age nor the type of disease matters.',
    sinceText: 'We have been successfully treating with Magotherapy since 1996.',
    clinicSectionTitle: 'Clinic "New Technologies — MaGo"',
    patentAlt: 'Patent',
    clinicDesc: 'Maka Gogiashvili\'s Therapy — Magotherapy — an innovative method for treating many eye diseases. Based on 12 inventions. Vision restoration without surgery or medication. Stable results. Any complication, risk, allergy are excluded. Inventions and Magotherapy are protected by international patents.',
    aboutUsBanner: 'ABOUT &nbsp; U S',
    tbilisiClinicIntro: 'In Tbilisi, the "New Technologies — MaGo" clinic was created with the goal of helping people restore their vision, especially patients who have lost hope for a full life.',
    bioIntro: 'Maka Gogiashvili graduated from the Tbilisi State Medical Institute in 1979. From 1983, she studied and worked in Moscow at the Institute of Eye Microsurgery.',
    bio2: 'An important role in developing the Magotherapy method was played by research conducted at the Brain Institute. Research into the positive effects of apparatus on the visual analyzer and the entire body made Magotherapy an innovative method. During her years of study and work, more than 1,500 patients were able to restore their vision with Magotherapy.',
    methodText: 'A unique, authorized method for determining the body\'s internal resources allows us to predict the expected treatment outcome in a specific case. Clinical experience and the pursuit of perfection allow us to create an individual treatment plan adapted to a specific organism. This is why we achieve vision restoration in many "incurable" patients.',
    treatmentAlsoFor: 'Vision restoration with Magotherapy occurs both after unsuccessful operations and in many eye conditions considered incurable:',
    diseaseList: [
      { label: 'Pigmentary Retinitis', to: '/results/pigmentary-retinitis' },
      { label: 'Retinal Dystrophies', to: '/results/pigmentary-retinitis' },
      { label: 'Macular Dystrophy', to: '/results/pigmentary-retinitis' },
      { label: 'Choreoretinitis', to: '/results/pigmentary-retinitis' },
      { label: 'Congenital Abiotrophy', to: '/results/pigmentary-retinitis' },
      { label: 'Nystagmus', to: '/results/general' },
      { label: 'Glaucoma', to: '/results/glaukoma' },
      { label: 'Strabismus', to: '/results/sielme' },
      { label: 'Amblyopia', to: '/results/amblyopia' },
      { label: 'Astigmatism', to: '/results/astigmatizm' },
      { label: 'And others (depending on the organism\'s resources)', to: '/results/general' },
    ],
    advantagesTitle: 'ADVANTAGES &nbsp; O F &nbsp; OUR &nbsp; CLINIC',
    experience: '30+ years of experience with Magotherapy.',
    patientsCount: 'From 1996 to 2025, more than 10,000 people have undergone a Magotherapy course.',
    qualityImprove: 'Magotherapy improves patients\' quality of life!',
    statsTitle: 'SUCCESS &nbsp; STATISTICS &nbsp; — &nbsp; B Y &nbsp; DISEASE',
    repeatCourse1: 'Due to the complete physiological nature of the method, the Magotherapy course',
    repeatCourse2: 'can be repeated',
    repeatCourse3: 'until the desired vision is restored,',
    repeatCourse4: 'every 6 – 9 – 12 months.',
    repeatCourse5: 'Repeated Magotherapy courses additionally',
    repeatCourse6: 'improve vision.',
    researchText: 'Scientific research on eye diseases and the development of the innovative method — Magotherapy — is based on 12 inventions, protected by international patents.',
    howVisionRestored: 'How Vision is Restored with Magotherapy',
    howText: 'Vision restoration with Magotherapy is achieved using special apparatus that acts through the skin on both the retina and the areas of the brain responsible for perceiving light signals. The action of the innovative apparatus enriches cells with oxygen, improves and regulates intracellular metabolism. The improvement of the metabolic process facilitates the conversion of light signals into nerve impulses, which are processed in corresponding brain areas into clear and sharp images. The restoration of intracellular metabolic processes takes place within 0.002 hundredths of a second, which ensures vision restoration in such an incredibly short time.',
    seeMoreMago: 'See more → Magotherapy',
    authorTitle: 'AUTHOR &nbsp; OF &nbsp; MAGOTHERAPY &nbsp; AND &nbsp; HEAD &nbsp; OF &nbsp; THE &nbsp; CLINIC',
    academicQual: 'Academic Qualifications',
    publicActivity: 'Public Activity',
    publications: 'Publications',
    awards: 'Awards',
    academicCvText: '1978: Medical Diploma. Tbilisi State Medical Institute.\n1979: Surgeon Diploma. Tbilisi State Medical Institute.\n1985: Moscow Eye Microsurgery Complex (postgraduate).\n1989: Scientific research at the Brain Institute played a significant role in developing the Magotherapy method. Candidate of Medical Sciences Diploma. MNTK Microsurgery of the Eye. Moscow.\n1990: Certificate in Optic Nerve Atrophy Treatment. Rostov State Institute of Neurocybernetics. Russia.\n1991: Certificate in non-contact neurostimulation. Soviet Union Social Investors Organization. Moscow.\n1993: Certificate in low-intensity laser therapy. Russian Medical Academy — postgraduate training. Moscow.\n1995: Moscow Eye Microsurgery Complex (doctoral).\n1997-1999: Certificate in Functional Biochemistry of the Brain. Human Brain Institute, Russian Academy of Sciences.\n1999: Course on "Prevention of Blindness". Bethesda, Maryland, Washington D.C., U.S.A.\n1999: Course on "OPHTHALMOMETRY". Bethesda, Maryland, Washington D.C., U.S.A.\n2000: Doctor of Medical Sciences Diploma. Moscow Eye Microsurgery Institute.',
    publicActivityText: '1996: Active member of the New York Academy of Sciences.\n1996: Member of the European Council of Ophthalmologists.\n1997: Charitable society "Women for Peace and Life".\n2000: International charitable club "Rotary International Club".\n2004: Association of Scientists and Specialists of Georgia.\n2005: Association of Scientists and Specialists of Georgia. Lecture — "Why glasses are a crutch for the eye".\n2012: MEDICAL WOMEN\'S INTERNATIONAL ASSOCIATION CENTRAL EUROPEAN REGIONAL CONGRESS. "What do you know about the new treatment method for nystagmus and optic nerve atrophy".\n2012: Association for Postgraduate Education of Physicians. "Long-term results of patients treated with Magotherapy".',
    publicationsText: '1975: 38th Conference of the Student Scientific Council of Tbilisi Medical Institute — "Hyperthermal Syndrome in Pediatric Surgery Practice", p. 181.\n1975: Yerevan — 17th All-Union Conference of Pediatric Surgery Students — "Treatment of Femoral Fractures", p. 346.\n1976: Kazan — 18th All-Union Conference — "Complex Enzyme Therapy of Purulent Wounds", p. 203.\n1977: Ufa — 19th All-Union Conference — "Treatment of Appendicular Peritonitis", p. 179.\n1978: BIALYMSTOK — 18 UCZELNIANA KONFERENCJA — "Determination of intestinal loop viability", p. 36.\n1986: Symposium Moscow–Telavi — M. Gogiashvili "Molecular Regeneration of Collagen in Ophthalmology", p. 11.\n1988: Medical Abstract Journal №1 — A. Ivashina, M. Gogiashvili — "Study of Refractive Efficacy of Radial Keratotomy", p. 11.\n1988: Rationalization proposal "Method for determining the minimum number of cuts in radial keratotomy". Certificate №753.\n1997: Gogiashvili M. — "Application of red and infrared laser in a complex treatment of NYSTAGMUS and OPTICAL NERVE ATROPHIES." The First International Congress. Laser Health \'97. Page 38. Limassol, Cyprus.\n1998: Gogiashvili M.A. — Method for treating partial optic nerve atrophy. Moscow. Patent №2146909.\n1998: Gogiashvili M.A. — Method for treating refractive anomaly combined with amblyopia. Moscow. Patent №2146910.\n1998: Gogiashvili M.A. — Visual acuity testing device. Moscow. Utility model certificate №14127.\n1998: Gogiashvili M.A. — Accommodation treatment device. Moscow. Utility model certificate №13149.\n2000: Gogiashvili M.A. — Device for treating congenital retinal degeneration. №14126.\n2000: Gogiashvili M.A. — Amblyopia treatment device. №12918.\n2000: Gogiashvili M.A. — Vision training device. №14114; №14127.\n2000: Gogiashvili M.A. — Eye treatment device. №15455.\n2000: Gogiashvili M.A. — Visual acuity testing device. №14010.',
    awardsText: '1975: 1st Prize from Yerevan Medical Institute — Best Presentation at All-Union Conference on Pediatric Surgery.\n1978: Honorary Certificate — Tbilisi State Medical Institute, for active participation in the Student Scientific Society Council.\n2026: For outstanding contribution to the development of medicine, awarded the title "Person of the Decade". Tbilisi, Georgia.',
    modalTitle: 'Book an Appointment with the Doctor',
    labelDate: 'Preferred Date',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
    advantages: [
      { num: '01', title: 'Glasses — "A Crutch"', text: 'Analysis of years of scientific research conducted since 1985 under the leadership of S.N. Fyodorov allows us to state: glasses are a crutch for the eye, which only helps to see better, but does not treat the eye. Often the prescription increases while vision deteriorates. After Magotherapy treatment, glasses and lenses are no longer needed.' },
      { num: '02', title: 'Body Resource Restoration', text: 'Scientific research has proven that the human body has an internal, untapped resource. Only in our clinic can this resource be identified and restored in a specific case, regardless of the patient\'s age and severity of the disease.' },
      { num: '03', title: 'Natural Method', text: 'Treatment with Magotherapy completely excludes any complications, risk, allergy. We do not use medication or surgery, which excludes any side effects.' },
      { num: '04', title: 'Results — in Incredibly Short Time', text: 'The patient feels the treatment result the next day after examination. To consolidate the result, the treatment course lasts 10–12 working days, 1–3–4 hours daily.' },
      { num: '05', title: 'Disease Progression Slows Down (Stops)', text: 'With Magotherapy\'s innovative technology, the progression of many chronic eye diseases slows down (stops). Vision improvement is achieved in 89% of cases, while complete restoration — in 56%.' },
      { num: '06', title: '25+ Years of Experience', text: 'Our clinical experience allows us to create an individual treatment plan for a specific patient, based on that specific person\'s resources. As a result, vision is restored in patients whose eye diseases were considered incurable by other methods.' },
    ],
    stats: [
      { label: 'Strabismus, Astigmatism, Myopia', value: 98 },
      { label: 'Farsightedness (Hypermetropia)', value: 98 },
      { label: 'Amblyopia (Lazy Eye)', value: 97 },
      { label: 'Retinal Atrophic-Dystrophic Processes', value: 90 },
      { label: 'After Unsuccessful Operations', value: 89 },
      { label: 'Glaucoma (with minimal vision present)', value: 88 },
      { label: 'Nystagmus', value: 87 },
      { label: 'Optic Nerve Atrophy', value: 80 },
      { label: 'Keratoconus Stage I–II', value: 70 },
    ],
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    bookBtn1: 'Записаться',
    bookBtn2: 'на приём',
    bookBtn3: 'к врачу',
    clinicTitle: 'Глазная клиника "Новые Технологии — MaGo"',
    magoTherapy: 'МАГОТЕРАПИЯ',
    aboutUs: 'О &nbsp; НАС',
    heroText: 'Только у нас вы можете узнать, каковы ресурсы вашего организма, которые помогут нам восстановить ваше зрение естественным путём. Ни возраст пациента, ни тип заболевания не имеют значения.',
    sinceText: 'Мы успешно лечим Маготерапией с 1996 года.',
    clinicSectionTitle: 'Клиника "Новые Технологии — MaGo"',
    patentAlt: 'Патент',
    clinicDesc: 'Терапия Мака Гогиашвили — Маготерапия — инновационный метод лечения многих глазных заболеваний. Основан на 12 изобретениях. Восстановление зрения без хирургии и медикаментов. Стабильные результаты. Любые осложнения, риск, аллергия исключены. Изобретения и Маготерапия защищены международными патентами.',
    aboutUsBanner: 'О &nbsp; НАС',
    tbilisiClinicIntro: 'В Тбилиси, клиника "Новые Технологии — MaGo" была создана с целью помочь людям восстановить зрение, особенно пациентам, потерявшим надежду на полноценную жизнь.',
    bioIntro: 'Мака Гогиашвили окончила Тбилисский государственный медицинский институт в 1979 году. С 1983 года училась и работала в Москве, в Институте микрохирургии глаза.',
    bio2: 'Важную роль в разработке метода Маготерапии сыграли исследования, проведённые в Институте мозга. Исследование положительных результатов воздействия аппаратуры на зрительный анализатор и весь организм сделало Маготерапию инновационным методом. За годы учёбы и работы более 1500 пациентов смогли восстановить зрение с помощью Маготерапии.',
    methodText: 'Уникальный, авторизованный метод определения внутренних ресурсов организма позволяет нам предсказать ожидаемый результат лечения в конкретном случае. Клинический опыт и стремление к совершенству позволяют нам создать индивидуальный план лечения, адаптированный к конкретному организму. Именно поэтому мы достигаем восстановления зрения у многих "неизлечимых" пациентов.',
    treatmentAlsoFor: 'Восстановление зрения с помощью Маготерапии происходит как после безуспешно проведённых операций, так и при многих считающихся неизлечимыми глазных заболеваниях:',
    diseaseList: [
      { label: 'Пигментный ретинит', to: '/results/pigmentary-retinitis' },
      { label: 'Дистрофии сетчатки', to: '/results/pigmentary-retinitis' },
      { label: 'Макулодистрофия', to: '/results/pigmentary-retinitis' },
      { label: 'Хориоретинит', to: '/results/pigmentary-retinitis' },
      { label: 'Врождённая абиотрофия', to: '/results/pigmentary-retinitis' },
      { label: 'Нистагм', to: '/results/general' },
      { label: 'Глаукома', to: '/results/glaukoma' },
      { label: 'Косоглазие', to: '/results/sielme' },
      { label: 'Амблиопия', to: '/results/amblyopia' },
      { label: 'Астигматизм', to: '/results/astigmatizm' },
      { label: 'И другие (в зависимости от ресурсов организма)', to: '/results/general' },
    ],
    advantagesTitle: 'ПРЕИМУЩЕСТВА &nbsp; НАШЕЙ &nbsp; КЛИНИКИ',
    experience: 'Более 30 лет опыта работы с Маготерапией.',
    patientsCount: 'С 1996 по 2025 год более 10 000 человек прошли курс Маготерапии.',
    qualityImprove: 'Маготерапия улучшает качество жизни пациентов!',
    statsTitle: 'СТАТИСТИКА &nbsp; УСПЕХА &nbsp; — &nbsp; ПО &nbsp; ЗАБОЛЕВАНИЯМ',
    repeatCourse1: 'Благодаря полной физиологичности метода, курс Маготерапии',
    repeatCourse2: 'может повторяться',
    repeatCourse3: 'до достижения желаемого восстановления зрения,',
    repeatCourse4: 'каждые 6 – 9 – 12 месяцев.',
    repeatCourse5: 'Повторные курсы Маготерапии дополнительно',
    repeatCourse6: 'улучшают зрение.',
    researchText: 'Научные исследования глазных заболеваний и разработка инновационного метода — Маготерапии — основаны на 12 изобретениях, защищённых международными патентами.',
    howVisionRestored: 'Как восстанавливается зрение с помощью Маготерапии',
    howText: 'Восстановление зрения с помощью Маготерапии осуществляется с помощью специальной аппаратуры, которая через кожу воздействует как на сетчатку, так и на те части мозга, которые отвечают за восприятие световых сигналов. Под воздействием инновационной аппаратуры клетки обогащаются кислородом, улучшается и регулируется внутриклеточный обмен. Улучшение обменных процессов способствует преобразованию световых сигналов в нервные импульсы, которые обрабатываются в соответствующих частях мозга в чёткое и ясное изображение. Восстановление процессов внутриклеточного обмена происходит за 0,002 сотых секунды, что обеспечивает восстановление зрения за такое невероятно короткое время.',
    seeMoreMago: 'Подробнее → Маготерапия',
    authorTitle: 'АВТОР &nbsp; МАГОТЕРАПИИ &nbsp; И &nbsp; РУКОВОДИТЕЛЬ &nbsp; КЛИНИКИ',
    academicQual: 'Академическая квалификация',
    publicActivity: 'Общественная деятельность',
    publications: 'Печатные труды',
    awards: 'Награды',
    academicCvText: '1978: Диплом врача. Тбилисский государственный медицинский институт.\n1979: Диплом хирурга. Тбилисский государственный медицинский институт.\n1985: Московский комплекс микрохирургии глаза (аспирантура).\n1989: Научные исследования, проведённые в Институте мозга, сыграли значительную роль в разработке метода Маготерапии. Диплом кандидата медицинских наук. МНТК Микрохирургия глаза. Москва.\n1990: Сертификат по лечению атрофии зрительного нерва. Ростовский государственный институт нейрокибернетики. Россия.\n1991: Сертификат по применению бесконтактной нейростимуляции. Организация социальных инвесторов СССР. Москва.\n1993: Сертификат по применению низкоинтенсивной лазеротерапии. Российская медицинская академия — постдипломное обучение. Москва.\n1995: Московский комплекс микрохирургии глаза (докторантура).\n1997-1999: Сертификат курса по функциональной биохимии мозга. Институт мозга человека, Российская академия наук.\n1999: Course on "Prevention of Blindness". Bethesda, Maryland, Washington D.C., U.S.A.\n1999: Course on "OPHTHALMOMETRY". Bethesda, Maryland, Washington D.C., U.S.A.\n2000: Диплом доктора медицинских наук. Московский институт микрохирургии глаза.',
    publicActivityText: '1996: Действительный член Нью-Йоркской академии наук.\n1996: Член Европейского совета офтальмологов.\n1997: Благотворительное общество "Женщины за мир и жизнь".\n2000: Международный благотворительный клуб "Rotary International Club".\n2004: Ассоциация учёных и специалистов Грузии.\n2005: Ассоциация учёных и специалистов Грузии. Лекция — "Почему очки — это костыль для глаза".\n2012: MEDICAL WOMEN\'S INTERNATIONAL ASSOCIATION CENTRAL EUROPEAN REGIONAL CONGRESS. "Что вы знаете о новом методе лечения нистагма и атрофии зрительного нерва".\n2012: Ассоциация постдипломного образования врачей. "Отдалённые результаты пациентов, пролеченных Маготерапией".',
    publicationsText: '1975: 38-я конференция Студенческого научного совета Тбилисского медицинского института — "Гипертермальный синдром в практике детской хирургии", стр. 181.\n1975: Ереван — 17-я Всесоюзная конференция по детской хирургии студентов — "Лечение переломов бедренной кости", стр. 346.\n1976: Казань — 18-я Всесоюзная конференция — "Комплексная энзимотерапия гнойных ран", стр. 203.\n1977: Уфа — 19-я Всесоюзная конференция — "Лечение аппендикулярного перитонита", стр. 179.\n1978: BIALYMSTOK — 18 UCZELNIANA KONFERENCJA — "Определение жизнеспособности петли кишечника", стр. 36.\n1986: Симпозиум Москва–Телави — М. Гогиашвили "Молекулярная регенерация коллагена в офтальмологии", стр. 11.\n1988: Медицинский реферативный журнал №1 — А. Ивашина, М. Гогиашвили — "Исследование рефракционной эффективности радиальной кератотомии", стр. 11.\n1988: Рационализаторское предложение "Метод определения минимального количества надрезов при радиальной кератотомии". Свидетельство №753.\n1997: Gogiashvili M. — "Application of red and infrared laser in a complex treatment of NYSTAGMUS and OPTICAL NERVE ATROPHIES." The First International Congress. Laser Health \'97. Page 38. Limassol, Cyprus.\n1998: Гогиашвили М.А. — Метод лечения частичной атрофии зрительного нерва. Москва. Патент №2146909.\n1998: Гогиашвили М.А. — Метод лечения рефракционных аномалий в сочетании с амблиопией. Москва. Патент №2146910.\n1998: Гогиашвили М.А. — Устройство для исследования остроты зрения. Москва. Свидетельство полезной модели №14127.\n1998: Гогиашвили М.А. — Устройство для лечения аккомодации. Москва. Свидетельство полезной модели №13149.\n2000: Гогиашвили М.А. — Устройство для лечения врождённой дегенерации сетчатки. №14126.\n2000: Гогиашвили М.А. — Устройство для лечения амблиопии. №12918.\n2000: Гогиашвили М.А. — Устройство для тренировки зрения. №14114; №14127.\n2000: Гогиашвили М.А. — Устройство для лечения глаз. №15455.\n2000: Гогиашвили М.А. — Устройство для проверки остроты зрения. №14010.',
    awardsText: '1975: I премия от Ереванского медицинского института — лучший доклад на Всесоюзной конференции по детской хирургии.\n1978: Почётная грамота — Тбилисский государственный медицинский институт, за активное участие в Совете студенческого научного общества.\n2026: За особый вклад в развитие медицины присвоено звание "Личность десятилетия". Тбилиси, Грузия.',
    modalTitle: 'Записаться на приём к врачу',
    labelDate: 'Желаемая дата',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
    advantages: [
      { num: '01', title: 'Очки — "Костыль"', text: 'Анализ многолетних научных исследований, проводившихся с 1985 года под руководством С.Н. Фёдорова, даёт нам право заявить: очки — это костыль для глаза, который лишь помогает видеть лучше, но не лечит глаз. Часто номер очков растёт, а зрение падает. После лечения Маготерапией очки и линзы больше не нужны.' },
      { num: '02', title: 'Восстановление ресурсов организма', text: 'Исследования учёных доказали, что в человеческом организме есть внутренний, неиспользованный ресурс. Только в нашей клинике можно выявить и восстановить этот ресурс организма в конкретном случае, независимо от возраста пациента и тяжести заболевания.' },
      { num: '03', title: 'Природный метод', text: 'Лечение Маготерапией полностью исключает любые осложнения, риск, аллергию. Мы не используем медикаменты и хирургию, что исключает любые побочные эффекты.' },
      { num: '04', title: 'Результат — в невероятно короткие сроки', text: 'Результат лечения пациент ощущает на следующий день после обследования. Для закрепления результата курс лечения продолжается 10–12 рабочих дней, ежедневно по 1–3–4 часа.' },
      { num: '05', title: 'Прогрессирование болезни замедляется (останавливается)', text: 'С помощью инновационной технологии Маготерапии прогрессирование многих хронических глазных заболеваний замедляется (останавливается). Улучшение зрения достигается в 89% случаев, а полное восстановление — в 56%.' },
      { num: '06', title: 'Более 25 лет опыта', text: 'Наш клинический опыт позволяет нам создавать индивидуальный план лечения для конкретного пациента, основываясь на ресурсах этого конкретного человека. В результате зрение восстанавливается у пациентов, чьи глазные заболевания другими методами считались неизлечимыми.' },
    ],
    stats: [
      { label: 'Косоглазие, астигматизм, миопия', value: 98 },
      { label: 'Дальнозоркость (гиперметропия)', value: 98 },
      { label: 'Амблиопия (ленивый глаз)', value: 97 },
      { label: 'Атрофически-дистрофические процессы сетчатки', value: 90 },
      { label: 'После безуспешных операций', value: 89 },
      { label: 'Глаукома (при наличии минимального зрения)', value: 88 },
      { label: 'Нистагм', value: 87 },
      { label: 'Атрофия зрительного нерва', value: 80 },
      { label: 'Кератоконус I–II стадия', value: 70 },
    ],
  },
};

export function useAboutTranslations(language: Language) {
  return aboutTranslations[language];
}
