import { Language } from '../contexts/LanguageContext';

const homeTranslations = {
  ge: {
    appointmentOnly: 'მიღება მხოლოდ წინასწარი ჩაწერით',
    bookButton1: 'ექიმთან',
    bookButton2: 'მიღებაზე',
    bookButton3: 'ჩაწერა',
    personalizedTreatment: 'აპარატურული პერსონიფიცირებული\nმკურნალობა',
    noSurgery: 'ქირურგიის და მედიკამენტების გარეშე',
    clinicAndTreatment: 'თვალის კლინიკა • აპარატურული მკურნალობა',
    visionRestoration: 'მხედველობის აღდგენა მაგოთერაპიით',
    nonSurgicalTbilisi: 'თვალის არაქირურგიული მკურნალობა თბილისში',
    heroTitle: 'მხედველობის აღდგენა მაგოთერაპიით',
    heroSubtitle: 'შედეგი ტესტირებიდან 1 საათში — გართულების და რისკის გარეშე — სტაბილური შედეგი',
    naturalMethod: 'დროით გამოცდილი ბუნებრივი მეთოდი!',
    withApparatus: 'კანის ზემოდან განთავსებული აპარატურით ვმკურნალობთ',
    noSurgeryFull: 'ქირურგიისა და მედიკამენტების გარეშე,',
    evenForIncurable: 'როგორც ბანალურ დაავადებებს აგრეთვე იმ დაავადებებს',
    thatCantBeCured: 'რომელთა განაკურნება არსებული მეთოდებით შეუძლებელია.‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ',
    patentedText: 'მაგოთერაპია დაცულია საერთაშორისო პატენტებით, რაც მეტყველებს მის ეფექტურობასა და უვნებლობაზე.',
    consultation: 'კონსულტაცია',
    contactBtn: 'კონტაქტი',
    mobilePoint1: '• კანის ზემოდან განთავსებული აპარატურით,',
    mobilePoint2: '• ქირურგიის და მედიკამენტების გარეშე',
    mobilePoint3: '• ისეთი დაავადებების დროსაც, რომელიც არ იკურნება!',
    mobilePoint4: '• დაცულია საერთაშორისო პატენტებით',
    patientsCount: '1996 წლიდან 2025 წლამდე ± 10000-ზე მეტ პაციენტს აღვუდგინეთ მხედველობა.',
    feature1: 'არ ვიყენებთ მედიკამენტებს, სათვალეს , ქირურგიას. მხოლოდ კანისზემოდან განთავსებული აპარატებით ხდება პერსონიფიცირებული მკურნალობა',
    feature2: 'დაავადების სირთულეს, ხანგრძლივობას და პაციენტის ასაკს მნიშვნელობა არ აქვს.',
    feature3: 'გამორიცხულია რისკი, ალერგია, გართულებები და გვერდითი მოვლენები.',
    feature4: 'ინოვაციური აპარატურით ვაღორძინებთ ორგანიზმის რესურსებს.',
    feature5: '97%-ში მხედველობის აღდგენა ხდება  მეორე   გამოკვლევაზე  ტესტირებიდან 1 საათში.',
    feature6: 'დაცულია საერთაშორისო პატენტებით.',
    feature7: 'მხოლოდ ჩვენ გაძლევთ პროგნოზს თუ რამდენად მოგემატებათ მხედველობა.',
    feature8: 'მაგოთერაპიის განმეორებითი კურსები დამატებით აღდგენს მხედველობას.',
    feature2mobile: 'დაავადების ხანგრძლივობას და ასაკს მნიშვნელობა არ აქვს.',
    tagline: 'მაგოთერაპია — (აპარატურული მკურნალობა) — წინსვლა მხედველობის აღდგენაში!',
    magoTherapyTitle: 'მაკა გოგიაშვილის თერაპია',
    clinicName: 'თვალის კლინიკა "ახალი ტექნოლოგიები — MaGo"',
    clinicCity: 'თბილისი (საქართველო)',
    intro1: 'თვალის კლინიკა "ახალი ტექნოლოგიები — MaGo", თბილისი (საქართველო) შეიქმნა იმისათვის, რომ დაუბრუნოს პაციენტებს მხედველობა, როგორც ბანალური დაავადებების აგრეთვე „   განუკურნებადი  „ დაავადებების დროს.',
    intro2: 'მაგოთერაპია გვაძლევს მოკლე დროში პოზიტიურ შედეგს სხვადასხვა ტიპის და სიმძიმის დაავადებათა მკურნალობისას.',
    intro3: 'პირველივე ვიზიტისას 97% სიზუსტით ვაძლევთ პროგნოზს მოსალოდნელ შედეგზე. 1 საათში მიღებულ შედეგს სჭირდება გამყარება 10-14 დღის განმავლობაში (ინდივიდუალურად).',
    intro4: 'მაგოთერაპიის შედეგი სტაბილურია 18–20 წლის განმავლობაში.',
    seeMore: 'იხილეთ მეტი → მაგოთერაპია',
    check1: '1996 წლიდან 2025 წლამდე +-10000-ზე მეტ პაციენტს აღვუდგინეთ მხედველობა.',
    check2: 'არ ვიყენებთ მედიკამენტებსა და ქირურგიას. ვმკურნალობთ მხოლოდ აპარატურით.',
    check3: '97%-ში მხედველობის აღდგენა ხდება ტესტირებიდან 1 საათში.',
    check4: 'გამორიცხულია გართულებები, რისკი და ალერგია.',
    check5: 'დაცულია საერთაშორისო პატენტებით.',
    doctorName: 'ექიმი-მეცნიერი-გამომგონებელი    ‎ ‎ ‎ ‎     ‎ ‎ ‎ ‎      ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎   მაკა გოგიაშვილი',
    doctorDesc1: '12 გამოგონების და მაგოთერაპიის ავტორი, მედიცინის აკადემიური დოქტორი, ევროპელ ოფთალმოლოგთა საბჭოს წევრი, ამერიკის სამეცნიერო და ოფთალმოლოგიური აკადემიების ქმედითი წევრი, კლინიკის ხელმძღვანელი.',
    doctorSubtitle: '2026 წელს აღიარებულია როგორც ათწლეულის საუკეთესო ექიმი-მეცნიერი.',
    doctorDesc2: 'მაგოთერაპია დროით გამოცდილი ბუნებრივი მეთოდია და აღადგენს მხედველობას 1996 წლიდან!',
    magoTitle: 'მაგოთერაპია',
    magoCard1Title: 'აღვადგენთ  ორგანიზმის რესურს',
    magoCard1: ' მხედველობის  ანალიზატორის  მიმართულებით  კანისზემოდან განთავსებული  სხვა და სხვა ტიპის აპარატურით  ხდება  მხედველობის  აღდგენა  ორგანიზმის რესურზე  დაყრდნობით',
    magoCard1Full: 'ინოვაციური აპარატურით (კანის ზემოდან), ხდება მხედველობის აღდგენა ბუნებრივად, ქირურგიის და მედიკამენტების გარეშე.',
    magoCard2Title: 'უჯრედები "იღვიძებენ"',
    magoCard2: 'მხედველობის აღდგენა დაუჯრებლად მოკლე დროში  განპირობებულია უჯრედშიდა ნივთიერებათა ცვლის აღდგენით , რის შედეგადაც  წამის  2000  ნაწილში  უჯრედები გამოდიან „ ძილის“ ( პარაბიოზის )   მდგომარეობიდან, ხდება ნეირონის ფუნქციის  გააქტიურება. იგივე დროის მონაკვეთში     ტვინი  ღებულობს   და  გადაამუშავებს ამ ნერვულ იმპულს  და თვალს მკაფიო გამოსახულება უბრუნდება',
    magoCard2Full: '1 საათში შედეგი დაკავშირებულია ნივთიერებათა ცვლის გააქტიურებასთან და იმპულსის გატარების დაჩქარებასთან (0.002 წმ).',
    magoCard3Title: 'ტვინის ვარჯიში',
    magoCard3: 'მკურნალობისას ,    ტვინი  სწავლობს  “ გაღვიძებული „   უჯრედებიდან წარმოქმნილ  ნეიროიმპულსის  გადამუშავებას,   ხდება  მხედველობის ანალიზატორის   აქტივაცია  რის შედეგადაც,   ხშირად  მხედველობა კვლავ მატულობს და ხდება მიღებული შედეგის გამყარება  მხედველობის ფუნქციონალურ აღდგენასთან  ერთად',
    magoCard3Full: 'გამორიცხულია გართულება და რისკი. მეთოდი დაცულია საერთაშორისო პატენტებით.',
    magoFootnote: 'მაგოთერაპია აღადგენს მხედველობას როგორც ბანალური დაავადებების, აგრეთვე „ განუკურნებადი „ დაავადებების დროს',
    diseaseAmblyopia: 'ამბლიოპია',
    diseasePigmentary: 'პიგმენტური რეტინიტი',
    diseaseSielme: 'სიელმე',
    diseaseAstigmatizm: 'ასტიგმატიზმი',
    diseaseGlaukoma: 'გლაუკომა',
    clinicSectionTitle: 'კლინიკა ახალი ტექნოლოგიები -MaGo“',
    clinic1: '1996 წლიდან 2025 წლამდე ჩვენ ვუმკურნალეთ +-10000-ზე მეტ პაციენტს.  ამ წლების მანძილზე  ჩვენ შევიძინეთ  შეუფასებელი გამოცდილება ,  რის საფუძველზედაც  შევძელით ყველა კონკრეტული ინდივიდისთის   მკურნალობის  ინდივიდუალური გეგმის შემუშავება  ( პერსონიფიცირებული მკურნალობა ) ',
    clinic2: 'ჩვენმა ცოდნამ, გამოცდილებამ  და სურვილმა  დავხმარებოდით  ადამიანებს  მხედველობის აღდგენაში, სხვა და  სხვა  ფაქტორებთან ერთად განაპირობეს  მიღებული შედეგების სტაბილურობა 18-20 წლის მანძილზე , მაგოთერაპიის  შექმნის  მიზანია - დავეხმაროთ ადამიანებს  ცხოვრების ხარისხის გაუმჯობესებაში როგორ ბანალური  აგრეთვე  „ განუკურნებად „ დაავდებების დროს . ჩვენთვის ენით აუწერელი სიხარული  და ემოციაა,   როდესაც     იმედ დაკარგულ ადამიანებს მხედველობა ემატება და ისინი ბედნიერები არიან!',
    seeMoreClinic: 'იხილეთ მეტი → მაგოთერაპია',
    resultQuestion1: 'მაგოთერაპია აღმიდგენს მხედველობას?',
    resultQuestion2: 'რა შედეგს შეიძლება ველოდო?',
    result1: 'მრავალწლიანი სამეცნიერო კვლევების საფუძველზე დადგინდა, რომ ნებისმიერ ორგანიზმს გააჩნია გამოუყენებელი ფარული რესურსი, მაგრამ სხვა და სხვა რაოდენობით.',
    result2: 'პირველივე ვიზიტზე ჩვენს მიერ შემუშავებული ავტორიზებული მეთოდიკით ხდება კონკრეტული ორგანიზმის რესურსის მოძიება — ასაკის, დაავადების წარმოქმნის, სირთულისა და ხანგრძლივობის მიუხედავად. გამოკვლევების საფუძველზე ჩვენ ვაძლევთ პროგნოზს თუ რამდენად მოემატება მხედველობა მაგოთერაპიით მკურნალობისას.',
    result3: 'მეორე გამოკვლევაზე პაციენტი უკვე ყველგან აღიქვამს დაპირებულ მხედველობას. ერთ საათში მიღებულ შედეგს სჭირდება გამყარება 5–10–14 დღის მანზილზე, რაც ყველა კონკრეტულ შემთხვევაში ინდივიდუალურია.',
    contactToday: 'დაგვიკავშირდით დღესვე',
    modalTitle: 'ექიმთან მიღებაზე ჩაწერა',
    labelDate: 'სასურველი თარიღი',
    labelName: 'სახელი გვარი',
    labelEmail: 'email',
    labelPhone: 'ტელეფონი',
    labelAge: 'ასაკი',
    labelIAm: 'მე ვარ',
    optionChoose: '----- აირჩიეთ -----',
    optionPatient: 'პაციენტი',
    optionFamily: 'ოჯახის წევრი',
    optionFriend: 'მეგობარი',
    labelHistory: 'დაავადების ისტორია',
    agreePolicy: 'ვეთანხმები შიდა პოლიტიკას',
    submit: 'გაგზავნა',
  },
  en: {
    appointmentOnly: 'Appointment by prior registration only',
    bookButton1: 'Book',
    bookButton2: 'Appointment',
    bookButton3: 'with Doctor',
    personalizedTreatment: 'Personalized\nApparatus Treatment',
    noSurgery: 'Without surgery or medication',
    clinicAndTreatment: 'Eye Clinic • Apparatus Treatment',
    visionRestoration: 'Vision Restoration with Magotherapy',
    nonSurgicalTbilisi: 'Non-surgical eye treatment in Tbilisi',
    heroTitle: 'Vision Restoration with Magotherapy',
    heroSubtitle: 'Results within 1 hour of testing — no complications, no risk — stable results',
    naturalMethod: 'A time-tested natural method!',
    withApparatus: 'Using apparatus placed on the skin,',
    noSurgeryFull: 'without surgery or medication,',
    evenForIncurable: 'even for conditions',
    thatCantBeCured: 'considered incurable!',
    patentedText: 'Magotherapy is protected by international patents, which speaks to its effectiveness and safety.',
    consultation: 'Consultation',
    contactBtn: 'Contact',
    mobilePoint1: '• Using apparatus placed on the skin,',
    mobilePoint2: '• Without surgery or medication',
    mobilePoint3: '• Even for conditions considered incurable!',
    mobilePoint4: '• Protected by international patents',
    patientsCount: 'From 1996 to 2025, we treated more than 10,000 patients using apparatus placed on the skin.',
    feature1: 'We do not use medication or surgery.',
    feature2: 'The duration of the disease and the patient\'s age do not matter.',
    feature3: 'Risk, allergy, complications and side effects are excluded.',
    feature4: 'We revive the body\'s resources with innovative apparatus.',
    feature5: 'In 93% of cases, vision is restored within 1 hour of testing.',
    feature6: 'Protected by international patents.',
    feature7: 'Only we can give you a prognosis of how much your vision will improve.',
    feature8: 'Repeated courses of Magotherapy additionally restore vision.',
    feature2mobile: 'The duration of the disease and age do not matter.',
    tagline: 'Magotherapy — (Apparatus Treatment) — Progress in Vision Restoration!',
    magoTherapyTitle: 'Maka Gogiashvili\'s Therapy',
    clinicName: 'Eye Clinic New Technologies — MaGo',
    clinicCity: 'Tbilisi (Georgia)',
    intro1: 'Eye Clinic New Technologies — MaGo, Tbilisi (Georgia) was created to restore vision to patients, especially in cases of diseases that are currently untreatable.',
    intro2: 'Magotherapy provides positive results in a short time in treating various types and degrees of diseases.',
    intro3: 'At the first visit, we provide a 97% accurate prognosis for the expected result. The result obtained in 1 hour needs to be reinforced over 10-14 days (individually).',
    intro4: 'The results of Magotherapy are stable for 18–20 years.',
    seeMore: 'See more → Magotherapy',
    check1: 'From 1996 to 2025, we restored vision to more than 10,000 patients.',
    check2: 'We do not use medication or surgery. We treat using apparatus only.',
    check3: 'In 93% of cases, vision is restored within 1 hour of testing.',
    check4: 'Complications, risk, and allergy are excluded.',
    check5: 'Protected by international patents.',
    doctorName: 'Dr. Maka Gogiashvili',
    doctorDesc1: 'Author of 12 inventions and Magotherapy, Doctor of Medical Sciences, Member of the European Board of Ophthalmologists, Active Member of American Scientific and Ophthalmological Academies, Head of the Clinic.',
    doctorSubtitle: 'Recognized in 2026 as the best physician-scientist of the decade.',
    doctorDesc2: 'Magotherapy is a time-tested natural method that has been restoring vision since 1996!',
    magoTitle: 'Magotherapy',
    magoCard1Title: 'Natural Restoration',
    magoCard1: 'Using innovative apparatus (on the skin surface), vision is restored naturally, without surgery or medication.',
    magoCard1Full: 'Using innovative apparatus (on the skin surface), vision is restored naturally, without surgery or medication.',
    magoCard2Title: 'Rapid Mechanism',
    magoCard2: 'The 1-hour result is due to the activation of cellular metabolism and the acceleration of nerve impulse transmission (0.002 sec).',
    magoCard2Full: 'The 1-hour result is related to the activation of cellular metabolism and the acceleration of impulse transmission (0.002 sec).',
    magoCard3Title: 'Safety',
    magoCard3: 'Complications, side effects, and risk are excluded. The method is protected by international patents.',
    magoCard3Full: 'Complications and risk are excluded. The method is protected by international patents.',
    magoFootnote: 'Magotherapy restores vision even in diseases considered incurable.',
    diseaseAmblyopia: 'Amblyopia',
    diseasePigmentary: 'Pigmentary Retinitis',
    diseaseSielme: 'Strabismus',
    diseaseAstigmatizm: 'Astigmatism',
    diseaseGlaukoma: 'Glaucoma',
    clinicSectionTitle: 'Clinic New Technologies MaGo',
    clinic1: 'From 1996 to 2025, we treated more than 10,000 patients. Over these years, we have accumulated experience in creating individual treatment plans, which ensured result stability for 18–20 years.',
    clinic2: 'Magotherapy was created to help with both common eye diseases and to restore the vision of desperate patients with various eye conditions.',
    seeMoreClinic: 'See more → Magotherapy',
    resultQuestion1: 'Can Magotherapy restore my vision?',
    resultQuestion2: 'What results can I expect?',
    result1: 'Years of scientific research have established that every organism has an untapped hidden resource.',
    result2: 'Our authorized methodology allows us to identify and revive each organism\'s specific resources — regardless of age, disease severity or duration.',
    result3: 'At the first visit, we provide a prognosis for the expected result. After 2–3 visits, the patient already experiences daily improvement in vision, which needs to be reinforced over 5–10 days (individually).',
    contactToday: 'Contact Us Today',
    modalTitle: 'Book an Appointment with the Doctor',
    labelDate: 'Preferred Date',
    labelName: 'Full Name',
    labelEmail: 'Email',
    labelPhone: 'Phone',
    labelAge: 'Age',
    labelIAm: 'I am',
    optionChoose: '----- Choose -----',
    optionPatient: 'Patient',
    optionFamily: 'Family Member',
    optionFriend: 'Friend',
    labelHistory: 'Medical History',
    agreePolicy: 'I agree to the privacy policy',
    submit: 'Submit',
  },
  ru: {
    appointmentOnly: 'Приём только по предварительной записи',
    bookButton1: 'Записаться',
    bookButton2: 'на приём',
    bookButton3: 'к врачу',
    personalizedTreatment: 'Аппаратурное персонифицированное\nлечение',
    noSurgery: 'Без хирургии и медикаментов',
    clinicAndTreatment: 'Глазная клиника • Аппаратурное лечение',
    visionRestoration: 'Восстановление зрения Маготерапией',
    nonSurgicalTbilisi: 'Нехирургическое лечение глаз в Тбилиси',
    heroTitle: 'Восстановление зрения Маготерапией',
    heroSubtitle: 'Результат через 1 час тестирования — без осложнений и риска — стабильный результат',
    naturalMethod: 'Проверенный временем природный метод!',
    withApparatus: 'С помощью аппаратуры, размещённой на коже,',
    noSurgeryFull: 'без хирургии и медикаментов,',
    evenForIncurable: 'даже при заболеваниях,',
    thatCantBeCured: 'которые считаются неизлечимыми!',
    patentedText: 'Маготерапия защищена международными патентами, что свидетельствует о её эффективности и безопасности.',
    consultation: 'Консультация',
    contactBtn: 'Контакт',
    mobilePoint1: '• С помощью аппаратуры, размещённой на коже,',
    mobilePoint2: '• Без хирургии и медикаментов',
    mobilePoint3: '• Даже при заболеваниях, которые считаются неизлечимыми!',
    mobilePoint4: '• Защищено международными патентами',
    patientsCount: 'С 1996 по 2025 год мы пролечили более 10 000 пациентов с помощью аппаратуры, размещённой на коже.',
    feature1: 'Мы не используем медикаменты и хирургию.',
    feature2: 'Продолжительность болезни и возраст пациента не имеют значения.',
    feature3: 'Исключён риск, аллергия, осложнения и побочные эффекты.',
    feature4: 'С помощью инновационной аппаратуры восстанавливаем ресурсы организма.',
    feature5: 'В 93% случаев восстановление зрения происходит в течение 1 часа тестирования.',
    feature6: 'Защищено международными патентами.',
    feature7: 'Только мы даём прогноз того, насколько улучшится ваше зрение.',
    feature8: 'Повторные курсы Маготерапии дополнительно восстанавливают зрение.',
    feature2mobile: 'Продолжительность болезни и возраст не имеют значения.',
    tagline: 'Маготерапия — (Аппаратурное лечение) — прогресс в восстановлении зрения!',
    magoTherapyTitle: 'Терапия Мака Гогиашвили',
    clinicName: 'Глазная клиника Новые Технологии — MaGo',
    clinicCity: 'Тбилиси (Грузия)',
    intro1: 'Глазная клиника Новые Технологии — MaGo, Тбилиси (Грузия) была создана для того, чтобы вернуть пациентам зрение, особенно при заболеваниях, лечение которых сегодня безрезультатно.',
    intro2: 'Маготерапия даёт положительный результат в короткие сроки при лечении различных типов и степеней тяжести заболеваний.',
    intro3: 'При первом визите мы даём прогноз с точностью 97% на ожидаемый результат. Результат, полученный за 1 час, необходимо закрепить в течение 10–14 дней (индивидуально).',
    intro4: 'Результат Маготерапии стабилен в течение 18–20 лет.',
    seeMore: 'Подробнее → Маготерапия',
    check1: 'С 1996 по 2025 год мы восстановили зрение более 10 000 пациентам.',
    check2: 'Мы не используем медикаменты и хирургию. Лечим только с помощью аппаратуры.',
    check3: 'В 93% случаев восстановление зрения происходит в течение 1 часа тестирования.',
    check4: 'Осложнения, риск и аллергия исключены.',
    check5: 'Защищено международными патентами.',
    doctorName: 'Доктор Мака Гогиашвили',
    doctorDesc1: 'Автор 12 изобретений и Маготерапии, д.м.н., член Европейского совета офтальмологов, действительный член американских научных и офтальмологических академий, руководитель клиники.',
    doctorSubtitle: 'В 2026 году признана лучшим врачом-учёным десятилетия.',
    doctorDesc2: 'Маготерапия — проверенный временем природный метод, восстанавливающий зрение с 1996 года!',
    magoTitle: 'Маготерапия',
    magoCard1Title: 'Природное восстановление',
    magoCard1: 'С помощью инновационной аппаратуры (на поверхности кожи) зрение восстанавливается естественным путём, без хирургии и медикаментов.',
    magoCard1Full: 'С помощью инновационной аппаратуры (на поверхности кожи) зрение восстанавливается естественным путём, без хирургии и медикаментов.',
    magoCard2Title: 'Быстрый механизм',
    magoCard2: 'Результат за 1 час обусловлен активацией клеточного метаболизма и ускорением проведения нервного импульса (0,002 сек).',
    magoCard2Full: 'Результат за 1 час связан с активацией клеточного метаболизма и ускорением проведения импульса (0,002 сек).',
    magoCard3Title: 'Безопасность',
    magoCard3: 'Осложнения, побочные эффекты и риск исключены. Метод защищён международными патентами.',
    magoCard3Full: 'Осложнения и риск исключены. Метод защищён международными патентами.',
    magoFootnote: 'Маготерапия восстанавливает зрение даже при заболеваниях, считающихся неизлечимыми.',
    diseaseAmblyopia: 'Амблиопия',
    diseasePigmentary: 'Пигментный ретинит',
    diseaseSielme: 'Косоглазие',
    diseaseAstigmatizm: 'Астигматизм',
    diseaseGlaukoma: 'Глаукома',
    clinicSectionTitle: 'Клиника Новые Технологии MaGo',
    clinic1: 'С 1996 по 2025 год мы пролечили более 10 000 пациентов. За эти годы мы накопили опыт в создании индивидуальных схем лечения, что обеспечило стабильность результата на 18–20 лет.',
    clinic2: 'Маготерапия создана для того, чтобы помогать как при банальных глазных заболеваниях, так и отчаявшимся пациентам в восстановлении зрения при различных глазных болезнях.',
    seeMoreClinic: 'Подробнее → Маготерапия',
    resultQuestion1: 'Восстановит ли Маготерапия моё зрение?',
    resultQuestion2: 'Каких результатов можно ожидать?',
    result1: 'Многолетние научные исследования установили, что каждый организм имеет неиспользованный скрытый ресурс.',
    result2: 'Наша авторизованная методология позволяет выявить и восстановить ресурсы конкретного организма — независимо от возраста, тяжести и продолжительности заболевания.',
    result3: 'При первом визите мы даём прогноз на ожидаемый результат. После 2–3 визитов пациент уже ежедневно ощущает улучшение зрения, которое необходимо закрепить в течение 5–10 дней (индивидуально).',
    contactToday: 'Свяжитесь с нами сегодня',
    modalTitle: 'Записаться на приём к врачу',
    labelDate: 'Желаемая дата',
    labelName: 'Имя Фамилия',
    labelEmail: 'Email',
    labelPhone: 'Телефон',
    labelAge: 'Возраст',
    labelIAm: 'Я являюсь',
    optionChoose: '----- Выберите -----',
    optionPatient: 'Пациент',
    optionFamily: 'Член семьи',
    optionFriend: 'Друг',
    labelHistory: 'История болезни',
    agreePolicy: 'Я согласен с политикой конфиденциальности',
    submit: 'Отправить',
  },
};

export function useHomeTranslations(language: Language) {
  return homeTranslations[language];
}
